% candidates 51 on were incorrectly labelled subpart(ii), so I changed it.
:- multifile answer/4.

answer(number(2),part(c),subpart(i),[1,0,"Galen beleived blood was pumped around the body, by something like a water pump, Harvey discovered how th heart works and what exactly happens."]).
answer(number(2),part(c),subpart(i),[2,2,"Harvey believed that there were capilleries that provided blood to every cell, and also that it collected oxygen in a double circulatory system. Galen believed blood flowed only once through the heart and that it didn't collect oxygen."]).
answer(number(2),part(c),subpart(i),[3,0,"William Harvey where more detailed"]).
answer(number(2),part(c),subpart(i),[4,2,"Harvey believed that there were capillaries between arteries and veins although he could not prove it. Harvey worked out that there were blood vessels like arteries and veins unlike Galen who believed spirit carried material around the body"]).
answer(number(2),part(c),subpart(i),[5,0,"William Harvey's ideas on circulation would have differed from those of Galen as Galen was a older scientist who may not have made certain discoveries due to insufficent laboratory equipment."]).
answer(number(2),part(c),subpart(i),[6,0,"Harvey's ideas on circulation were more realistic and scientific than what Galen's were."]).
answer(number(2),part(c),subpart(i),[7,2,"Harvey discovered that veins carry blood at low pressure and arteries cary blood at high pressure, he also discovered capilliaries. Galen did not know about capilliaries and thought that blood travelled at the same pressure throughout the body."]).
answer(number(2),part(c),subpart(i),[8,2,"William Harvey predicted the existence of capillaries and the double circulatory system. His ideas were much more logical - Galen believed that the blood flowed round the body and was part of the soul."]).
answer(number(2),part(c),subpart(i),[9,1,"He believed we had double circulation that consisted of pulmonary & systemic circulation. As opposed to single circulation."]).
answer(number(2),part(c),subpart(i),[10,0,"william harvey thought that blood is pumped by the heart and to all the organs, Galen thought it only went to some organs."]).
answer(number(2),part(c),subpart(i),[11,0,"he believed that the"]).
answer(number(2),part(c),subpart(i),[12,1,"William discovered that the blood carried circulation systems - Galan idea rather your body being filled with blood and no veins, archaries, capilliaries"]).
answer(number(2),part(c),subpart(i),[13,0,"William Harvey's ideas on circulation where more recent, which means more research had gone into it and many of Galen ideas had been developed."]).
answer(number(2),part(c),subpart(i),[14,1,"He believed that blood flowed in only one direction where as Galen believed it flowed in all directions"]).
answer(number(2),part(c),subpart(i),[15,0,"because William harvey was discovering the ideas from medical knowledge & galen was using scientific knowledge."]).
answer(number(2),part(c),subpart(i),[16,0,"He thought that the heart pumped oxygen in the blood whereas Galen believed that oxygen wasn't carried in the blood"]).
answer(number(2),part(c),subpart(i),[17,1,"William Harvey believed that humans pumped blood round the body in arteries, capillaries and veins he believed blood was continuously circulating. Galen on the other hand believed that blood was lost every time it went round the body and we had to eat to"]).
answer(number(2),part(c),subpart(i),[18,1,"harvey believed that blood was pumped round the body he looked it up with saying heart helped pump the blood round the body."]).
answer(number(2),part(c),subpart(i),[19,1,"Galen thought the heart was a single pump and blood was pumped systematically round the body. Harvey discovered the heart to be a musclur double pumps left side - oxygenated blood and right - deoxygenated blood."]).
answer(number(2),part(c),subpart(i),[20,0,"Harvey knew that the blood transported the oxygen around to the body so the body could work afficently"]).
answer(number(2),part(c),subpart(i),[21,1,"William Harvey predicted the existance of capillaries linking the other blood vessels, whilst Galen believed that life force flowed one way around the body, passing through the heart once, and along one path."]).
answer(number(2),part(c),subpart(i),[22,0,"he"]).
answer(number(2),part(c),subpart(i),[23,1,"William Harvey suggested that blood flowed in one direction which was helped through valves, and that all blood was made up of the same things. Galen thought that there were three different types of blood, that it could flow in several directions and did"]).
answer(number(2),part(c),subpart(i),[24,1,"He knew that there were capillaries in the body and that the blood flowed through the arteries at high pressure from the heart."]).
answer(number(2),part(c),subpart(i),[25,1,"William Harvey believed the idea of double circulation where the blood flows from the heart to the body capilliaries, then to the heart, then the lung capilliaries then the cycle repeates."]).
answer(number(2),part(c),subpart(i),[26,0,"Harvey thought that blood was pumped from the heart, Galen disagreed."]).
answer(number(2),part(c),subpart(i),[27,0,"William Harvey said that the blood is pumped around the body in valves wheras Galen described the structure of the heart"]).
answer(number(2),part(c),subpart(i),[28,0,"Harvies was true"]).
answer(number(2),part(c),subpart(i),[29,1,"William Harvey's idea was that the blood circulation was a one-way valve system and Galen throught it was a two way valve system."]).
answer(number(2),part(c),subpart(i),[30,0,"he believed that it was all centred around the heart and that every living thing must have one to survive"]).
answer(number(2),part(c),subpart(i),[31,1,"William Harvey believed in the double circulation system, (that the blood went twice through the heart) in one cycle"]).
answer(number(2),part(c),subpart(i),[32,0,"Harvey suggested that blood entered the heart deoxygenated and left oxygenated through the arteries. Harvey's ideas were more modern and complex than Galen's"]).
answer(number(2),part(c),subpart(i),[33,1,"Harvey introduced the idea of different types of blood vessels, an idea Galen had not introduced; he believed the vessels of the circulator system were all the same thickness."]).
answer(number(2),part(c),subpart(i),[34,0,"Galen believed that spirits in the body controlled life processes whereas Harvey proved that substances were carried in the blood through a circulatory system"]).
answer(number(2),part(c),subpart(i),[35,1,"Harvey thought that blood kept pumping round the body whereas Galen thought blood went like a tide back and forth up & down the body."]).
answer(number(2),part(c),subpart(i),[36,2,"Harvey made important discoveries about the blood circulation - he stated that within veins, valves were situated which prevented backflow and only allowed the blood to flow in one direction, which Galen did not discover that veins could do."]).
answer(number(2),part(c),subpart(i),[37,0,"Harvey said that the blood flowed into the lungs and was the reason why we can move and feel."]).
answer(number(2),part(c),subpart(i),[38,1,"Harvey believed that humans had a double circulatory system and not a single system."]).
answer(number(2),part(c),subpart(i),[39,0,"William Harvey's ideas on circulation differed from Galen because Galen's ideas were not as highly accurate as Harvey's because there were more discoveries made by the scientists as they got more highly machinery"]).
answer(number(2),part(c),subpart(i),[40,1,"The ideas on William Harvey's was that blood clotted & there was a double circulation of blood."]).
answer(number(2),part(c),subpart(i),[41,2,"Harvey's ideas were that the or one circulation around the body, the blood went through the heart twice, Galen said it went through once."]).
answer(number(2),part(c),subpart(i),[42,2,"William Harvey suggested that the blood travelled in a double circulation system and that capillaries joined arteries to veins"]).
answer(number(2),part(c),subpart(i),[43,1,"Harvey believed there to be capillaries that allowed substances to be passed through."]).
answer(number(2),part(c),subpart(i),[44,0,"Galen thought that the lungs controlled the circulation of blood and pumping blood around the body but after much research Harvey's ideas proposed that the circulation of blood is controlled by the heart."]).
answer(number(2),part(c),subpart(i),[45,1,"Harvey believed that the heart was simply a pump that pumped the same blood around. Galen thought it produced blood as well + blood was 'used up' in the body."]).
answer(number(2),part(c),subpart(i),[46,0,"Harvey -> That there were two beats and so probably two chambers in the heart to pump the blood around"]).
answer(number(2),part(c),subpart(i),[47,1,"Galen believed that blood was simuler to a tide, which flowed backwards and forwards through the veins, arteries, and capelleries. This differed to Harvey, Who disscuvered, that the blood travels in one direction only."]).
answer(number(2),part(c),subpart(i),[48,2,"William Harvey believed in the existence of a double circulation system, and predicted the existence of capilleries networked over the body. Galen, however, believed that blood moved directly from one side of the heart to the other."]).
answer(number(2),part(c),subpart(i),[49,1,"They explained how blood was oxygenated on the left side and how blood was deoxygenated on the right side. He discovered that blood was pumped into the lungs and around the blood. He discovered double circulatory system."]).
answer(number(2),part(c),subpart(i),[50,1,"William Harvey believed that blood went in a cycle from your heart, round the body and back to your heart, where as Galen thought it was produced by the heart and once it was pumped out didn't go back to the heart."]).
answer(number(2),part(c),subpart(i),[51,0,"Because they were obviusly more beleivable."]).
answer(number(2),part(c),subpart(i),[52,1,"Harvey's was correct he knew the heart pumped blood around the body. (Galen just thought it flowed one direction)"]).
answer(number(2),part(c),subpart(i),[53,0,"Harvey discovered the two different types of blood cells (white and red) and began to understand thier functions."]).
answer(number(2),part(c),subpart(i),[54,1,"Harvey believed that blood flowed one way but Galon thought it travelled in all directions. Harvey believed blood carried oxygen & Gallen did not."]).
answer(number(2),part(c),subpart(i),[55,2,"He showed that the blood circulated, and was re-used and pumped by the heart. Galen believed blood ebbed & flowed in veins & arteries. Harvey showed that arteries carry blood away from the heart and veins carry blood to the heart"]).
answer(number(2),part(c),subpart(i),[56,1,"William Harvey believed that blood is pumped to the body and returned. Then de-oxygenated. Galen believed that blood only pumped around the body in circular motions."]).
answer(number(2),part(c),subpart(i),[57,0,"William Harvey did not believe in Galen's ideas on circulation, as he believed them to be inaccurate. Harvey checked his results numerous times to ensure accuracy whereas Galen did not."]).
answer(number(2),part(c),subpart(i),[58,1,"William Harvey thought that arteries carried oxygenated blood away from the heart, and veins carried deoxygenated blood towards the heart. Galen did not have this theory."]).
answer(number(2),part(c),subpart(i),[59,0,"Galen beleived that blood was produced constantly in the liver, so it did not matter if a person bled because the body would make enough to make up for the amount lost - he beleived in blood-letting as a medical practice. Harvey beleived that blood was re"]).
answer(number(2),part(c),subpart(i),[60,1,"Galen thought the blood stayed stationary throughout the body where as Harvey thought the blood was pumped around by the heart."]).
answer(number(2),part(c),subpart(i),[61,1,"Galen beleived that our bodies made new blood because it got to our fingertips etc and was lost. William Harvey discovered that blood is recycled and pumped aroud the body again by the heart."]).
answer(number(2),part(c),subpart(i),[62,1,"Harvey believed that it was the heart that pumped blood around the body whereas Galen believed that liver was very important Galen thought that blood was made from food, but Harvey refused to believe this and"]).
answer(number(2),part(c),subpart(i),[63,1,"Galen thought the main organ of the circulatory system was the liver, whereas Harvey found it to be the heart, and Harvey showed that blood only flows one way in veins, is at a lower pressure than arterial blood. He also disproved Galen's idea of pores in"]).
answer(number(2),part(c),subpart(i),[64,0,"William Harvey was a doctor and had facts of the human body and knew a great deal about this but Galen was just a scientist"]).
answer(number(2),part(c),subpart(i),[65,0,"William is doctor how constantly checks people giving him more of a ideal experience to believe"]).
answer(number(2),part(c),subpart(i),[66,0,"Galen thought that blood did not go to the lungs but went to the rest of the body. William Harvey thought that the blood went to the lungs and the rest of the body."]).
answer(number(2),part(c),subpart(i),[67,0,"Harvey discovered aspects of the circulatory system that Galen had not yet noticed. He discovered the layout of the heart and the ways in which blood travelled (e.g arteries) whereas Galen hadn't yet noticed this and had only discovered the function of th"]).
answer(number(2),part(c),subpart(i),[68,0,"Harvey discovered the circulatory system, and what is carried around the body such as oxygen in the red blood cells. Also the direction in which it flow from the heart."]).
answer(number(2),part(c),subpart(i),[69,1,"Harvey discovered that the blood acted as a pump, not a sucking organ as Galen had believed, and that blood was pumped to the lungs rather than passing straight from the right to the left side of the heart."]).
answer(number(2),part(c),subpart(i),[70,1,"Harvey predicted the existence of capillaries which Galen had no idea about. Harvey also believed the heart was a pump and acknowledged a different between the blood entering and leaving the heart which Galen had not discovered blood, heart, capillaries."]).
answer(number(2),part(c),subpart(i),[71,1,"Harvey believed that capillaries were present without having actual evidence."]).
answer(number(2),part(c),subpart(i),[72,1,"Galen believed that the blood seeped out of the heart to all parts of the body whereas harvey believed that blood was pumped round the body."]).
answer(number(2),part(c),subpart(i),[73,1,"Harvey claimed the circulatory system was a double circulation so blood reached tissues more efficiently. (separate circulation to deliver blood to lungs & body). Galen claimed it is a single circulation."]).
answer(number(2),part(c),subpart(i),[74,1,"Galen thought that the blood only went through the heart once whereas Harvey realised it did it twice."]).
answer(number(2),part(c),subpart(i),[75,1,"Many of Galen's theories about circulation were incorrect. Harvey's idea that there were several different types of blood vessels contradicted Galen's ideas. Galen thought that the blood only pumped through the heart once everytime it was pumped around th"]).
answer(number(2),part(c),subpart(i),[76,1,"Harvey discovered the double circulation, showing oxygenated and deoxygenated blood. Galen discovered the use of arteries veins and capillaries."]).
answer(number(2),part(c),subpart(i),[77,1,"Galen believed that blood was continually produced and used up. Harvey, however, believed blood circulated continuously."]).
answer(number(2),part(c),subpart(i),[78,2,"Harvey believed the blood followed a particular route. He believed humans had a double circulatory system. Unlike Galen he also believed the heart pumped blood around the body. Galen had believed blood just moved randomly around."]).
answer(number(2),part(c),subpart(i),[79,1,"He introduced the idea of the heart pumping around the blood and the arteries and veins that are involved in the process."]).
answer(number(2),part(c),subpart(i),[80,2,"William Harvey came up with the idea of double circulation and that veins carry blood back to heart whilst arteries carry it away from heart and to every cell with capillaries. Galen came up with a single circulation."]).
answer(number(2),part(c),subpart(i),[81,2,"William Harvey's ideas were that blood is carried around in capillaries which join veins and arteries together. Galen believed that only arteries and veins existed, carrying blood in one direction."]).
answer(number(2),part(c),subpart(i),[82,2,"William Harvey believed that blood circulated around the body, pushed by the heart and then travelled in arteries and capillaries around the body"]).
answer(number(2),part(c),subpart(i),[83,2,"Harvey improved Galens discoveries by showing that there were capilaries and veins and arteries making it a two-way circulatory system"]).
answer(number(2),part(c),subpart(i),[84,2,"Galen believed that the blood just flowed from one side of the heart to the other, and did not realise that it flowed all the way around the body, transporting materials. William Harvey, however did realise this, and also predicted the existence of capill"]).
answer(number(2),part(c),subpart(i),[85,2,"William Harvey thought there were things called cappileries which connected the veins to arteries. even though he could not prove it. Galen believed that there were only veins and ateries."]).
answer(number(2),part(c),subpart(i),[86,2,"Galen thought that blood flowed from one side of the heart to the other, but William Harvey, by careful observation, discovered that there is a double circulation system and the heart pumps blood around the body and he also predicted the existance of capi"]).
answer(number(2),part(c),subpart(i),[87,2,"Galen believed that blood simply seeped in and out of tissues. Harvey suggested the idea of veins and arteries and the idea that blood can only flow in one direction."]).
answer(number(2),part(c),subpart(i),[88,1,"Galen believed that the blood would be used up by the body and needed replacing. He would bleed his patients in order to get rid of bad blood. Harvey on the other hand suggested the blood circulated, and was never replaced."]).
answer(number(2),part(c),subpart(i),[89,1,"Harvey believed that blood was pumped around the body by the heart. Galen believed that it was present everywhere in the body and stayed there."]).
answer(number(2),part(c),subpart(i),[90,2,"Galen beleived that blood did not circulate William Harvey beleived it did, he even predicted the existance of microscopic cappilaries"]).
answer(number(2),part(c),subpart(i),[91,1,"Galen believed that blood left the heart went all round the body and returned to the heart as one system not as two, one to the lungs and one to the body as Harvey believed."]).
answer(number(2),part(c),subpart(i),[92,2,"William Harvey's ideas on circulation was the idea of double circulation allowing blood to go around the whole body."]).
answer(number(2),part(c),subpart(i),[93,1,"Galen thought blood was only used once and more was made it only went round once Harvey discovered blood circulated through the body and was pumped by the heart"]).
answer(number(2),part(c),subpart(i),[94,1,"Harvey realised that blood must only flow one way. He wouldn't believe in the ideas of Galen unless he had scientific proof. Galen believed that blood could flow up and down veins, not just in one direction."]).
answer(number(2),part(c),subpart(i),[95,1,"Harveys ideas explained how blood got pumped from the heart around the body and back to the heart again, Galen did not have the idea of a constant (circularatory system)"]).
answer(number(2),part(c),subpart(i),[96,2,"William Harvey predicted the presence of cappilaries which Galen did not believe existed. Harvey also rejected Galen's theory of the blood being enumeranted with bodily spirits Harvey also thought that blood only flows one way, whereas Galen did not Harve"]).
answer(number(2),part(c),subpart(i),[97,1,"Harvey thought that deoxygenated blood was transported by the arteries and oxygenated by the veins. While Galen thought there was only one type of tube for transportation."]).
answer(number(2),part(c),subpart(i),[98,2,"William Harvey believed that there was a double circulatory system, one flowing to the body and one to the lungs. Galen believed it was only a single circulation system. Harvey also discovered capillaries."]).
answer(number(2),part(c),subpart(i),[99,0,"Harvey beleaved that the heart is a continuas pumping station, always pumping and he found out about the valves and aorter etc."]).
answer(number(2),part(c),subpart(i),[100,2,"William Harvey believed that the heart controlled the flow of blood round the body while Galen believed the lungs did this. Harvey also believed that it was a double circulatory system and blood flowed through the heart twice while Galen believed that it"]).
answer(number(2),part(c),subpart(i),[101,1,"Galen said blood flowed to and from the heart in the same vessels. Harvey said it flowed from the heart in different vessels than those in which it flowed to the heart. Galen said it flowed to and from the heart in an ebb and flow manner. Harvey said bloo"]).
answer(number(2),part(c),subpart(i),[102,1,"William Harvey believed that humans had a double circulatory system and that the heart was a double pump, whilst Galen thought that there was only a single system and the heart was a single pump."]).
answer(number(2),part(c),subpart(i),[103,1,"He believed that the heart was a double pump. Which meant that the blood passed through the heart twice in one full circulation. Whilst Galen didn't believe this."]).
answer(number(2),part(c),subpart(i),[104,1,"Galen believed that our heart was not a double pump and Harvey did believe this. Harvey thought that blood entered the heart deoxygenated and came went to the lungs and back to the heart oxygenated."]).
answer(number(2),part(c),subpart(i),[105,2,"Harvey said that blood is pumped through the body and then back to the heart in veins and arteries. Galan thought the the blood was only pumped out into the body and did not believe it circulated."]).
answer(number(2),part(c),subpart(i),[106,1,"Harvey believed the blood had to go to the heart then to the lungs to become oxygenated then back to the heart to be pumped around the body"]).
answer(number(2),part(c),subpart(i),[107,1,"William idea was that there was a double circulation and Galen thought there was only one circulation."]).
answer(number(2),part(c),subpart(i),[108,2,"William Harvey discovered that there is a double circulatory system in the body and that blood is pumbed around the body and back to the heart again. Galen had no idea of the circulatory system or the ideas of the importance of the heart to the circulatio"]).
answer(number(2),part(c),subpart(i),[109,1,"Harvey belived the heart was a pump that made blood go around the body, Galen belived the heart made the blood"]).
answer(number(2),part(c),subpart(i),[110,1,"William Harvey thought that blood was continually being pumped around the body by the heart in a cycle and recyled, Galen however thought that the liver pumped out blood, which then formed flesh"]).
answer(number(2),part(c),subpart(i),[111,1,"Galen believed that we had a single circulatory system, whereas Harvey thought that the heart also pumped blood to the lungs (therefore humans had a double circulatory system)."]).
answer(number(2),part(c),subpart(i),[112,2,"Galen thought blood went from one side of the heart straight to the other. Harvey thought it went around the body and theorized on the 'double circulation' system and the existence of capillaries."]).
answer(number(2),part(c),subpart(i),[113,0,"Galen knew the heart pumped blood around the body but did not know how. William Harvey discovered how the blood traveled, and told about the arteries, valves etc."]).
answer(number(2),part(c),subpart(i),[114,1,"Galen thought that blood was carried to and from the heart in the same veins whilst Harvey believed that blood was carried away from the heart by arteries and carried back to the heart by veins."]).
answer(number(2),part(c),subpart(i),[115,1,"William Harvey said that there was a double circulation. The right side pumped blood from the body and the left side pumped blood from the lungs to the heart."]).
answer(number(2),part(c),subpart(i),[116,1,"Galen beleived that the blood evaporated as it is used up and more is made. Harvey beleived that the blood is recycled round the body again and again (circulated)"]).
answer(number(2),part(c),subpart(i),[117,1,"William Harvey found out that we have a double circulary system which alows oxygenated and deoxygenated blood to be kept separate"]).
answer(number(2),part(c),subpart(i),[118,2,"William Harvey believed in the existance of capillaries. He introduced the heart as a double circulatory system and placed it in the right place in the anatomy, unlike Galen who did not believe in capillories and thought that the origin of everything"]).
answer(number(2),part(c),subpart(i),[119,1,"Harvey discovered that blood was pumped through the process of double circulation ie. the blood flows twice through the heart (once to the body, once to the lungs)"]).
answer(number(2),part(c),subpart(i),[120,2,"Harvey found our capillarys where already there, without the help of a microscope. He also found out that the blood flowed in a double circulatory way, Galen though differantly"]).
answer(number(2),part(c),subpart(i),[121,1,"Harvey believed there were cappillaries even though they could not be seen."]).
answer(number(2),part(c),subpart(i),[122,2,"Harvey believed in double circulation where as Galen did not. Harvey even predicted the existance of capillaries which at the time were too small to see."]).
answer(number(2),part(c),subpart(i),[123,2,"Harvey believed that there was a double circulatory system, Galen believed it was single. Harvey believed the heart pumped the blood round the body, Galen did not."]).
answer(number(2),part(c),subpart(i),[124,1,"he discovered that humans had a double circulatory system whereas Galen believed humans only had a single circulation."]).
answer(number(2),part(c),subpart(i),[125,2,"Harvey bellieved that blood flowed all around the body wheras Galen thought it went simply from one side of the heart to the other. He also predicted the existance of capillaries connecting arteries & veins which Galen did not"]).
answer(number(2),part(c),subpart(i),[126,1,"Harvey discovered that blood was pumped around blood around the body and the blood all went in the same direction around the body."]).
answer(number(2),part(c),subpart(i),[127,1,"Harvey believed that the blood was recycled, that it moved round the body and was oxygenated and deoxygenated accordingly"]).
answer(number(2),part(c),subpart(i),[128,2,"Harvey believed that blood is carried through your ateries and veins in a cycle + closed system, whereas Galen belieived that it was a backward reversed system."]).
answer(number(2),part(c),subpart(i),[129,2,"Harvey believed that instead of blood being made continually it was pumped around the body and therefore ''recycled'' He also believed that there was a double circulatory system rather than Galen's ideas of there being only a single circulatory system."]).
answer(number(2),part(c),subpart(i),[130,2,"William Harvey thought that the blood passed through the heart twice, whereas Galen thought there was only one circuit. Also, Harvey proved the existence of valves in veins which Galen did not know about."]).
answer(number(2),part(c),subpart(i),[131,1,"Galen believed that there was only one circulatory system, wheras rightly so, Harvey believed mammals had a double circulatory system."]).
answer(number(2),part(c),subpart(i),[132,1,"Galen believed blood was made by the liver and burned up as the body used it. Harvey, however thought blood was circulated continuously around the body"]).
answer(number(2),part(c),subpart(i),[133,0,"Galen thought blood reached the heart in an ebb and flow method."]).
answer(number(2),part(c),subpart(i),[134,2,"Harvey said that we had a double circulation and that blood entered the heart twice before it went around the body - heart to lungs then heart to body"]).
answer(number(2),part(c),subpart(i),[135,0,"Galen did not know how complex the circulatory system was. Galen did not understand about veins and arteries."]).
answer(number(2),part(c),subpart(i),[136,2,"William Harvey, due to careful experimentation and observations noticed that blood flows round the body in the blood vessels, he also noticed the presence of veins. He also predicted the existance of capillaries. His ideas differ from Galens as Galen had"]).
answer(number(2),part(c),subpart(i),[137,1,"Whilst Galen believed that blood was constantly produced by the heart with every heart beat and thus supplied the body with blood, William Harvey believed that the heart was a pump which helped transport the blood round the body through capillaries, blood"]).
answer(number(2),part(c),subpart(i),[138,1,"Galen believed that blood simply flowed around the body and was replaced when it was used up. Harvey discovered that the heart pumped blood around in tiny tubes called veins."]).
answer(number(2),part(c),subpart(i),[139,0,"Harvey believed that blood had to go in at one side of the heart and out at the other. Galen said it passed through the centre wall of the heart."]).
answer(number(2),part(c),subpart(i),[140,1,"He discovered that the left side of the heart pumped the blood carried by arteries and that the right side recieved blood carried by veins."]).
answer(number(2),part(c),subpart(i),[141,2,"Galen believed that blood flowed from one side of the heart to the other, and Harvey believed in a double circulatory system involving the two sides being totally separated. Galen also did not consider the existence of capillaries, which Harvey correctly"]).
answer(number(2),part(c),subpart(i),[142,2,"William Harvey believed that blood circulated round the body due to the heart and that we have what is known as a double circulatory system by which the blood goes through the heart twice for every one complete circuit of the body. Galen did not believe t"]).
answer(number(2),part(c),subpart(i),[143,2,"Harvey believed that the heart pumped blood all around the body in blood vessels through a double circulatory system, while Galen believed it was first taken from one side of the heart to the other"]).
answer(number(2),part(c),subpart(i),[144,1,"William Harvey proved that blood was pumped around the body where as galen thought that the inside of the body was made up substances called bile."]).
answer(number(2),part(c),subpart(i),[145,2,"Galen thought that blood ebbed and flowed in veins and was a single circulatory system. Harvey however, due to valves etc found out that blood flow was one directional and as there were four heart chambers, had a double circulatory system."]).
answer(number(2),part(c),subpart(i),[146,1,"Galen thought that the heart was a single pump and pumps blood around the body in a single circulation, whereas Harvey thought otherwise. He thought it was a double circulation."]).
answer(number(2),part(c),subpart(i),[147,1,"He said that blood is circulated around your body which helps digest food and keeps us alive whereas Galen had a different theory"]).
answer(number(2),part(c),subpart(i),[148,2,"Harvey believed there to be a double circulatory system which galen did not. Harvey also predicted the presence of capillaries which join arteries to veins."]).
answer(number(2),part(c),subpart(i),[149,2,"Galen did not believe that the heart pumped the blood around the body in one direction as Harvey did, and Harvey also predicted the existence of capillaries linking arteries to veins which Galen did not."]).
answer(number(2),part(c),subpart(i),[150,1,"Harvey belived in double circulation and 4 chambers of heart with oxygenated and deoxygenated blood. Galen did not have his knowledge of blood returning to heart twice"]).
answer(number(2),part(c),subpart(i),[151,1,"William Harvey discovered that the heart was a double circulatory system, whereas Galen thought there was only one. Harvey also discovered the heart has two sides for oxygenated and deoxygenated blood."]).
answer(number(2),part(c),subpart(i),[152,1,"Galen believed that the liver was responsible for the movement of blood around the body, Harvey identified the heart as the pumping organ Galen did not believe that the circulation of blood was one continous system. Harvey did and even speculated on the e"]).
answer(number(2),part(c),subpart(i),[153,1,"Galen thought blood flowed from the heart in all directions at one time until it reaches the edge of the body + then flowed back (came in + out like a tide) wherease Havey realised blood was pumped round the whole body in a circuit."]).
answer(number(2),part(c),subpart(i),[154,1,"William Harvey disuvered that blood flowed round the body in one direction."]).
answer(number(2),part(c),subpart(i),[155,2,"Harvey believed that blood is reused ie pumped in a continous cycle unlike Galen who believed that blood was always being destroyed and remanufactured, Harvey also believed in the presence of a network which is now called a capilliary network"]).
answer(number(2),part(c),subpart(i),[156,2,"Harvey believed that the body was made up of arteries pumping blood away from the heart and veins pumping blood to the heart and these were all joined by capillaries."]).
answer(number(2),part(c),subpart(i),[157,2,"William Harvey said that blood was pumped round the body by the heart, and that the blood travelled through vessels (arteries and veins). He also said that veins contained valves and he predicted the existence of capillaries linking arteries and veins. Ga"]).
answer(number(2),part(c),subpart(i),[158,0,"Harvey's ideas on circulation were that the heart provides the blood with air, and that there was more to the circulatary system than blood vessels and arteries"]).
answer(number(2),part(c),subpart(i),[159,1,"William Harvey introduced the idea of a double circulation where the heart was split into two halves and one side pumped out oxygenated blood and the other received deoxygenated blood. Galen only thought that the heart was not split into two."]).
answer(number(2),part(c),subpart(i),[160,1,"he said that the heart has two jobs, as it recieves deoxygenated blood from the lungs, it pumps oxygenated around the body, it is therefore called the double-circulatory system."]).
answer(number(2),part(c),subpart(i),[161,0,"because Harvey believed that circulation was important & Galen only knew about blood he didn't know about the circulatory system"]).
answer(number(2),part(c),subpart(i),[162,1,"William Harvey believed that blood was pumped around the system by the heart"]).
answer(number(2),part(c),subpart(i),[163,2,"Galen believed blood could flow between the two sides of the heart through pores. Harvey believed the two sides were separate. Galen believed blood 'ebbed and flowed' whereas Harvey believed it flowed in a continous circulatory system."]).
answer(number(2),part(c),subpart(i),[164,1,"Harvey came up with the idea that blood circulated round the body and was pumped. Galen thought our food was like fuel which was turned into blood."]).
answer(number(2),part(c),subpart(i),[165,2,"Galen believed that the heart simply pumped blood from one side of the heart to the other. Harvey correctly identified that the blood flowed through the heart twice making a complete circuit of the whole body, correctly identifying the existence of capill"]).
answer(number(2),part(c),subpart(i),[166,2,"He said that the heart was the central organ of the circulatory system rather than the liver. He proposed the idea of capillaries to link the veins and arterial system through careful observation, whereas Galen did not know this"]).
answer(number(2),part(c),subpart(i),[167,1,"William Harvey believed in the double circulatory system where the blood would make two trips to the heart in one circulation. Galen believed in single circulatory system."]).
answer(number(2),part(c),subpart(i),[168,2,"William Harvey said that the heart was a double pump and that there were different vessels in which blood flowed depending on which direction it was going."]).
answer(number(2),part(c),subpart(i),[169,1,"Williams believed the double circulation system. Of pumping deoxidated and oxidated blood."]).
answer(number(2),part(c),subpart(i),[170,2,"Galen believed that blood travelled directly from one side of the body to the other. Harvey dis-covered veins and arteries. He was able to find valves in veins and guessed at the existence of capillaries. He discovered the modern belief that blood travels"]).
answer(number(2),part(c),subpart(i),[171,0,"William Harvey thought that the heart was a pump and he thought it was valves that let the blood flow around the body."]).
answer(number(2),part(c),subpart(i),[172,2,"He found out that blood pumped around the body in veins and arteries that were filled with oxygen or not filled with oxygen."]).
answer(number(2),part(c),subpart(i),[173,1,"Harvey thinks that there are 4 chambers in the heart, the left side of the heart pumps oxygenated blood to the body and the right side of the heart pumps deoxygenated blood to the lungs to be oxygenated. Harvey therefore thought  humans use double circula"]).
answer(number(2),part(c),subpart(i),[174,2,"William Harvey did not believe in Galen's 'animal spirit' theory, and he predicted the existance of capillaries, which Galen did not. He refused to believe the theory without scientific evidence. He believed that blood had to flow all around the body,and"]).
answer(number(2),part(c),subpart(i),[175,2,"William Harvey believed that blood flowed through arteries and veins and predicted they were linked by capillaries. However Galen believed that blood went from one side of the body to the other."]).
answer(number(2),part(c),subpart(i),[176,0,"Harvey believed that the arteries carried blood around the body and that veins carried blood back to the lungs"]).
answer(number(2),part(c),subpart(i),[177,1,"William Harvey discovered the idea of double circulation of the blood, he believed that deoxygenated blood entered the heart and 2 pumps were present in the heart which made it leave as oxygenated. Galen believed the heart was one pump."]).
answer(number(2),part(c),subpart(i),[178,2,"Harvey believed there was a connection between the veins and arteries (now known as the capillaries) where as Galen believed the blood flowed out to the organs in vessels, and then back in the same vessels, rather like the tide - ebb and flow theory."]).
answer(number(2),part(c),subpart(i),[179,2,"Harvey believed in the presence of capillaries, and also that blood flowed in a double-circulating system"]).
answer(number(2),part(c),subpart(i),[180,1,"The wayin which William Harveys' ideas on circulation differed from Galen's is that Harvey put foreword the idea of a double circulatory system where Galen's idea was that it was a single circulatory system."]).
answer(number(2),part(c),subpart(i),[181,2,"William Harvey predicted the existance of capilleries and demonstrated that the heart pumped blood round the body. He also showed the existence of valves in veins. Galen thought that the blood flowed to organs from the stomach and new blood was constantly"]).
answer(number(2),part(c),subpart(i),[182,1,"Harvey said that blood went round the heart twice - a bouble circulatory system while Galen did not know this."]).
answer(number(2),part(c),subpart(i),[183,1,"William Harvey's idea's involved a double circulation, which is more complex than that of Galen's, showing that the blood passes through the heat twice in one full cycle. He also discovered that blood was not always oxygenated."]).
answer(number(2),part(c),subpart(i),[184,0,"because William harvey found out what blood vesels was and capilaries was where Galen didn't"]).
answer(number(2),part(c),subpart(i),[185,1,"because william came up with the idea of double circulation system which carries around oxygenated & deoxygenated blood."]).
answer(number(2),part(c),subpart(i),[186,2,"Harvey believed the body had double circulation whereas Galen did not. He believed blood travelled from the heart, to the lungs & then back to the heart, which is true. He also believed blood passed through small capillaries."]).
answer(number(2),part(c),subpart(i),[187,2,"William Harvey found that the heart was a pump that pumped blood around the body through veins & arteries. Galen thought that liver was the centre of the system. Harvey also discovered valves in veins."]).
answer(number(2),part(c),subpart(i),[188,2,"he believed blood circulated from the heart to the lungs to the heart to the body, in other words that humans had a double circulatory system."]).
answer(number(2),part(c),subpart(i),[189,1,"William Harvey believed that the blood in the body was circulated by the pumping of the heart. Galen, however, whilst recognising that the heart was a pump, believed that new blood was synthesised by the liver instead of it being re-circulated around the"]).
answer(number(2),part(c),subpart(i),[190,0,"William Harvey believed that there were two to the circulations of the blood. Half oxygenated, half not."]).
answer(number(2),part(c),subpart(i),[191,1,"Harvey introduced the idea that the heart pumped blood around the body whereas Galen did not believe this."]).
answer(number(2),part(c),subpart(i),[192,1,"Harvey discovered that humans had a double circulatory system where as Galen thought there was a single circulatory system."]).
answer(number(2),part(c),subpart(i),[193,1,"Harvey believed that blood flowed around the body in a circulatory system connected by vessels, whereas Galen believed every organ was simply connected to the heart."]).
answer(number(2),part(c),subpart(i),[194,1,"Harvey discovered that there was a double circulartory system for oxygenated blood and deoxygenated blood."]).
answer(number(2),part(c),subpart(i),[195,2,"William Harvey predicted the existence of capillaries and thought that there were two different types of blood vessels that handled oxygenated and deoxygenated blood Galen did not."]).
answer(number(2),part(c),subpart(i),[196,1,"Harvey discovered that we had a double circulatory system and Galen believed we had a singular (like a fish)"]).
answer(number(2),part(c),subpart(i),[197,2,"Harvey realised that the blood was pumped round the body through arteries and veins and predicted the existance of cappillaries, he based his ideas on experiments which he had done. As opposed to Galen, who had not seen how the veins and arteries worked a"]).
answer(number(2),part(c),subpart(i),[198,1,"Harvey discovered that the blood is pumped from the left side of the heart, all the way around the body and then back to the right side of the heart."]).
answer(number(2),part(c),subpart(i),[199,2,"Harvey thought blood flowed in a double circuit round the body, and that there were capilleries between veins and arteries. Galen had believed that the body contained spirits which kept the body alive, and that these were not pumped by the heart"]).
answer(number(2),part(c),subpart(i),[200,1,"Harvey had the idea of a double circulation system with the heart at the centre and blood passes twice through the heart in one 'lap'. Galen believed that it only passed once and it was a single system."]).

 
