:- multifile answer/4.

answer(number(4),part(b),subpart(ii),[1,1,"It means that 'man' cannot harm the goat in any way or 'he' could be prosicuted. It is designed to make the animal's numbers increase as it could only be killed by natural curcumstances."]).
answer(number(4),part(b),subpart(ii),[2,1,"They help to survive because we are protecting it so that they nobody can kill them for fur or for meat."]).
answer(number(4),part(b),subpart(ii),[3,2,"Protecting' a species means increasing its population size by making it illegal to hunt the species or greatly limiting this activity. This could also be done by preserving its natural habitat by limiting activities such as deforestation having a species in captivity and releasing it into the wild would also help increase numbers."]).
answer(number(4),part(b),subpart(ii),[4,1,"It is then illegal to shoot, harm or kill the animal because of the 'protected species' law"]).
answer(number(4),part(b),subpart(ii),[5,2,"Labelling a type of animal 'a protected species' limits the number of people hunting the creature, as this would become illegal. Sanctuaries may also be started this is when 'protected species' are bread out of captivity."]).
answer(number(4),part(b),subpart(ii),[6,0,"When an animal becomes 'a protected species' it is given more of a chance to survive by not exposing it to its natural predators, increasing numbers of its natural prey, a tabbing system on the numbers to they can be monitered It has more of a chance to survive."]).
answer(number(4),part(b),subpart(ii),[7,0,"Making an animal 'a protected species' helps it survive, as it is safe from predators and does not have to compete for food. Allowing them to live to reproduce."]).
answer(number(4),part(b),subpart(ii),[8,2,"It stops people killing the species, and encourages steps to be taken to ensure its survival. For instance, to not disturb it's habitat."]).
answer(number(4),part(b),subpart(ii),[9,1,"If an animal becomes 'protected' it means no one can kill or harm it. This means that the species has a chance to replenish and reproduce whilst they are protected so the population increases."]).
answer(number(4),part(b),subpart(ii),[10,1,"by making an animal a proteced speciase makes it illegal to hunt and kill .: allowing more them to bread succesfully."]).
answer(number(4),part(b),subpart(ii),[11,2,"Laws are enforced that make it illegal to hunt or kill the animal that is now a 'protected species', and the penalty for breaking the law deters people. Also, it brings the threat to the animal to the publics attention."]).
answer(number(4),part(b),subpart(ii),[12,1,"Increases knowledge of it's own danger to other people. May encourage them to make preventative actions towards it's extinction in the hope of avoiding trouble for them-selves if they harm it in any way."]).
answer(number(4),part(b),subpart(ii),[13,0,"By making a type of animal 'a protected species', the animal is protected from harm from humans and other animals,"]).
answer(number(4),part(b),subpart(ii),[14,1,"When an animal is declared a 'protected species' it helps it to survive because more people are made aware of it. It also helps as extra care is then taken to protect it."]).
answer(number(4),part(b),subpart(ii),[15,1,"The species would be protected against being hunted by man, there would be a punishment (eg a fine) for anyone that hunted and killed them it enables them to live in their natural habitat on their own without the threat of being killed. Man is not their natural predator."]).
answer(number(4),part(b),subpart(ii),[16,0,"The animals increased protection improves its standard of living. In effect are animals live longer, and produce more animals that have the same protection"]).
answer(number(4),part(b),subpart(ii),[17,1,"If it is living in a certain area where man wants to build on, it cannot as it is now a 'protected specie'"]).
answer(number(4),part(b),subpart(ii),[18,1,"it allows the species to procreate without the threat of being hunted for food or clothing by human beings"]).
answer(number(4),part(b),subpart(ii),[19,1,"Less people will try to kill the species so it we produce more and more babys each year"]).
answer(number(4),part(b),subpart(ii),[20,2,"It makes people aware of a dying species and also makes it illegal to hunt or kill one of these animals."]).
answer(number(4),part(b),subpart(ii),[21,1,"By protecting a species the animal will stay alive, because man is not allowed to hunt and they are prevented from danger."]).
answer(number(4),part(b),subpart(ii),[22,1,"If an animal is a ''protected species'' then it makes it illegal for the humans to damage or kill the animal. It is therefore protected and left in their natural envirnoment to encourage maximum breeding."]).
answer(number(4),part(b),subpart(ii),[23,1,"It is not hunted for a part of it (fur, horns) so is left to increase its population."]).
answer(number(4),part(b),subpart(ii),[24,1,"because they are not aloud to be harmed by man! There are people looking after them to help them survive."]).
answer(number(4),part(b),subpart(ii),[25,1,"this means that it cannot be harmed by man and will get help from places / people like RSPCA."]).
answer(number(4),part(b),subpart(ii),[26,1,"Making an animal a protected species would stop hunters from killing them and it would stop people from disterbing the animal natural habbitat."]).
answer(number(4),part(b),subpart(ii),[27,1,"Making a animal 'a protected species' will help it to survive because it stops hunters from hunting the animal so the species numbers will increase."]).
answer(number(4),part(b),subpart(ii),[28,0,"Making an animal a 'protected species' helps it to survive as it reduces the factors that could affect them. For instance it protects the species from human damage and other predators."]).
answer(number(4),part(b),subpart(ii),[29,1,"So less people try to hunt for them so they have more chance at reproducing more of the species."]).
answer(number(4),part(b),subpart(ii),[30,1,"It means it is illegal to kill, harm or capture an animal so people leave them alone, so there numbers can increase again."]).
answer(number(4),part(b),subpart(ii),[31,2,"By making animals a 'protected species' this increases the liklehood of it surviving as for example hunters are not allowed to hunt it, the animals are possibly mated under special conditions to ensure they produce much off spring. The animals could be kept in special conditions to ensure it has the required amount of food, + mates and it could be separated from its predators."]).
answer(number(4),part(b),subpart(ii),[32,1,"This is because it decreases the chance of hunters trying to hunt & kill it. They can be looked after resulting in less chance of disease. Also, so they can be breeded."]).
answer(number(4),part(b),subpart(ii),[33,0,"This helps the animal to survive because if it is protectful of their species then this animal would protect their familys and themselves."]).
answer(number(4),part(b),subpart(ii),[34,0,"If an animal is a protected species then every animal in the species is monitored and it's health is constantly checked, meaning if a disease occurs or a member of the protected species is ill then they can be treated more quickly so fewer should die from being left ill and stranded."]).
answer(number(4),part(b),subpart(ii),[35,2,"By declaring the bucardo a protected species people are alerted to its status as in great danger of being extinct and embark on schemes, such as making sure they are well fed, so that numbers begin to increase again. There may be campaigns against hunters or other human activities contributing to its fall in numbers."]).
answer(number(4),part(b),subpart(ii),[36,1,"Protecting it means to help it to survive by not allowing it to be hunted, so it lives longer and can reproduce as produce more offspring to replace itself and the partner."]).
answer(number(4),part(b),subpart(ii),[37,1,"If it is a known protected animal people would not be able to hunt it easily as that would be illegal. Therefore more would survive which could mate with others and continue the species."]).
answer(number(4),part(b),subpart(ii),[38,1,"Making an animal that has a low population a 'protected species' helps it survive because it then becomes illegal to hunt or kill them"]).
answer(number(4),part(b),subpart(ii),[39,2,"making a protected species lets people know becose, they put them on like wildlife programs to show , so hunters do not touch them, also their are signs up."]).
answer(number(4),part(b),subpart(ii),[40,1,"By making it a protected species special care is taken out so that they are not killed for no reason, so that they can reproduce and increase in number again and prevent them being wiped out."]).
answer(number(4),part(b),subpart(ii),[41,1,"By making an animal protected it stands more chance of survival, as it is not hunted for meat or pleasure. It is kept in it's natural environment without the threat of becoming extinct."]).
answer(number(4),part(b),subpart(ii),[42,0,"by doing so, you will let the animal reproduce, and help it live longer and the numbers of the animal will increase, and special care will be taken."]).
answer(number(4),part(b),subpart(ii),[43,2,"People are more aware of the animal and the animal is also protected this means that the animal by law can not be harmed."]).
answer(number(4),part(b),subpart(ii),[44,2,"Making an animal a protected species aids its survival as certain laws will be passed that prevent humans hunting or killing these animals. If harm does come to the animals through human fault it would be regarded as a serious offence. The specific environment of the species would also be protected."]).
answer(number(4),part(b),subpart(ii),[45,0,"The community will help look after it and keep track of how it lives and whether the animal is endangered where it lives. If it is, then the animal is provided another shelter."]).
answer(number(4),part(b),subpart(ii),[46,1,"It stops people from huanting the animal capturing and hirting the animal and if anyone was court they would have to pay afine or go to jail"]).
answer(number(4),part(b),subpart(ii),[47,0,"If they are protected species then it means they are rare and are few of them. Which means there would probably have more food to eat."]).
answer(number(4),part(b),subpart(ii),[48,1,"If you kill a protected species you could possible get sent to person for disobaying the law."]).
answer(number(4),part(b),subpart(ii),[49,1,"Making a type of animal 'a protected species' increases peoples awarness that they are dying out and people can be prosiquted for killing them, so people stop killing them and they survive, hopefully."]).
answer(number(4),part(b),subpart(ii),[50,0,"It helps it because it gives the goat freedom from man and other animals."]).
answer(number(4),part(b),subpart(ii),[51,1,"This is by stopping humans from making them exstinct by killing them. So therefore nothing they need should be damaged."]).
answer(number(4),part(b),subpart(ii),[52,0,"It helps it to survive because it offers the animal greater protection than it would otherwise have."]).
answer(number(4),part(b),subpart(ii),[53,1,"By making a type of animal 'a protected species' means that it cannot be killed by man for entities like meat and fur. By being protected means that man also helps to prevent any harm coming to it."]).
answer(number(4),part(b),subpart(ii),[54,1,"The animal is acknowledged to be rare and people know that it needs protection to be saved from exstinction. Monitors will be put on them so they are protected. People look after the animal and prevent it, from danger."]).
answer(number(4),part(b),subpart(ii),[55,2,"Making an animal 'a protected species' helps it to survive because, by law, it cannot be hunted or killed by man and its habitat must be protected and left unharmed."]).
answer(number(4),part(b),subpart(ii),[56,1,"becauce and coun't be haunted down no more are it would be extinked like the dowdow bird."]).
answer(number(4),part(b),subpart(ii),[57,2,"When this is done, it becomes illagel to disturb them and destroy their enviroment. You are not aloud to kill or capture them. This allows them to grow and multiply without man killing them or interfearing."]).
answer(number(4),part(b),subpart(ii),[58,1,"people can't harm them anymore, people check that they are ok and have food"]).
answer(number(4),part(b),subpart(ii),[59,2,"It makes people more aware of the animal. It may put them of hunting them. They may try and prectect the species if possible so they wont become exstinct"]).
answer(number(4),part(b),subpart(ii),[60,1,"Because it makes people more aware of it, so they are given extra care and treatment to keep them alive and reproducing."]).
answer(number(4),part(b),subpart(ii),[61,2,"this means they can't be hunted and that no-one can destroy their habitat."]).
answer(number(4),part(b),subpart(ii),[62,2,"By making an animal a protected species, its habitat becomes protected and it is illegal to kill it. This allows the animal to live longer so that hopefully, it can reproduce and replenish its species' population."]).
answer(number(4),part(b),subpart(ii),[63,1,"If an animal is a protected species then it will be encouraged to breed more and will be kept in specialised areas where humans cannot bother or touch the animal. This means that animals will have special vets to look after them and constant food supplies."]).
answer(number(4),part(b),subpart(ii),[64,2,"Making an animal protected will meen it could be illegal to kill them. Some may be kept in captivity & try to make them breed so there is more"]).
answer(number(4),part(b),subpart(ii),[65,0,"If an animal is a protected species, it would be more able to survive as it is being protected and especially looked after by conservationists which will prevent against human interference in a negative way and also natural harms to the animal."]).
answer(number(4),part(b),subpart(ii),[66,1,"When an animal is named as a 'protected species', restrictions are put on the hunting of the animal, imposing fines on hunters and so preventing deaths in this way. The species may also then benefit from money for research into conservation as a result of its new status."]).
answer(number(4),part(b),subpart(ii),[67,1,"When an animal is a protected spiecies it means that it is illegal to kill it therefore less are killed and the numbers don't decrease so much."]).
answer(number(4),part(b),subpart(ii),[68,2,"Making an animal 'a protected species' alerts people to the fact that there aren't many left, which may mean that people change certain habits, eg. hunting, shooting. Sometimes laws accompany declarations of 'protected species'."]).
answer(number(4),part(b),subpart(ii),[69,2,"When animals are made 'protected species' people try to ensure that these animals are not hunted or that their environments are not harmed. It is also that their food supplies are not damaged. These precautions protect the 'protected species' and make sure that the species can flourish in it's environment."]).
answer(number(4),part(b),subpart(ii),[70,1,"So they can produce more and not get killed by man."]).
answer(number(4),part(b),subpart(ii),[71,1,"when an animal becomes a 'protect species' it mean that it is illegal to kill or capture the animal and that these animals and their population numbers would be closely monitored."]).
answer(number(4),part(b),subpart(ii),[72,1,"If an animal's 'a protected species' it cannot be killed purposely by man and it is looked after by wildlife trusts."]).
answer(number(4),part(b),subpart(ii),[73,1,"Making an animal 'a protected species' helps it to survive as it makes humans aware of its limited numbers so they are not harmed. It also makes people who do harm them more weary of harming them"]).
answer(number(4),part(b),subpart(ii),[74,0,"A protected species' is usually given more help to survive than a normal species. It is generally observed, and all predators are kept away until the species is strong enough to survive on its own again."]).
answer(number(4),part(b),subpart(ii),[75,0,"they look after him, and that they know that they are safe."]).
answer(number(4),part(b),subpart(ii),[76,0,"Because you can't go near the land or on it and you can't touch or feed the animal, and people go and check it."]).
answer(number(4),part(b),subpart(ii),[77,2,"Making an animal 'a protected species' heightens awareness of the plight of that animal, and also aims to reduce decrease in numbers, for example by preventing hunting."]).
answer(number(4),part(b),subpart(ii),[78,1,"So no one can kill it and it reproduces and they can be protected"]).
answer(number(4),part(b),subpart(ii),[79,1,"Making a type of animal helps it to survive because they can make it breed or watch how it works to prevent extinction in the future"]).
answer(number(4),part(b),subpart(ii),[80,1,"making an animal a protected species helps it survive because it would be illegal to interfear with their habitate so their habitat will stay the same for them."]).
answer(number(4),part(b),subpart(ii),[81,2,"Making an animal a protected species helps it to survive, as they will be kept in secluded mountains away from people ruining their habitats. The people looking after them will feed them, and focus on breeding."]).
answer(number(4),part(b),subpart(ii),[82,0,"Mountain Rangers look after them making sure no Man can get to them"]).
answer(number(4),part(b),subpart(ii),[83,1,"This means that measures are taken to ensure that the animal stays alive. For example, people would not be able to hunt an animal that was a protected species."]).
answer(number(4),part(b),subpart(ii),[84,2,"A animal which is a protected species is not allowed to be killed for any reason e.g fur, ivory. Also 'protected species' are given food and are helped to breed."]).
answer(number(4),part(b),subpart(ii),[85,1,"Its carefully watched and looked after. Selective breeding could be used to enhance the number of animals"]).
answer(number(4),part(b),subpart(ii),[86,2,"Because a protected species is a species protected by the law. This involves law against poachers or other killing by man. Also conservationalists will protect their habitat and so they will be more likely to survive."]).
answer(number(4),part(b),subpart(ii),[87,2,"Once an animal has become a protected species, humans are duty-bound to disallow any actions such as hunting it or destroying its habitat, thereby increasing its likelyhood to survive & reproduce."]).
answer(number(4),part(b),subpart(ii),[88,1,"If an animal is 'a protected species' then more people are aware that they are there, and people would not do anything to jeopardise their survival."]).
answer(number(4),part(b),subpart(ii),[89,0,"It allows them to breed freely and live in free dom. The maybe provided with food also."]).
answer(number(4),part(b),subpart(ii),[90,0,"It would have less of a struggle for survival and therefore be able to reproduce and pass their genes to their offspring."]).
answer(number(4),part(b),subpart(ii),[91,1,"people protect the animal and stop hunting the animal which makes it survive longer."]).
answer(number(4),part(b),subpart(ii),[92,0,"So it can protude offspring without having to worry about man."]).
answer(number(4),part(b),subpart(ii),[93,2,"Animals are protected by law so anyone who is caught hunting it can face serious penalties including prison. It's habitat is also well protected from destruction."]).
answer(number(4),part(b),subpart(ii),[94,2,"people are not allowed to hunt or kill the animal and damages to its habitat are not allowed. People are also more aware of 'a protected species'."]).
answer(number(4),part(b),subpart(ii),[95,0,"By making an animal 'a protected species' people try and protect the species and try to help to conserve them by giving money to build new habitats or by staying away from their original habitats"]).
answer(number(4),part(b),subpart(ii),[96,2,"People are not allowed to hunt the animal. Scientists may choose to prevent the animal's extinction by breeding them in a zoo or nature reserve. It would also raise awareness about the animal, and so people will take care not to disturb them or raise money for breeding programs."]).
answer(number(4),part(b),subpart(ii),[97,2,"If an animal is a protected species hunting it and destroying its habitat is an offense punishable by law. If these kind of things are prevented the animal in question will live much longer giving it a change to procreate thus keeping the species alive."]).
answer(number(4),part(b),subpart(ii),[98,0,"If an animal is a 'protected species' nothing is allowed to deliberately harm it."]).
answer(number(4),part(b),subpart(ii),[99,1,"They protect the animals as much as they can from men and deforrestation."]).
answer(number(4),part(b),subpart(ii),[100,2,"This makes people more aware of a species' difficulty, and promotes conservation methods, such as preservation of habitat, bans on hunting, and breeding programs."]).
answer(number(4),part(b),subpart(ii),[101,2,"It helps the animal because the animal is given more rights, it would be illigal to kill it. Some may be kept in captivity to increase the numbers, before being released."]).
answer(number(4),part(b),subpart(ii),[102,2,"This measure firstly registers concern over the species so development in that area would be sensitive to the risk of destroying more of a dwindelling species habit and prevent illegal poaching by making it protected therefore giving punishments such as fines to those that harm them."]).
answer(number(4),part(b),subpart(ii),[103,0,"It stops the food chain that might occur. If (human) stop eating them they will increase in number."]).
answer(number(4),part(b),subpart(ii),[104,1,"it helps it to survive by declaring it a protected species meaning they are not allowed to be killed or poached, if they are caught they would land huge fines and jail terms. When protected allows them to reproduce without fear of poachers or hunter"]).
answer(number(4),part(b),subpart(ii),[105,1,"It helps protect the animal. It will stop hunters killing the animal. As it is endangered people will want to protect it and help it survive"]).
answer(number(4),part(b),subpart(ii),[106,1,"It means that the animal has to be looked after and that you oren't allowed to hunt it other wise you can go to jail or have to pay a fine"]).
answer(number(4),part(b),subpart(ii),[107,2,"In doing so it makes it illegal to hunt the particular species of animal. It makes people aware of their limited numbers and more cautious about how animals are treated."]).
answer(number(4),part(b),subpart(ii),[108,1,"If an animal is a protected species, it becomes illegal for it to be killed for any reason. Fewer people, therefore, are prepared to kill the protected species, and fewer die."]).
answer(number(4),part(b),subpart(ii),[109,1,"because then there not allowed to be hunted and the popilalation of the animal is looked after."]).
answer(number(4),part(b),subpart(ii),[110,0,"protecting it will help it to survive as it will be kept an eye on more looked after"]).
answer(number(4),part(b),subpart(ii),[111,1,"it makes it illegal to kill it and puts peaple watching and keeping an eye on them"]).
answer(number(4),part(b),subpart(ii),[112,2,"because it makes it illegal to kill them, some are bred in wildlife parks & zoo's etc"]).
answer(number(4),part(b),subpart(ii),[113,1,"A protected species can not be hunted or poached. If a protected species is not hunted, then there will be more of them to reproduce and increase their numbers."]).
answer(number(4),part(b),subpart(ii),[114,2,"because it stop people from hunting it or destroying it habitat giving it to bread more so it can get its number back up so it willn't become extinct"]).
answer(number(4),part(b),subpart(ii),[115,1,"By making a type of animal 'a protected species' you are making it illegal to be killed by anyone and to protect it from predators."]).
answer(number(4),part(b),subpart(ii),[116,1,"Can ban man from harming these animals in any way."]).
answer(number(4),part(b),subpart(ii),[117,1,"It protects them by making it illiegal to kill or hurt the animal."]).
answer(number(4),part(b),subpart(ii),[118,0,"Making an animal 'a protected species' helps it to survive because it would be protected by its predators and other things - environment, to help it survive."]).
answer(number(4),part(b),subpart(ii),[119,1,"If an animal is made 'a protected species', then people would be more aware of it, and they would make sure as many of this species would survive and reproduce as possible."]).
answer(number(4),part(b),subpart(ii),[120,2,"By making an animal 'a protected species' scientists and people around the world become aware that it is in danger of extinction. Schemes are set up by wildlife organisations to monitor the situation and they set up breeding programs or protect the animals' habitat."]).
answer(number(4),part(b),subpart(ii),[121,1,"By making an animal 'a protected species' people are prevented from hunting or culling that animal. No action can take place whereby the numbers of the animal are decreased so it is allowed to thrive and regain its numbers."]).
answer(number(4),part(b),subpart(ii),[122,0,"Makes them seperate from any preditors which they might have. Protected species have all their needs e.g - warmth, food, water etc."]).
answer(number(4),part(b),subpart(ii),[123,1,"It makes it a illegal for man to kill it. It provides more protection for the species in a better habitat. The species is watched and looked after by people in control of protecting species."]).
answer(number(4),part(b),subpart(ii),[124,2,"Because it makes people more aware so they try to avoid things like building roads and cutting trees down."]).
answer(number(4),part(b),subpart(ii),[125,1,"This helps the animal because it becoms illegal to kill them. They can therefor reproduce more readily and it's numbers don't reduce unless its through Natural causes."]).
answer(number(4),part(b),subpart(ii),[126,1,"Man would stop taking actions that might decrease their numbers any further. They would probably leave their mounbtains alone and build factories elsewhere."]).
answer(number(4),part(b),subpart(ii),[127,2,"If the animal is protect no men can hunt it or destroy it's habitats"]).
answer(number(4),part(b),subpart(ii),[128,2,"by making a type of animal 'a protected species' it allowes laws to be placed on the killing of it and concervation of it's habitat."]).
answer(number(4),part(b),subpart(ii),[129,1,"No man will hunt them and instead help to to survive so that the species will survive for longer."]).
answer(number(4),part(b),subpart(ii),[130,0,"by making it a protected species it can reproduced so there are lots More of the Animal."]).
answer(number(4),part(b),subpart(ii),[131,2,"If an animal is a protected species it means people can't poach it for its meat or fur. It also means that people will try to help it survive by giving it vaccines against diseases or taking it into captivity to breed. People will look out for protected species and be more kind towards them."]).
answer(number(4),part(b),subpart(ii),[132,2,"people are not alowed to hunt protected species. Protections may also be put on their habitat so they have places to live. undisturbed."]).
answer(number(4),part(b),subpart(ii),[133,0,"Because when there are more number of them the people will afraid of them and they can protect themselves to reproduce more of them."]).
answer(number(4),part(b),subpart(ii),[134,2,"This helps by letting people know that the species has nearly died out. There will be fines for hunters caught killing this animal."]).
answer(number(4),part(b),subpart(ii),[135,2,"By making a type of animal 'a protected species', you are helping it to survive by placing bans and laws against certain actions, such as hunting, for it. It also makes people more aware and perhaps willing to help to increase it's numbers."]).
answer(number(4),part(b),subpart(ii),[136,1,"It is looked after by wild life people and no one is allowed to kill it."]).
answer(number(4),part(b),subpart(ii),[137,0,"This helps as they can be kept in a safer enviroment away from harm of natural and man made disasters."]).
answer(number(4),part(b),subpart(ii),[138,2,"To make an animal 'a protected species' means to make if officially illegal for that animal to be hunted. It also means that increased attention will probably be paid to maintaining its habitat."]).
answer(number(4),part(b),subpart(ii),[139,1,"The type of animal is kept in the right environmental conditions, for example their is enough food and shelter for them. They are also bred carefully in the correct conditions"]).
answer(number(4),part(b),subpart(ii),[140,0,"because it is protected"]).
answer(number(4),part(b),subpart(ii),[141,2,"If an animal is a protected species it makes it illegal to hunt it, thus helping the species survive. Often protected species are kept in captivity, protecting them from predators and providing food to survive . Breeding is also encouraged here, helping the survival of the species.."]).
answer(number(4),part(b),subpart(ii),[142,2,"When a species becomes a protected species it becomes illegal to kill this animal and its habitat is usually protected. This means its population is under less threat and may prosper."]).
answer(number(4),part(b),subpart(ii),[143,2,"People will take more notice of protected species. People will be aware that it is illegal to harm the animal and will realise it is close to extinction."]).
answer(number(4),part(b),subpart(ii),[144,0,"It makes some people know the boundarys and where they can and cant do distressing things"]).
answer(number(4),part(b),subpart(ii),[145,2,"People will not be able to kill them as there are not many. People will be more aware and their land can be protected."]).
answer(number(4),part(b),subpart(ii),[146,1,"it means that you can't hunt the animal and are usually kept in pairs of male & female so they Reproduce"]).
answer(number(4),part(b),subpart(ii),[147,2,"This would stop humans from damaging its natural habitat through deforestation and for crop land. Also, this makes it a criminal offence to be found hunting a 'protected species'.: this allows the indangered species to thrive again & breed."]).
answer(number(4),part(b),subpart(ii),[148,2,"If a type of animal is declared a protected species then it is illegal for them to be hunted or killed. It will also mean that some will be taken into captivity to be bred to try and increase the numbers."]).
answer(number(4),part(b),subpart(ii),[149,2,"A 'protected species' means that everything is ensured so that it may survive. Their habitat is protected and it is made illegal to hunt them down, so that it is more likely that it will reproduce easier and faster and in peace."]).
answer(number(4),part(b),subpart(ii),[150,2,"By making an animal 'a protected species', conservationists can ensure that its habitat is left undisturbed, furthering its chances of survival, and that the hunting of it is illegal. It may also make it possible to create a breeding programme for it or protect it from natural predators in order to increase numbers."]).
answer(number(4),part(b),subpart(ii),[151,1,"This helps a species to survive by making people more aware of the danger of the animal's exinction, and thus encourages those to be more careful in its habitat for example."]).
answer(number(4),part(b),subpart(ii),[152,2,"If a protected animal is made a 'protected species' this means that people are forbidden to harm its natural habitat or jepordise the factors which it needs to survive. It also means the animal is unable to be poached or killed in any way for human benefit."]).
answer(number(4),part(b),subpart(ii),[153,2,"Making an animal a protected species helps it to survive as it brings attention to it. Also it stops people from hunting them as penaltys can be large."]).
answer(number(4),part(b),subpart(ii),[154,2,"By making an animal a 'protected species' means that animal welfare groups could monitor the animal breeding activites to make sure theyre breed or making it illigal to hunt or kill these animals."]).
answer(number(4),part(b),subpart(ii),[155,0,"This means that the type of animal would be treated with great care and would be kept in a safe enviroment."]).
answer(number(4),part(b),subpart(ii),[156,2,"Making an animal a protected species, helps it to survive as it is not allowed to be hunted, also Man has to respect its enviroment and not disturb or destroy it, unnecessarily."]).
answer(number(4),part(b),subpart(ii),[157,0,"by putting them in a special habital so man cannot get to them"]).
answer(number(4),part(b),subpart(ii),[158,1,"everyone is aware of this, and if people want to hunt them down, they either are at a huge risk of getting fined, or dont hunt them at all."]).
answer(number(4),part(b),subpart(ii),[159,2,"When an animal is declared a protected species, nobody can directly try to harm the animal and is protected from its habitat being destroyed."]).
answer(number(4),part(b),subpart(ii),[160,1,"A protected species will have a better survival chance because human activity against it would be restricted. e.g. poaching. Thus allowing the animal not to have human interaction to interupt its natural habitat or behavior."]).
answer(number(4),part(b),subpart(ii),[161,0,"By making a type of animal 'a protected species', scientists will try to do everything they can in order to look after the species and prevent them from damage, for example by removing any harmful litter from the area, etc."]).
answer(number(4),part(b),subpart(ii),[162,2,"It makes it illegal to kill the animal to enforce it's survival + also highlights the plight to potential buyers of the fur + meat who would then choose not to buy it + poachers would stop as there wouldnt be a market for it."]).
answer(number(4),part(b),subpart(ii),[163,0,"It just Protces it from man it Doesn't help it survive By natural Diasters"]).
answer(number(4),part(b),subpart(ii),[164,1,"That way people might stop hunting it and then there will also be more people looking out for the animal trying the protect it."]).
answer(number(4),part(b),subpart(ii),[165,2,"Making a type of animal 'a protected species' helps it to survive because people are then not allowed to kill the animal or destroy it's original habitat."]).
answer(number(4),part(b),subpart(ii),[166,2,"When an animal is a 'protected species' it means humans are not allowed to do any harm to it, it is protected by the law. Instead people must make an effort to conserve it and not interfere with its habitat or lifestyle. It also means it will be carefully monitered and every effort made to help it to survive."]).
answer(number(4),part(b),subpart(ii),[167,2,"A protected species is not allowed to be harmed by humans: laws are passed to prevent shooting. There is also a raised awareness about the animal and its problems, which can encourage members of the public to help in its conservation"]).
answer(number(4),part(b),subpart(ii),[168,2,"Making a type of animal 'a protected species' gives it certain rights. They are not allowed to be killed for meat by poachers and their natural habitat (the environment it lives in) has to be maintained and not directly threatened by humans."]).
answer(number(4),part(b),subpart(ii),[169,1,"These animals can be protected from preditors, breed to increase numbers and given the right food it needs to eat."]).
answer(number(4),part(b),subpart(ii),[170,2,"There are laws against hunting it and do things like building where it lives."]).
answer(number(4),part(b),subpart(ii),[171,0,"There are conservation groups that check on how the specie is surviving. They record results and help the protected species."]).
answer(number(4),part(b),subpart(ii),[172,0,"because there are less of them they no how to hunt for themselves & they don't get killed because not many people know what they are"]).
answer(number(4),part(b),subpart(ii),[173,2,"When a type of animal is made 'a protected species' there are several benefits. Firstly, man's awareness of its plight is increased and so zoos may start to run captive breeding programmes to help. Also, it means that humans are not allowed to hunt it or kill it or destroy its habitat. Finally, numbers of the species or monitored."]).
answer(number(4),part(b),subpart(ii),[174,2,"If an animal is protected, it cannot be hunted thus this will not reduce numbers. It also makes people realise that it is necessary, to help this animal, so raises awareness. If animals are protected the area they live in may be conserved or various schemes to help it survive or increase numbers may be implemented. All this increases the size of the population"]).
answer(number(4),part(b),subpart(ii),[175,2,"There are laws to stop actions such as hunting. Also people will try and breed the species and let them back into the wild."]).
answer(number(4),part(b),subpart(ii),[176,2,"Animals which are named 'protected species' are normally in danger of extinction. By giving them this label, the public may become aware of the situation. As a result the animal is more likely to survive as it may be hunted less, or caution may be taken by the public, while in its presence."]).
answer(number(4),part(b),subpart(ii),[177,1,"It lays down rules on how it can be treated and makes it obvious that killing or harming this animal is NOT protecting it. It should be seen as to be protected."]).
answer(number(4),part(b),subpart(ii),[178,2,"It makes people more wary of it and therefore more careful. They are less likely to do neglegent things that could endanger it. Also it makes them illegal to hunt."]).
answer(number(4),part(b),subpart(ii),[179,0,"If protected then that means that nothing is allowed to harm it unless it's natural e.g. disease. It helps it to survive as it means there is no outside interference with the animals way of life."]).
answer(number(4),part(b),subpart(ii),[180,0,"Making itself feel safe and knowing what they are doing to make itself feel at home."]).
answer(number(4),part(b),subpart(ii),[181,0,"Making a type of animal a protected species helps it survive because protected spiecies are usually low in numbers so making them protected gives them a chance to reproduce and increase the spiecies population"]).
answer(number(4),part(b),subpart(ii),[182,0,"because they have extra special attetion and food given to them. People go out of there way to make sure stay strong and healthy."]).
answer(number(4),part(b),subpart(ii),[183,0,"If a certain human goes out to hunt for a animal and he or she finds out its a 'protected species' It means it protects itself or others, so its not worth hunting for."]).
answer(number(4),part(b),subpart(ii),[184,0,"If the animal is small in numbers a decision is made to protect them so that they can breed to regain the population."]).
answer(number(4),part(b),subpart(ii),[185,1,"If an animal is made a protected species it lowerrs the risk of it being hunted."]).
answer(number(4),part(b),subpart(ii),[186,0,"Because if the animal is a protect species there are not many of the animal so there is less competition for food"]).
answer(number(4),part(b),subpart(ii),[187,0,"Because the animal get's better looked after and seen to other that if they just left it on it's own."]).
answer(number(4),part(b),subpart(ii),[188,0,"because conversatists will ensure that all possible dangers that could affect the bucardo's like pollution and leaving sharp objects behind."]).
answer(number(4),part(b),subpart(ii),[189,1,"making a type of animal a protected species helps it to survive by excluding it from any dangerous occurances that could lead to their death. They are protected by man to continue to breed them"]).
answer(number(4),part(b),subpart(ii),[190,0,"because of the low numbers of the species it had been declared as protected"]).
answer(number(4),part(b),subpart(ii),[191,1,"If an animal is 'a protected species' this usually signifies that it is a rare type of animal therefore humans ensure that there is the correct and sufficient amount of food that the specie requires as well as suitable living standerds. The 'protected species' are notified as rare and for the reason that they are decreasing they are looked after with care and monitered constantly."]).
answer(number(4),part(b),subpart(ii),[192,0,"As it is taken better care of, therefore will live longer if it gets the water and nutrients and food it needs. Also if it is living in its comfortable habitat."]).
answer(number(4),part(b),subpart(ii),[193,0,"By making an animal 'a protected species' the population is helped to survive. When an animal is 'a protected species' they are protected from dangerous things due to there lack of numbers."]).
answer(number(4),part(b),subpart(ii),[194,0,"By making a type of animal 'a protected species' it means to look out for their best intrests and help and give them what they need."]).
answer(number(4),part(b),subpart(ii),[195,0,"This means that it is close to extinction and so will be carefully watched to make sure that there are no predators around and that there is enough food available. Humans will make sure that there is little competition"]).
answer(number(4),part(b),subpart(ii),[196,0,"By telling people a animal is a Protected species they will become more gentle with the animal"]).
answer(number(4),part(b),subpart(ii),[197,0,"Nothing would be able to kill it as it would be protected."]).
answer(number(4),part(b),subpart(ii),[198,0,"If it is protected, then the species can face no ultimate danger that may harm it. For example making sure the species has a sufficient amount of food to help it to survive."]).
answer(number(4),part(b),subpart(ii),[199,1,"It encourages people to prevent actions which may cause it to become extinc e.g. hunting"]).
answer(number(4),part(b),subpart(ii),[200,1,"Making an animal a 'protected species' will it back off the brink of extinction. It also means you can't hurt the species."]).

 
