:- multifile answer/4.

answer(number(4),part(d),subpart(0),[1,2,"Producing human cell clones will be useful for people with incurrable diseases such as cancer, which can only be cured by receiving a healthy organ through transplant. If cloning became possible (legal) then healthy organs (tissue) will always be available for transplant. Some people object to cloning because they are afraid that it will escalate to the stage where complete human clones are created, and then individuality (as well as unique human rights) will be lost."]).
answer(number(4),part(d),subpart(0),[2,1,"cloneing human cells mean terminal illnesses can be cured. people disagree with this because they belive its playing God with some one life."]).
answer(number(4),part(d),subpart(0),[3,2,"It is possible to produce clones of human body cells and it could be very useful as we could make exact coppies of our blood incase a blood transfusion was needed and also sperm and egg cells so a new life could be genetically created. Sum people object to this as they feel it is unnatural and inhumane."]).
answer(number(4),part(d),subpart(0),[4,2,"It might be useful beacause we can replace or damage cell with good ones that work then most deasises could get wiped out. Might be a problem because problems which could cause ethical problems because in the process alot of embroys are destroyed"]).
answer(number(4),part(d),subpart(0),[5,1,"This mAy be useful to cure genetic diseAses or diseAses which cAn be cured by replAcing the infected cells. Some people mAy object to this As they Are religious And believe thAt god should be the only one to creAte life."]).
answer(number(4),part(d),subpart(0),[6,3,"Cloning human body cells would be very useful for organ transplants. A donor would not be required, and as the organ would be made from the cells of the recipient, there would be almost no risk of rejection. However, some people object to this, as there are many moral issues involved. Some may argue that it is wrong for scientists to 'play God'. Others may be worried that this could allow the creation of things such as 'designer' babies, or replacements for dead children, as these could appear to decrease the value of human life."]).
answer(number(4),part(d),subpart(0),[7,1,"It may be useful because maybe it saves a life by bringing in another etc. Some people object to this because they believe that making another human by hand is not right, that is like saying they are good, they are messing with nature. And it is only god who can bring or take lifes, that is why many people object to cloning."]).
answer(number(4),part(d),subpart(0),[8,1,"This may be useful because if people have genetically sound body cells, clones can be produced to prevent other humans from suffering genetic disorders and the embryo can be inserted into the mother. Some people object to this process because they believe it is playing god and messing with nature."]).
answer(number(4),part(d),subpart(0),[9,1,"This may be useful as it means that healthy offspring with desirable characteristics can be produced. many people object due to ethical reasons and it also can be very dangerous if it reaches the wrong hands."]).
answer(number(4),part(d),subpart(0),[10,2,"This may be useful if someone needs a transplant but has no matching doner. Disadvantage being if it causes \'the clone\' to die. People also think it is wrong to \'Play God\' (so to speak)"]).
answer(number(4),part(d),subpart(0),[11,1,"This could be useful because it is a new technology and people may want clones of themselves, people may also object because it is not natural and highly dangerous."]).
answer(number(4),part(d),subpart(0),[12,0,"It may be usefull because if someone was born without a usefull cell then they could clone it and use it to save their life"]).
answer(number(4),part(d),subpart(0),[13,1,"It may be useful because people who are ill and need cells to be replaced can have the correct cells cloned and inserted so they become well. Some people object because they think it would be used to create doubles of everyone which is not what nature intented."]).
answer(number(4),part(d),subpart(0),[14,2,"Making clones is useful as it can help fight diseases, act as an organ donor by having a replicate of a particular organ. Furthermore people could clone a person who is going to die or is dead. People may object to this process as they do not believe it is natural way for humans to be born."]).
answer(number(4),part(d),subpart(0),[15,0,"This would be able to makes exact copy\'s of humans who may have diesese but without the diseases. People object to the process because it is against human rights for people to choose who lives and who dies."]).
answer(number(4),part(d),subpart(0),[16,1,"Because if humans ever become extinced they can clone the last few and make more. People protest this because they dont think it is right to clone people so they object."]).
answer(number(4),part(d),subpart(0),[17,0,"so you can live forever but some people thinks its wrong."]).
answer(number(4),part(d),subpart(0),[18,2,"This may be useful to doctors because if there is a patient with a kidney failure it would be possible to clone the working kidney and replace the damaged kidney. Organs would be easily replaced. Some people would object because they feel that it is tampering with nature and is not God\'s doing. They also feel that people might get carried away and start cloning people."]).
answer(number(4),part(d),subpart(0),[19,3,"Clones could be made of organisms which would greatly facilitate organ transplants since there would be no danger of the body rejecting the organ. However, some people object because they feel it is morally wrong to create something just for organs. Some people feel that nature should not be interfered with too much."]).
answer(number(4),part(d),subpart(0),[20,3,"It is possible to build a new organ for someone whose original one is defective or absent from their own tissue so it will not be rejected. It is also possible to clone entire humans for an infertile couple or other person or persons wishing but unable to have children. However this means the child will be a replica of its parent which may offend its individuality."]).
answer(number(4),part(d),subpart(0),[21,0,"It could be useful to help people over come diseases where the cells are lost. People object to it because people don\'t want baby\'s being produced in this way where you can chose what it looks like."]).
answer(number(4),part(d),subpart(0),[22,0,"human body cell clones are useful for seriously ill people who need them to survive. But, some people disagree with it because there is only supposed to be one of everyone"]).
answer(number(4),part(d),subpart(0),[23,1,"often religious people object as they see cloning as \'Playing God.\' Also cloning can have serious side affects possibly causing cancer. However it is useful as it ensures identical organisms. For example cloning of a plant which is healthy and useful ensures the daugthter plants are identical."]).
answer(number(4),part(d),subpart(0),[24,0,"It is useful so it can make people remember the bucardo but some people may object to this because they might want to remember it for what it was."]).
answer(number(4),part(d),subpart(0),[25,2,"It may be useful because it would help people with such diseases as bone maro to find a donor. But some people may object because they might start producing actual clones. of people."]).
answer(number(4),part(d),subpart(0),[26,1,"It is useful to clone humans because it means they can enhance the human body to make it susceptable to certain diseases and will increases peoples chances of survival. Other people will object to this because they believe that nature should run it\'s corse and not be altered or interfered with by creating clones."]).
answer(number(4),part(d),subpart(0),[27,2,"If a family member needs a transplant but cannot find a suitable match then a healthy clone can be born. Then the specific organ can be taken from the clone, which although saves the original person, effectively kills or causes risk to the cloned human\'s life, which can be seen as inhumane."]).
answer(number(4),part(d),subpart(0),[28,2,"Producing clones of body cells, such as liver or kidney cells could provide healthy copies of damaged organs, creating a cure for many diseases. Some people object to this as unethical as it seems to be \'playing God\'."]).
answer(number(4),part(d),subpart(0),[29,2,"Clones of human body cells could be useful because then people could have only good and desirable traits such as intelligence and beauty. Some people object to this process because if everybody used cloned human body cells, there would be very little genetic variation in the human race, some people also argue that it is a bad thing because it is not natural, and therefore not a moral thing to do. - it is not meant to happen."]).
answer(number(4),part(d),subpart(0),[30,2,"This is useful because it can prevent mutation and allow people to be produced with certain desirable qualities such as intelligence, sportiness etc. However, it is questionable whether it is morally right to do such a thing as it means loss of identity for clones and those they have been cloned from. and there is also the danger that they will not live very long, as it is suspected clones do not which makes it all the more wrong to \'\'create\'\' a person unlikely to survive and without a true identity."]).
answer(number(4),part(d),subpart(0),[31,2,"It could be useful as it could lead us one day being able to grow organs for transplants. But people object as it is not natural and could lead to some kind of \'super\' human."]).
answer(number(4),part(d),subpart(0),[32,0,"Producing human clones can give people the choice to have children. People object to this because it can be damaging for people involved."]).
answer(number(4),part(d),subpart(0),[33,1,"If cloning were used alongside artificial selection and genetic engineering it might be possible to create a better adapted society. Cloning and genetic engineering could have unforseen repurcussions on ecosystems. It could also take away the variational qualities, which make us human"]).
answer(number(4),part(d),subpart(0),[34,1,"It is useful if we wanted to create talented people or tall people etc. People may object, because they feel that it is unnatural and wrong."]).
answer(number(4),part(d),subpart(0),[35,1,"i could be usefull to people who are born handicaped you can make a clone for them.- but people who dont agree one can stop it happening due to being a different religion"]).
answer(number(4),part(d),subpart(0),[36,3,"This may be useful because it would mean that vital organs could be produced, for transplants and there would not be any chance of rejection. Some people object to cloning, because they feel it is wrong to interfere with nature, on such a scale."]).
answer(number(4),part(d),subpart(0),[37,3,"This can be very useful because people may have certain organ diseases, whereby they need a new organ it can be hard to find a doner, however if they use cloning, then a healthy organ could be created. However this may have to be created through a human and it is thought to be ethically wrong to clone."]).
answer(number(4),part(d),subpart(0),[38,1,"Cloning is a useful way of replicating organisms, it could be used to test possible cures for serious illnesses. Some people may object as they feel it would be \'\'ethically immoral\'\'"]).
answer(number(4),part(d),subpart(0),[39,3,"Clones may be used to provide organs for people who need organ transplants, if there are none available. They could also be uded for testing out medecines that would be used for the benefit of mankind. However, there is an ethical issue in that people consider this \'playing god\', and think that creating a human merely to destroy it for its organs is wrong."]).
answer(number(4),part(d),subpart(0),[40,1,"They would want to produce clones of human body cells, if that inparticular human cell has characteristis that can fight disease, this will be objected to because of some religious reasons and also because the process can be very expensive and difficult to carry out."]).
answer(number(4),part(d),subpart(0),[41,2,"Yes is is possible to produce clones of human body cells. It may be useful as it could cure, and illiminate many genetic diseases, i.e cystic fibrosis. However some people object as they feel it is like playing gd."]).
answer(number(4),part(d),subpart(0),[42,1,"This could be useful because it would help people who have incurable deseases such as cystic fybrosis. But some people object because they believe that this would lead to humans putting a price on human lifes."]).
answer(number(4),part(d),subpart(0),[43,1,"It is possible this could be useful to re live people when they have died. People could object becuas they say if you die it was ment to be and that science and experimenting is wrong."]).
answer(number(4),part(d),subpart(0),[44,2,"This may be useful to produce offspring free of disease but some people may object to it because it can be seen as unethecial as it is interfering with natural reproduction. It can reduce the gene pool if performed on a wide scale which means as well as a lack of diversity a specific disease could affect more people due to genetic identicality than had cloning not have been performed. Also, things in the cloning process may go wrong and the human baby may be deformed in some way, whch is unfair on the baby who has to live like this."]).
answer(number(4),part(d),subpart(0),[45,2,"Human cloning would be able to help a person who has a disease, by romoving the effected tissiue and replaceing it with the fresh clean one from the clone, But then the clone would be killed, and that what people object to."]).
answer(number(4),part(d),subpart(0),[46,1,"Some people think that they can make their baby have no diseases but others think that this will lead to \'designer babies\', which isn\'t what human life is about and is not what God wanted."]).
answer(number(4),part(d),subpart(0),[47,2,"This may be useful in procedures such as skin grafts, where new skin can be produced instead of taken from elsewhere. Some people object to this in case there is a defect or fault in the process, which could be harmful."]).
answer(number(4),part(d),subpart(0),[48,1,"yes it is possible, it could be useful because you could create an ideal and perfect person but it would be playing god that is why a vast number of people object to this solution"]).
answer(number(4),part(d),subpart(0),[49,1,"It may be useful because it would be like having a younger version of you but some people may object because there isn\'t any need for two of the same person."]).
answer(number(4),part(d),subpart(0),[50,0,"It is possible to clone human body cells. It has been used to try and investigate how patients might benefift from diseases. some people object because they belive it is wrong to reproduce humans so that they can be subjected to tests and experiments to see how the medicin, that is being tested for public use, might benefit or be a disadvantage to those who have diseases."]).
answer(number(4),part(d),subpart(0),[51,2,"Some people object to cloning as they think that scientists are trying to play the part of God. It also may be useful as people who cannot have babies can use cloning to produce children. The cost of cloning would be high so that is why some people might object to it."]).
answer(number(4),part(d),subpart(0),[52,0,"Producing clones of human body cells can be beneficial for example cloning human insulin cells for diabetes sufferers. Some people object to it because so little is known about the process. Also when trying to put new DNA into a new nucleus, it is very difficult to get it in the right place."]).
answer(number(4),part(d),subpart(0),[53,2,"It would be useful to cure diseases and replace broken or damaged cells. Some people object to this process as it is seen as unnatural and there isn\'t strong evidence that it will work"]).
answer(number(4),part(d),subpart(0),[54,2,"Yes it is possible and this will be good people how need eg bone marow transplants. Some people object to this as its like \'playing god\' creatting humans for specific requirments."]).
answer(number(4),part(d),subpart(0),[55,1,"If the population of the world decreases clones can be produced to help the human spieces survive. It is objected by people as it is not a natural life. And at the moment if a human clone was produced it would spend it\'s whole life in R & D."]).
answer(number(4),part(d),subpart(0),[56,1,"This may be useful if a couple would want their child to have Psfic features such as blue eyes or blonde hair, however some People tend to disagree. And argue that this Process involves risk and it is morally innapropriate to be so concerned with the way your child will physically look."]).
answer(number(4),part(d),subpart(0),[57,1,"it may be useful because you could tell what your baby could be before it is born. people object to as its not natural to look into the future of what your baby should look like they think its not right."]).
answer(number(4),part(d),subpart(0),[58,1,"Some people object because of ethical reasons, or they might think it is unsafe, it can never be 100% safe. It maybe useful as you could get rid of a disease the baby might have."]).
answer(number(4),part(d),subpart(0),[59,1,"This could be useful for cloning scientists or geniuses who would carry on their work as a clone. People object, however, due to its moral issues. It is also known that clones do not live very long and people have not thought about feelings of the clone"]).
answer(number(4),part(d),subpart(0),[60,0,"This may be useful if we start to become extinct but people object because of the experiments on humans and the fact it will not know how the live a normal life."]).
answer(number(4),part(d),subpart(0),[61,0,"You could grow body parts for people who needed it. People would object to it because they would think it\'s sick and its from some one elses cells."]).
answer(number(4),part(d),subpart(0),[62,2,"This may be useful for transplant operations where the organs are not available. This would be useful as many people on waiting lists for organs would be treated more quickly and would have a better chance of staying alive. People object to this as they think that cloning is like \'playing God\' and that doctors should not have this power."]).
answer(number(4),part(d),subpart(0),[63,2,"It may be useful as clones can be made of important substances eg, Insulin for diabetics, or the blood clotting gene for haemophiliacs. However some might think it is ethical wrong because mutations might occur and it is also copying the genetics of another human making them identical cells."]).
answer(number(4),part(d),subpart(0),[64,2,"By being able to clone parts of the human body will mean that in the future people will be able to cure diseases in the body, people who have lost parts of their body could have them replaced and transplants won\'t be as difficult to have due to matches. However, the ethics of cloning mean that people fear the idea of clones. They are scared we will become a society of clones."]).
answer(number(4),part(d),subpart(0),[65,0,"If a couple have a high chance of passing on an inherited disease to their child then it can be used to find a cell that does not have the genes + then copy this to produce a healthy child."]).
answer(number(4),part(d),subpart(0),[66,1,"Some people might object because they see them as an unatural living species and they do not want the population taken over by clones."]).
answer(number(4),part(d),subpart(0),[67,1,"It is useful because you can have a person who is the same who has the persons genetic strengths. People are against cloning because deseases could spread easerly if there were many people who were clone"]).
answer(number(4),part(d),subpart(0),[68,0,"This could be useful because we could make a clone of the cleverist person or tallest person to use them for something useful. People object to this because the is a big chance something will go wrong and they could probaly die from something."]).
answer(number(4),part(d),subpart(0),[69,1,"By detecting a gene that is particularily useful to humans, such as a gene resistant to a particular disease, we can produce clones which show this particular trait. This is a quick way of producing many clones resistant to disease andmore able to survive yet these genes may have an unknown effect and defects in the genes would also be passed on and passed on to many offspring, not just the (if many clones are produced). Finally people question the status of a human clone in a normal environment and whether playing god is the right thing to do"]).
answer(number(4),part(d),subpart(0),[70,1,"This may be useful, because if a couple wanted a baby to look a certain way they could pay for it to be done. Some people object to it, because they think that you should let nature take its course."]).
answer(number(4),part(d),subpart(0),[71,2,"This may be useful for reconstructive surgery such as skin grafts or replacement of an organ lost in a accident. This would mean that there wouldn\'t be a shortage as there is now, with donor organs. Some people object, as they feel that if cloning is used for small things, people may then want to clone a human being and a danger arises of \' identical races / humans.\'"]).
answer(number(4),part(d),subpart(0),[72,1,"Yes, it is possible to produce clones of human body cells. It would be very useful to do this to prevent desease in an embrio or produce selectively breed animals. Some people object to this because it can cause mutations and can be seen as morally wrong."]).
answer(number(4),part(d),subpart(0),[73,2,"This is useful for situations such as heart transplants as spare hearts are not always available, to be able to culture a healthy one would be useful. However, it is not natural to clone something so some people object especially when attemps are made to clone a whole human as there are many moral issues."]).
answer(number(4),part(d),subpart(0),[74,1,"It can be useful to re-grow human body parts, eg breasts after breast cancer but people are worried it may get out of control, as all you need from a person is one cell. It would be difficult to moderate, people could be cloned without their consent. It would change life as we know it and is an unnatural process if it is done by scientist."]).
answer(number(4),part(d),subpart(0),[75,2,"It may be useful to clone skin cells because you could grow a lot at a fast rate and then it could be used on a skin graft. Some people object because it isn\'t a natural life process to do."]).
answer(number(4),part(d),subpart(0),[76,2,"It is possible to copy human cells, as proved with the mass production of insulin formed from cuttings of human DNA. Although many oppose this as it seems an intrusion on G-d\'s work. They do not believe it is ethical to \'produce\' life in this way."]).
answer(number(4),part(d),subpart(0),[77,1,"Cloning is useful as we are able to obtain the most desired characteristics and reproduce them and then find new cures for diseases. Some people consider this unethical and \'playing God\'. It is also useful because we are able to determine society and prevent outbreaks of illness."]).
answer(number(4),part(d),subpart(0),[78,1,"Clones of human body cells may be useful because diseases could be fought. Some people object to the cloning process because it is seen as unnatural and wrong. They also believe that things could get out of hand if scientists start to produce clones of living people without permission or thinking of the consequences."]).
answer(number(4),part(d),subpart(0),[79,3,"This way be useful as the cells of organs which have failed in patients can be cloned, enabling a new organ to grow in the damaged organs place., thus improving the health of the patient. The organ is also not rejected by the patient\'s body, as some donor organs are. Some people object to this process as it involves embryonic stem-cells which are cloned from the individual. The use of embryos ie. a new life is seen as immoral. Some people also object as they do not believe that humans should interfere with nature an \'play God\'."]).
answer(number(4),part(d),subpart(0),[80,0,"Yes, it is possible to produce clones of human body cells. This is useful if you want to produce an army to go to war, but some people object to this process because they think it isn\'t right to make a clone, you should just leave people alone."]).
answer(number(4),part(d),subpart(0),[81,0,"This could mean that people could have an exact double that would live on even if they died also if a human has died, you may be able to recarnate them. Some people object because it is not alway quaranteed to work."]).
answer(number(4),part(d),subpart(0),[82,1,"it may be useful because it could result in cureing a disease, people may object because it isn\'t nataral and things could go wrong."]).
answer(number(4),part(d),subpart(0),[83,1,"It is useful because it would make it possible for infertile people to have children. Some people object because tampering with human body cells is dangerous and the clone can have many problems due to side effects."]).
answer(number(4),part(d),subpart(0),[84,1,"It would be useful as it would be a breakthrough in science, but it would be going against the cause of nature so some people would object to this. But it would help scientists to find out more about cloning, its effects and problems."]).
answer(number(4),part(d),subpart(0),[85,3,"It is useful in order to make hormones, such as insulin, that could be injected into someone who does not produce enough. It can also help infertile couples produce offspring. Some people object to this process as they believe it is unnatural and only G\'d can decide whether or not couples should be fertile or a person should produce a certain hormone."]).
answer(number(4),part(d),subpart(0),[86,3,"Producing clones of humans may be useful for making donor organs and real limbs when they are needed because they are living and the genetic information could then come from the patient, these extra organs would not be rejected by their body, as the rejection of organs is such an important issue in helping patients needing heart and kidney transplants, etc. Some people object to this process because they object on a moral level, where life should not be produced but created."]).
answer(number(4),part(d),subpart(0),[87,2,"Human clones could benefit some people who want identical children, or say a fashion company that wants to clone a model who they believe is \'perfect\' for their needs. However, many believe it is not ethical to clone humans as it is messing with nature and leaves no scope for variation, and so it is now illegal to clone humans."]).
answer(number(4),part(d),subpart(0),[88,1,"Some people believe that cloning is incorrect because we should not be interfering with its nature and we should not try to mimic the reproduction cycle. It may also be useful because we will be able to find out cures for medicinal uses."]).
answer(number(4),part(d),subpart(0),[89,3,"This may be particurlarly useful for people suffering from paralysis, who may need a stem cell which has been cloned or for people who need organ transplants some people object to this because they feel it is morally wrong and it could lead to other things, such as cloning of a whole body. Some may also be worried by the idea of the creation of a genetic hierachy, where people who are not perfect are shunned from society."]).
answer(number(4),part(d),subpart(0),[90,1,"It is useful so if some one has an accident they could use the system to save that persons life, many people object to this as it is not natural and are going to far beond the way of life."]).
answer(number(4),part(d),subpart(0),[91,2,"Cloning of human body cells could help to fight disease by finding new cures. Some people object because it is unnatural to produce clones."]).
answer(number(4),part(d),subpart(0),[92,2,"it would be usefull becouse if we could clone harts and other organs less people would die of heart desise and the waiting list for new harts would be cut dramatically.there are however people (mostly religeouse) who believe it is wrong for people to tamper with nature and \'\'gods creations\'\'"]).
answer(number(4),part(d),subpart(0),[93,1,"This may be useful to a person who needs a transplant of some sort and needs a match in blood. They can use the clone for that. People object to this because it takes their freewill. They don\'t want another one of them walking the streets."]).
answer(number(4),part(d),subpart(0),[94,0,"it could be usefull because it could be used to cure disease some people think that the origional cells may reject the new clones however."]).
answer(number(4),part(d),subpart(0),[95,2,"Cloning body cells would be very useful if they could be used to clone body parts and organs, so that transplants would be a lot easier. People object to the process of cloning because it is utterly untraditional, and is unnatural. Religious people would especially object, as they would see it as going against one of God\'s processes - birth."]).
answer(number(4),part(d),subpart(0),[96,0,"It maens that you could make exact replicas of children. but then every one won\'t be original"]).
answer(number(4),part(d),subpart(0),[97,0,-]).
answer(number(4),part(d),subpart(0),[98,2,"It would be useful because it would mean that if an organ transplant needed to happen, it would be able to without searching for a donor. People object to this as they see it as unnatural."]).
answer(number(4),part(d),subpart(0),[99,2,"Clones of humans could be very useful for medical purposes; exploring causes of particulary genetic disease and for experimenting with cures. Many people do have objections because the clones would in many cases be used solely as test objects and what right do we have to use other human beings for such a process. Furthermore it would take away human individuals if a copy could be made and it is against many relegious beliefs"]).
answer(number(4),part(d),subpart(0),[100,3,"It could be useful as a clone could be used for badly needed organ transplants, and for women who can\'t conceive their own child. It is opposed because it is said by religious people - against the act of god and mother nature."]).
answer(number(4),part(d),subpart(0),[101,2,"It would be useful to do this because we could make bone marrow or new organs to be implanted into ill people. People object to this because they fear that whole people would be cloned which would be unethical."]).
answer(number(4),part(d),subpart(0),[102,2,"Cloning a human body cell can be beneficial for some. A clone of oneself would be beneficial if a person had to have an organ transplant and needs a particular organ with tissue the same as theirs. Yet some may object as some regard the process as de-humanising and acting as though they are \'\'Playing God\'\'"]).
answer(number(4),part(d),subpart(0),[103,0,"It is possible because some scientists do clone humans cells. Some people object because it could be dangerous or risky."]).
answer(number(4),part(d),subpart(0),[104,1,"If someone has a good, strong part of the body, i.e a liver cell, then clones can be made to produce more of the ideal cell. These can then be placed in people who have that weak cell, to help their body function easily and better. Some people say it is not just, not right to have part of someone else in you. Some say it is morally wrong and goes against beliefs of being created and remaining as you are."]).
answer(number(4),part(d),subpart(0),[105,3,"Its useful for medical reasons, for example blood transfusions or transplants etc as the body wont reject it as its the same. People may object as they say that people shouldn\'t interfear with nature, they should let it run its course."]).
answer(number(4),part(d),subpart(0),[106,2,"It is useful because a cloned person could give organs for transplants for the original. Some people object because it is wrong to play god, and also if this technology fell into the wrong hands anything could happen."]).
answer(number(4),part(d),subpart(0),[107,2,"It may be useful, if someone was dying because of a faulty organ, a clone of a good organ would be made to replace bad one. People object because they think it\'s messing with god, denying what should happen, avoiding fate."]).
answer(number(4),part(d),subpart(0),[108,2,"This could be very useful for transplants and blood transfusions. However people object because they feal that you are creating something living only to destroy it."]).
answer(number(4),part(d),subpart(0),[109,0,"Means examining dead people. People would say it invaision on their body. It can be useful to find out new things about our bodies."]).
answer(number(4),part(d),subpart(0),[110,2,"It would be useful to produce clones of human body cells as they could be used in medicin as donar body parts are in constant demand and are very difficult to match correct blood types. Some people object to this as they feel it is cruel to create this person or cell for the sole purpose of donating organs or blood."]).
answer(number(4),part(d),subpart(0),[111,1,"This may be useful to fight diseases. Some people are against it because they believe it is un-Holy!"]).
answer(number(4),part(d),subpart(0),[112,1,"cloning human cells could be very useful, they could be used for transplants, but many people say it is unnatural and could be dangerous."]).
answer(number(4),part(d),subpart(0),[113,1,"Scientists could use cloning to produce organs in which they could use to save the dying by giving them organ transplants which gives them more chance of survival."]).
answer(number(4),part(d),subpart(0),[114,2,"Cloning can be useful, but is also controversial. By cloning human body cells, cures for many diseases could be discovered, and thus diseases that were previously fatal could be thwarted. Additionally, previously infertile couples could still produce a child of their own as both their body cells are replicated to make an embryo. However, many people believe that cloning is morally wrong as it is \'\'disrupting nature\'s course\'\'. They may also object for religious reasons."]).
answer(number(4),part(d),subpart(0),[115,0,"It could be useful as it may help people survive."]).
answer(number(4),part(d),subpart(0),[116,2,"It is possible to clone human body cells, and it may help to save lives as there will always be a matching donar, however people object as it is morally wrong as people think those who clone things are playing God."]).
answer(number(4),part(d),subpart(0),[117,3,"It may be useful to produce human clones if a couple cannot conceive and have children naturally. Also if a person experienced an accident and lots of tissues are destroyed. Cloning some body cells can substitute the damaged cells. However, some people object to the idea because clones are likely to have genetic problems and diseases which sexual reproduction can help to avoid (such as variations in offspring) and cloning of humans are going against nature (and some people believe - God)."]).
answer(number(4),part(d),subpart(0),[118,3,"This is useful because it can help save lifes, by genetic engerneering we can make organs but some people object because its not natural and can cause problems. Some people have religious beliefs."]).
answer(number(4),part(d),subpart(0),[119,0,"It could be useful because then we can discover more things about a clone, this could be useful in different reasons for example more research could be done. But other people would object this process because it could be dangerous, and people would make fun of this and think it is a joke."]).
answer(number(4),part(d),subpart(0),[120,0,"It would be helpful to quore cancer and other life Featiting illness people mite object because Its something completely different, and it many not work."]).
answer(number(4),part(d),subpart(0),[121,2,"Cloning cells means organs can be produced to help save lives. It means if someone needed a heart they would not have to wait long. However some people think this process is unnatural and interfers with life."]).
answer(number(4),part(d),subpart(0),[122,1,"use full cause can get a rare type of blood to a dieing person who has the rare blood type. people object cause some things may lead to, to much cloneing of one person body part"]).
answer(number(4),part(d),subpart(0),[123,1,"People object as they feel it is not for humans to tamper with, it is unatural. It may be useful to scientists to = help prevent diseases, inherited ones. This is a way of eradicating certain diseases."]).
answer(number(4),part(d),subpart(0),[124,2,"It is useful in that it gives us the ability to produce organs that can then be used in medicine to save people lives. There is, however, a great deal of controversy on this subject as many people feel it is unethical and wrong to clone humans as it could get out of hand and we would not know when to stop . Eventually it may emotionally harm the cloned humans."]).
answer(number(4),part(d),subpart(0),[125,2,"Cloning humans would allow the creation of organ donors whose tissue type matched perfectly with the person in need of a transplant. However, cloning humans causes many ethical dilemmas, such as what the rights of a clone should be and whether it might be used to create a new class of people, so some people object to the cloning."]).
answer(number(4),part(d),subpart(0),[126,1,"This is useful as it can be used for skin grafts when someone has had a disfiguring accident. Some people object to this process because it is \'unnatural\' and perceived as interfering with nature"]).
answer(number(4),part(d),subpart(0),[127,2,"If someone was not able to have a child, cloning could be useful as you could form a zygote from using the cells from a person. People may object though as this process is not natural and they may think it cruel."]).
answer(number(4),part(d),subpart(0),[128,1,"This may be useful if someone has cancer and needs some cells that are identical. It means that they can survive"]).
answer(number(4),part(d),subpart(0),[129,1,"this would help those who had lost a limb, or that had muscle detereation as the cells would be able to grow a new into the place of the lost or damaged tissue."]).
answer(number(4),part(d),subpart(0),[130,2,"Cloning human body cells can be used medically to regenerate a kidney, or grow a body part of someone\'s who was born without one, or is very ill. It will allow for the perfect replica, as opposed to a donor, which may cause complications. Some object to this process as it is playing with the hands of GOD, and some see it as immoral. It will allow for a lack of privacy as peoples DNA will be kept, which is personal information. Thats why many object."]).
answer(number(4),part(d),subpart(0),[131,2,"it is useful for medical resson like if so one need a liver or another organ they can clone someone and us it organ. people object to this because not good for the clone they are mostly misused and some religous people will not like the fact it goes aganist them"]).
answer(number(4),part(d),subpart(0),[132,2,"Being able to clone human cells would mean that it would be possible to generate new body parts for people with defective organs or amputees. Some people object to this as they do not think it is natural and believe you should not be able to select body parts or possibly the genes of a person"]).
answer(number(4),part(d),subpart(0),[133,2,"This may be useful as replacement organs or body parts could be grown. Fewer donors would be needed as the organs would be manufactured rather than donated. However, objections to this would most probably centre around the contraversial issue of the possibility of cloning entire humans and where these processes could lead. It could be argued that free will and individuality would be threatened."]).
answer(number(4),part(d),subpart(0),[134,0,"Useful because they wont die and just keep living. But people want to die and not be brought back to life."]).
answer(number(4),part(d),subpart(0),[135,0,"because it will seem like the scientist are trying to play God with real life humans."]).
answer(number(4),part(d),subpart(0),[136,1,"The cloning of human body cells would be useful if someone needs a transplant to save them, doctors can clone that person and use that organ they need. But if the person has a disease, then the clone would have disease and is a living person."]).
answer(number(4),part(d),subpart(0),[137,0,"If anybody parts where lost Donners where needed."]).
answer(number(4),part(d),subpart(0),[138,0,"Because a good thing from a human body cell can be cloned and produced again, however this is dangerous and the world could have lots of clones causing life to be very different."]).
answer(number(4),part(d),subpart(0),[139,1,"it could be useful that way some one can live again but people could object because it is not really a natural way of reproducting."]).
answer(number(4),part(d),subpart(0),[140,1,"If your child died and you found out why afterwards, then you can make another one and break the problem. People object because it is not for us to play God and go round creating babies when we want. they might use cloning for evil, like using them as soldiers in wars."]).
answer(number(4),part(d),subpart(0),[141,2,"if you produce a human cell you can produce another body part eg a liver or lung. people may protest against this because it is playing \'god\'"]).
answer(number(4),part(d),subpart(0),[142,1,"It may be useful because it could help us to form perfect humans without any birth defects but some people object because the believe it is wrong to misuse cells and go against nature."]).
answer(number(4),part(d),subpart(0),[143,3,"It will be useful for people that are ill and need organ transplants as clones of their own organs will not be rejected by their bodies as foreign organs maybe. Some people think it is inhumane to grow embryos simply for spare body parts. people are worried about designer babies resulting in clones as the world would become artifically full of perfect babies"]).
answer(number(4),part(d),subpart(0),[144,1,"It can useful for those who may have lost a loved one and cannot bear not having them there. Some people object to cloning because they believe it is wrong and against the will of God."]).
answer(number(4),part(d),subpart(0),[145,1,"This will be usefull because you can use them for body parts. But most people disagry because its wrong."]).
answer(number(4),part(d),subpart(0),[146,2,"Cloning human body cells can be used to grow new organs for use in transplants. It would eliminate rejection of the organ because the organ would be genetically identical to the recipient\'s genes. However, some people believe this would lead to cloning of humans to produce embryos and they believe that it is immoral to \'grow\' humans solely to be used as organ donors for others."]).
answer(number(4),part(d),subpart(0),[147,2,"A clone could be grown to donate organs to an ill human. Because the organs would be identical, there would be no problems of rejection. Some people think that it is wrong to intefere with nature and \' play God\' and that a clone should not be created just for organs and then killed."]).
answer(number(4),part(d),subpart(0),[148,2,"This may be useful, because clones can be produced of a healthy organ and transplanted into person with a damaged organ. Some people object to this, because they think that humans should not play the role of God and experiment with genetic engineering."]).
answer(number(4),part(d),subpart(0),[149,2,"It can be useful as we can recreate an organ or specific skin tissue for those injured or disabled. Won\'t have to necessarily wait for a donor. However it is very difficult and often many mutations occur therefore people object. It is also a long and expensive process."]).
answer(number(4),part(d),subpart(0),[150,2,"It may be useful if somebody was trying for a baby, but couldn\'t have one therefore they would have a test tube baby, but some people would rather have it done / processed the natural way!"]).
answer(number(4),part(d),subpart(0),[151,2,"This may be useful because if somebody has a genetic defect or problem, for example blindness, replacement organs can be \'grown\'. Similarly, the replacement of kidneys, hearts and lost limbs will become possible. People object to this process because of the controversy surrounding cloning humans just for \'spare\' body parts. What\'s more, they object the disruption of nature and the idea of some people \'playing God\'."]).
answer(number(4),part(d),subpart(0),[152,2,"This may be useful if a person is missing a limb, such as an arm, scientiests can \'grow\' another one. Some people object to exact replicas / clones of a whole complete person as all individuality would be lost. They believe it is disrespectful."]).
answer(number(4),part(d),subpart(0),[153,0,"It is useful to do further research on that bodies genetics, but if a whole clone is produced, there will be massive trouble and the clone may commit a crime, holding the parent responsible because their DNA is identical."]).
answer(number(4),part(d),subpart(0),[154,0,"because it may help by producing someone after they are dead, yet other people beleive that it may cause Inherrited desease"]).
answer(number(4),part(d),subpart(0),[155,0,"This may be use full to prevent painful deaths illness or suffering such as cancer or parkinson\'s disease."]).
answer(number(4),part(d),subpart(0),[156,0,"It is not fair on the child, they also might be deformed or not live as long as other people and it wouldn\'t be fair."]).
answer(number(4),part(d),subpart(0),[157,1,"It could be useful in organ transplantation, because all of the tissues, cells and blood groups match, some people may object because they think its not fair for people to have an exact recplica of a person made."]).
answer(number(4),part(d),subpart(0),[158,1,"It may be useful because, if a person dies, then a cell from that person can be used to produce another person. People object to this process because they don\'t want the cells to be taken from dead people to produce cloned people."]).
answer(number(4),part(d),subpart(0),[159,1,"it would be use full, because if someone has a Probelem with their body they can be cloned and use the body part on the clone, some people object to this because it is unfair to the clone"]).
answer(number(4),part(d),subpart(0),[160,0,"Some people object because you have to take something from the bucardo and keep it."]).
answer(number(4),part(d),subpart(0),[161,0,"People often object to these types of processes because they don\'t want samples taken from someone they have lost, however it maybe useful to maybe find out reasons why a certain person has died and be able to find a cure for others."]).
answer(number(4),part(d),subpart(0),[162,1,"By producing clones of human body cells, possible diseases an illness\' maybe overcome however this process may lead to full human cloning and designer babies which people do not agree with."]).
answer(number(4),part(d),subpart(0),[163,2,"This can be useful for medical developments such as clone specific healthy cells to replace diseased or damaged cells, or clone insulin producing cells for human use. However this presents ethical dilemmas as to how moral it is to clone humans in part or in whole and whether this should only be done to help save others lives or to produce whole new beings."]).
answer(number(4),part(d),subpart(0),[164,1,"It could stop desease and make people live longer. people protest because they say its wrong and unatural."]).
answer(number(4),part(d),subpart(0),[165,1,"This could be useful because you could clone an intelligent person and keep cloning it so when the other people have died, there\'d just be intelligent people for example. People also object because it is also taking away someones identity and it could also be dangerous as many risks are involved."]).
answer(number(4),part(d),subpart(0),[166,2,"This can be useful to grow organs and body parts which are damaged on people so that they can be replaced. Some people object to this through ethical issues such as that it is not a natural process and it will develop a new race with a desire to be perfect in every way."]).
answer(number(4),part(d),subpart(0),[167,0,"Clones are good in the sense that there is no chance of a disease being passed"]).
answer(number(4),part(d),subpart(0),[168,2,"People who need transplants would be able to get them more easily if organs/body cells could be made on demand. Some people object as they say it is interfering too much with evolution and with God."]).
answer(number(4),part(d),subpart(0),[169,0,"to save lives, some people think that it\'s not right as this isn\'t what are bodies where designed for, cloning."]).
answer(number(4),part(d),subpart(0),[170,2,"This could help the human race to survive however some people think it is morally wrong to have genetically identical humans as they feel we should have individuality."]).
answer(number(4),part(d),subpart(0),[171,3,"Cloning may be advantageous to humans. The main use would be for transplants. If a person needed any organ transplant (eg. heart, liver) by cloning an exact replica of the original organ can be grown and the body will except this organ whereas in other cases it may reject an organ. However the risks in cloning are not yet known and if there was any problem caused by the cloning it could be passed down generations and remain undiscovered for generations. Cloning may also be considered unethical as it involves using an embryo which some consider as a life in its own right. By cloning, therefore, the embryo is being killed and a life taken away."]).
answer(number(4),part(d),subpart(0),[172,3,"It may be useful to find \'\'matches\'\' for certain transplants for example; a bone marrow transplant. However some people object because some things (people & animals) should stay unique and cloning them is immoral and wrong."]).
answer(number(4),part(d),subpart(0),[173,0,"You can produce designer babys and you can make perfect baby"]).
answer(number(4),part(d),subpart(0),[174,3,"because it could help couples that can\'t have kids have a kid. People object because they think its wrong to be messing with nature plus it just copying another person so you could end up with about 50 people who are excactly the same."]).
answer(number(4),part(d),subpart(0),[175,3,"This may be useful because it means that tissues and organs can grown. These can greatly benefit people who have illnesses that require transplants. Cloning could also cause mutations, which is why some people may object to it. Cloning is also useful because it means that infertile couples can have children. Some people may, however object to cloning because it eradicates natural variation which could be dangerous in the future. Some people also object to cloning because they believe it to be unethical."]).
answer(number(4),part(d),subpart(0),[176,3,"It may be useful to produce clones of human body cells because it would provide organs for organ transplants and childless couples could have children made from their own cells rather than relying on egg or sperm donors. However, some people object to this process because cloning greatly reduces life expectancy, and for religious people; cloning is viewed as playing the role of their god(s). Some people also feel not enough is yet known about cloning to actually clone humans."]).
answer(number(4),part(d),subpart(0),[177,3,"Producing clones of human body cells may be useful because if somebody has a disease and can be cured by cloning someone if they have bone marrow which can be used to cure them. Some people would object to this because it is unnatural and does not allow evolution and less variation."]).
answer(number(4),part(d),subpart(0),[178,0,"This can be useful as cloning human body cells can decrease the chances of mutations occuring and they can also be used for growth and repair in the body. Some people may disagree with this because this means creating two identical beings and so they should not be played around with."]).
answer(number(4),part(d),subpart(0),[179,0,"This is useful because it a very important person in the world died then scientist\'s would be able to make a new person (clone)."]).
answer(number(4),part(d),subpart(0),[180,3,"This may be useful to couples who are infertile and wish to have children. Some people object because they feel it is taking away a person\'s individuality and that it is morally wrong and many say it is\'\'Playing God\'\'"]).
answer(number(4),part(d),subpart(0),[181,3,"The cloning of stem cells would allow scientists to produce human organs or other body parts for transplantation, reducing the risk of rejection, allowing rare blood and tissue types to be provided for and without being dependant on a donor. Some people believe that this process may lead to the cloning of human beings in their entirety, the ethical value of which is highly contested."]).
answer(number(4),part(d),subpart(0),[182,3,"Cloning human body cells would mean that organs could be grown to provide more organs for transplants. People who could not have children could grow clones of themselves but some people feel this is interfering to much into nature / Gods laws."]).
answer(number(4),part(d),subpart(0),[183,3,"If clones could be made of humans it would help in making organs for people needed organ transplants. This is because some peoples bodies reject organs they are given or have no organs donated and these people can die. If organs were made as clones it could save many lives. Some, however, believe that it is morally wrong to create life and then destroy it, we should not \'play God\'."]).
answer(number(4),part(d),subpart(0),[184,3,"Human body cells could possibly be used to grow organs or help infertile parents produce children. However in researching this process human embryos might have to be experimented on and this produces ethical dilemmas, especially if children grown from human body cells posess deformities because initially mistakes would be made"]).
answer(number(4),part(d),subpart(0),[185,3,"Producing clones could be useful as it could provide body parts for people who need them. As they are clones of themselves they will not be rejected. People object to this process as they think it is wrong to \'play god\' and wrong to breed something to be killed."]).
answer(number(4),part(d),subpart(0),[186,0,"This is the \'Designer Baby\' situation some people object as they believe it is wrong to be able to choose your babies characteristics i.e. hair colour, eye colour, intelligents. However it could be useful, if a baby had a heart problem you could clone it and use the clones heart to cure the original baby."]).
answer(number(4),part(d),subpart(0),[187,3,"It would be possible to clone organs which then could be used in organ transplants. This would be preferable to using donor organs as there will be a constant supply and there is less chance of the organ being rejected by someone if the DNA is shared. Thus transplants will be more succesful. This could also be useful if someone lost a limb. It may also help advance medicine. However many feel cloning is unethical. They are worried that it is not fair to use an organ simply to give life to someone else. Many people are worried that there will be no limit on how far we go, which could result in humans being completely cloned and this could lead to designer babies. Others are worried the technology could pass into the wrong hands and it would be hard to control who has power when, they object."]).
answer(number(4),part(d),subpart(0),[188,0,"It may be useful if a type of person becomes extinct like an eskimo, or in rebuilding the body from an accindnt. People object because you can recreate the same person after they have died, and they believe that person is dead and shouldn\'t come \'back to life.\'"]).
answer(number(4),part(d),subpart(0),[189,3,"It would be useful to produce clones of human body cells because the best characteristics could be selected and passed on. It would also enable scientists to eliminate the chances of the baby having or developing any serious conditions. Some people object to this because the variation in the world would decrease and they also do not like the fact that it is not a natural process"]).
answer(number(4),part(d),subpart(0),[190,3,"People who are unable to have children will be able to have them. they could be used if someone is medically ill and needs an organ. Although these may be seen as disposable and you are also playing God."]).
answer(number(4),part(d),subpart(0),[191,3,"all over the world there are many people who are unable to have children. Cloning human cells could give those people the chance to have babies. It would also be useful in other areas of medizine - for example healthy organs could be grown which could be used in transplants eliminating the problem of organ-donorship. Some people object to it however, because they think that it is immoral - almost as if people were \' playing god\' and going against natural processes. Some people simply want more care to be taken with the issue because of unforseen problems with the procedure."]).
answer(number(4),part(d),subpart(0),[192,3,"Producing clones of human cells is useful as the cells can be used to create tissue or organs for implantation without the risk of rejection. Also, the cells can be used to produce an embryo for a couple who have difficulty conceiving. Some people object to cloning because they feel humans do not have the right to re-create life or living things."]).
answer(number(4),part(d),subpart(0),[193,3,"It would be useful to clone human cells to produce organs, such as the heart, which are often needed for transplants, and are in short supply.However, it is objected to because some people believe it would lead to the cloning of humans themselves,which may remove the sanctity of life and people would no longer be individuals if someone is made in their image. They believe it is unethical and could have damaging consequences"]).
answer(number(4),part(d),subpart(0),[194,3,"It is useful to clone people so that if theres something wrong with them they can do a clone and use a body part which is not working, some people see this as wrong because they will be tampering with the natural way of life and it would be killing someone at the same time."]).
answer(number(4),part(d),subpart(0),[195,3,"It may be useful in fighting certain diseases, creating new organs for those who need them and creating children for those who can\'t have them. However it is against natural law and religion objects to it, because it would be \'\'playing God\'\'."]).
answer(number(4),part(d),subpart(0),[196,3,"clones can be used to produce embryos, from which the people needing transplant can take bone narrow or organs that they might need and as its genes are genetically identical, there will be no problem with the body rejecting the transplant. Though many countries allow abortion, they believe that creating a \'life\' just to kill it is ethically wrong\' there are huge debates about the ethics of cloning and the unwanted results it can have, like premature aging and arthritus"]).
answer(number(4),part(d),subpart(0),[197,3,"People who have diseases, who are ill or need organ transplants will find it beneficiary for clones to be made because the cloned individual will have the same blood type etc. as them and because it is genetically identical, transplanted organs will not be rejected by the body. This process may be objected to because the clone is an individual in its own right and it may be seen as unfair to produce it simply to allow another individual to live."]).
answer(number(4),part(d),subpart(0),[198,3,"It is useful for making (cloning human insulin) things like insulin, to give to those with insulin deficiencies. Therefore it can save lives. However some people object because they feel that individuality is lost and God would have made two identical people if he wanted them. Cloning may be useful to those people who cannot have children (due to infertility). Instead they could clone themselves."]).
answer(number(4),part(d),subpart(0),[199,3,"This may be useful for transplanting organs,  - people\'s bodies would be more likely to accept organs cloned from their own body. However some people think it is morally wrong as it would be creating a life and then killing it for our own selfish purposes - (ie. playing god)."]).
answer(number(4),part(d),subpart(0),[200,3,"Human body cells are useful to be cloned as people will  because they are missing cells (like bone marrow) can be cloned to produce new cells that won\'t be rejected by the body. However, people say this is wrong as humans should not play God or make an embryo just to kill it again"]).
