answer(number(13),part(b),subpart(ii),[1,0	,"They where in diffrent places warm and cool and light and dark. "]).
answer(number(13),part(b),subpart(ii),[2,0	,"The leaves that where facing the sun and had shade was growing quick and healthy and the leaves in the shade edged to the sun got little sun so they didn't grow quick. The leaves facing the sun with no shade didn't grow cause there was too much sun and no shade and the ones edged to the sun got the amount what they needed but there was no shade and it was dieing off  "]).
answer(number(13),part(b),subpart(ii),[3,0	,"The plant needs sunlight to photosynthesis so it always points it leaves nearest to the sun to get energy. Then the plant photosynthesis. The plant also needs sunlight to transpirate, to get in oxygen to help photosynthis, to make starch. "]).
answer(number(13),part(b),subpart(ii),[4,0	,"The leaves on plants absorb blue and red light from the visible spectrum and reflect green light. chlorophyll causes this, and the light is needed by the plant as a raw material of photosynthesis, (making food). The leaves were leaning towards the sun in order to continue making food for itself. Transpiration is the loss of water from the leaf. In order to remain as efficient as normal the plant needs energy from the sun to make its roots more efficient at cooling the plant and making food. "]).
answer(number(13),part(b),subpart(ii),[5,0	,"Plants need both sunlight and oxygen to survive. Therefore in sunny areas they have a higher chance of surviveing. When plants produce pollen, their (petals) flowers attracts insects which taken the pollen and on the way the seeds are spread to different places, making the plant grow in different surroundings or areas after being transported by insects. (such as bees!) "]).
answer(number(13),part(b),subpart(ii),[6,1	,"Plants need sunlight for food and for energy so in chart 1 the plant are trying to face towards to try and get more sunlight for more food and energy. "]).
answer(number(13),part(b),subpart(ii),[7,0	,"in the two different areas the plant recorded on chart 1 the plant needs more light to photosynthesize so turns to the sun. the second plant in the open area is in sunlight so does not need to reach for it and continue the process of photosythesis. "]).
answer(number(13),part(b),subpart(ii),[8,0	,"They face the to top of the leave toward's the sun light. So they get as much light and energy as posible. "]).
answer(number(13),part(b),subpart(ii),[9,noanswer]).
answer(number(13),part(b),subpart(ii),[10,3	,"In shaded area's the sun is not reaching the plants that's why they turn to face the sun as they are in shade it will not dry them out. When in open area the sun could dry out the plant so they turn so that the edge is to the sun. "]).
answer(number(13),part(b),subpart(ii),[11,2	,"It is different because in the shaded area there is less sunlight for photosynthesis and so the leaves on plant would need to be facing the sun for maxium sunlight. In the open space there would be more sunlight for the leaves. The leaves in the shaded area are more likely to have higher transpiration.  "]).
answer(number(13),part(b),subpart(ii),[12,0	,"When the plants are completly in the sun the edge would be facing because transpiration would be happening quicker so the sun would be evaporating the liquid quicker. In the sun the plant leaves would be facing the sun as much as possible as being shaded transpiration would be happening slower and the rate of photo synthesis would be slower to  "]).
answer(number(13),part(b),subpart(ii),[13,noanswer]).
answer(number(13),part(b),subpart(ii),[14,0	,"Sunlight gives chloropyll to the chloroplasts cell in the plant which gives it its green colour for photosynthesis + transpiration. Oxygen helps release energy for transpiration. Without the sunlight this cannot happen. Thats why the plants grew faster when put in the sun. "]).
answer(number(13),part(b),subpart(ii),[15,0	,"The leaf positions were different in the two areas because the shaded area was not getting any light to make food so it was trying to face the sun to absorb as much light as possible.The open area was getting too much light so it had the edge of the leaf towards the sun to absorb the right amount of light to make food. "]).
answer(number(13),part(b),subpart(ii),[16,0	,"The leafs in the open area where not facing the sun because the sun would take all the water out of the leaf, but in the shaded area the leafs where trying to get to the sun to photosynthesise. "]).
answer(number(13),part(b),subpart(ii),[17,0	,"Plants in the shade face the sun because they want to get as much as possible so they can go through photosynthesis. The plants in an open area do not need so much sunlight as it already has it and needs to transpire.  "]).
answer(number(13),part(b),subpart(ii),[18,0	,"The leaves recorded facing the sun are those found in shaded areas. This suggests that the plant is not receiving enough light to photosynthesise. Therefore the leaves on the plant will have to angle themselves to recieve the light needed however the plants in the open area are receiving enough light so therefore don't need to angel as much to be able to photosynthesise. "]).
answer(number(13),part(b),subpart(ii),[19,	2 ,"	In order for trees two grow they need sunlight so the leaves face the sun. In the shaded area the leafs have to work harder to get sunlight but in the open area they are already getting some. "]).
answer(number(13),part(b),subpart(ii),[20,2	,"For transpiration to take place, the plants need lots of carbon dioxide & water and if there in the shade, no water will be able to get to them. The plants were facing the light in the shaded area, because they grow towards the light for photosynthesis to take place. "]).
answer(number(13),part(b),subpart(ii),[21,4	,"In the shaded area the leaves needed to try face the sun as much as possible for photosynthesis. This would also increase their transpiration rate.Where as the plants in the open area had no shade to shelter them from the sun so although they need sun for both photosynthesis and transpiration they could get enough sun from just having part of their leaves in the sun. As they have too much then they would dry up and not have enough water."]).
answer(number(13),part(b),subpart(ii),[22,0	,"The plant facing the sun took in more energy and stored more because it is always facing the sun. The plant edged away from the sun took less in and stored less, but used more energy to try and get to the sunlight. "]).
answer(number(13),part(b),subpart(ii),[23,0	,"When the leaves are in a shaded area, they lean closer to the sun. This is because the leaves need sunlight for photosynthesis, so when they are in the shade they serch for the sunlight and move towards it. When they are in an open area, they do not need to struggle towards the sunlight because it is all around them. They also edge away from the sun so they get equal amounts of other things they need like, carbon dioxide and water. "]).
answer(number(13),part(b),subpart(ii),[24,noanswer]).
answer(number(13),part(b),subpart(ii),[25,0	,"The leaves in the shade were trying to turn to the sun light because they need this for photosynthesis to occur, the ones in open air were turning away because they don't want to much sun because they will dry out and die. "]).
answer(number(13),part(b),subpart(ii),[26,0	,"because leaves need sunlight for photosynthesis and heat so they can transpire to cool them down and more water can get soaked up by the roots. "]).
answer(number(13),part(b),subpart(ii),[27,0	,"In the two areas there would be different amounts of sunlight, water and carbon dioxide so the leaves would turn at an angle that would best suit their need's. "]).
answer(number(13),part(b),subpart(ii),[28,2	,"In the shaded area, the sunlight covered so the leaves must turn an angle so that at least sunlight & water are reaching the face of the leaf so it can photosynthesise and get as much sunlight & water as possible. However in the open area there is a lot of sunlight & water for transpiration & photosynthesis so they adjust thier angle so that they take as much sunlight as they need & not too much as they may wilt. "]).
answer(number(13),part(b),subpart(ii),[29,1	,"The leaves in the shade need to face the sunlight or they won't be able to photosynthesis, whereas the leaves in the open area get sunlight anyway. "]).
answer(number(13),part(b),subpart(ii),[30,noanswer]).
answer(number(13),part(b),subpart(ii),[31,noanswer]).
answer(number(13),part(b),subpart(ii),[32,0	,"the shaded area did not get the light from the sun that needed the plant to grow and chart 2 had the light so the plant grew more quicker and healthy.  "]).
answer(number(13),part(b),subpart(ii),[33,noanswer]).
answer(number(13),part(b),subpart(ii),[34,0	,"plants need oxygen and sun and water so when it was in the shaded area it weren't getting much of that stuff but when it was in a open area it was getting lots of that stuff and thats why the chart wasn't diffing as much like going up and down."]).
answer(number(13),part(b),subpart(ii),[35,0	,"They were different because a plant needs sun so that in can make photosynthesis and respiration"]).
answer(number(13),part(b),subpart(ii),[36,0	,"as in the shaded area they would not get much sunlight, so there was no need to move but in the open they had a lot of sunlight so moved to get the sunlight onto it's leaves"]).
answer(number(13),part(b),subpart(ii),[37,4	,"In the shaded area there is no light so the leaves have to face the sun to enable them to get some light. This is so the leaves are able to photosynthesize. As they need the sun's energy to be able to do this. In the open area the leaves were able to have plenty of light so they had only an edge to the sun. They were on the side as if the were facing the sun they will be allowing the sun to evaporate the water from the leaves. So on the edge to the sun they will be able to transpire and take in the sunlight for photosynthesis. "]).
answer(number(13),part(b),subpart(ii),[38,0	,"they was different because the sun was on some of them"]).
answer(number(13),part(b),subpart(ii),[39,0	,"Photosynthesis is to do with the sun that's probably what makes the plants grow. The plants that the students have picked are exactly the same so that's probably why the lines in chart 1 and chart 2 were going up and down."]).
answer(number(13),part(b),subpart(ii),[40,0	,"transpiration is affected by humidity and temperature so leaves that where in the shade never grew much because it was cooler here and there was no sunlight. So if there was no sunlight there was no photosynthesis which meant the plant made less food. But when they where facing the sun they made a lot more leaves from when they weren't. The open area grew leaves when the edge was to the sun. This was because it was more humid, water was being lost through transpiration so leaves weren't growing. But when part of it was facing the sun it grew. "]).
answer(number(13),part(b),subpart(ii),[41,3	,"The leaves in the shady area turned towards, the sun, so that they could preform photosynthesis. The leaves in the open area turned so that they were edged to the sun, to prevent transpiration, therefore minimising water loss."]).
answer(number(13),part(b),subpart(ii),[42,0	,"Leaf position is different because in open area the wind blow them towards it. They are also attracted by the sun, which then allows the leaf to produce Glucose using the light from the sun."]).
answer(number(13),part(b),subpart(ii),[43,1	,"Plants need sunlight to transpire and they also need it in photosynthesis. The plants in the shade will find it hard to do these things if there is not enough sunlight available to them. "]).
answer(number(13),part(b),subpart(ii),[44,noanswer]).
answer(number(13),part(b),subpart(ii),[45,1	,"Photosynthesis need carbon dioxide, water, air to transport to the plant when the leaf is shaded it needs light so it is facing the sun and need light. But for chart 2 it is in open space it has Co2, water air and sunlight it is edging to the sun, to transport to the plant you need Co2, water, and air."]).
answer(number(13),part(b),subpart(ii),[46,0	,"transpiration - water loss from the leaves the more the C "]).
answer(number(13),part(b),subpart(ii),[47,0	,"The length wasn't the same so photosynthesis took place at different times. The width wasn't the same it took time for transpiration."]).
answer(number(13),part(b),subpart(ii),[48,0	,"The sun gives light to the leaves then it has transpiration of the leaf."]).
answer(number(13),part(b),subpart(ii),[49,0	,"When the plants are in the shade they try to face into the light and the move in that direction but when the are in the open area they try to edge to the sun so the underneath leaf gets the sun as it doesn't evaporate much water as the top."]).
answer(number(13),part(b),subpart(ii),[50,0	,"The plants might of had good soil to grow in on chart 2 compared to chart 1."]).
answer(number(13),part(b),subpart(ii),[51,noanswer]).
answer(number(13),part(b),subpart(ii),[52,noanswer]).
answer(number(13),part(b),subpart(ii),[53,0	,"There is less sunlight in the shade, so the leaves need to get enough in oreder to photosynthesise. If it gets too much, then transpiration becomes difficult, so the leaves in the open area dont face direct sunlight, but still manage to get enough to photosynthesise"]).
answer(number(13),part(b),subpart(ii),[54,noanswer]).
answer(number(13),part(b),subpart(ii),[55,noanswer]).
answer(number(13),part(b),subpart(ii),[56,noanswer]).
answer(number(13),part(b),subpart(ii),[57,noanswer]).
answer(number(13),part(b),subpart(ii),[58,0	,"The shaded area had more leaves facing the sun because leaves need light to be able to do photosynthesis. The unshaded area had more leaves edge to the sun because the can get light through transpiration. "]).
answer(number(13),part(b),subpart(ii),[59,noanswer]).
answer(number(13),part(b),subpart(ii),[60,noanswer]).
answer(number(13),part(b),subpart(ii),[61,noanswer]).
answer(number(13),part(b),subpart(ii),[62,1	,"The leaves in the shade are facing the sun as they are trying to get all the light they can. The reason the leaves in the sun edge to the sun is because they want to get sunlight but they also want to get rid of excess water through the stomata."]).
answer(number(13),part(b),subpart(ii),[63,	1	,"A plant needs optimum sunlight to reach optimum rate of photosynthesis however the more sunlight it gets the more water it will lose by evaptranspiration, so the plant leaves try to find a point where it can get a happy medium. in dim light or shade this evaptranspiration is not nearly as much of an issue as photosynthesis so the leaf goes all out to soak up the sun's rays."]).
answer(number(13),part(b),subpart(ii),[64,noanswer]).
answer(number(13),part(b),subpart(ii),[65,2	,"plants need light to be able to photosynthesise. The reason for the leafs to be in different positions in the two areas is that A shadowed areas, leaves face the sun directly to recieve as much sunlight as possible. Areas with trees in direct sunlight, just edge to the sun as they don't require as much light. Light & heat also effect the leaves transpiration rate.Leaves that are in directy sunlight require far more water which makes the cells in the leaves become tugid. Leaves that are in shade require a lot of light therefore their cells become facide"]).
answer(number(13),part(b),subpart(ii),[66,2	,"Plants need sunlight in order for photosynthesis to take place, so the plants in the shaded area are angled towards the sun more than the plants in the open area because the plants in the open area get a lot more sun than the plants in the shaded area get."]).
answer(number(13),part(b),subpart(ii),[67,0	,"Because nearly all plants need photosynthesis so all the plants in chart 2 had more leafs to as in chart one only a small amount had leafs because he had no sun for photosynthesis to take place."]).
answer(number(13),part(b),subpart(ii),[68,1	,"In the shaded areas the leaves need as much light as possible, so they lie flat because it gives a larger surface area, so they are at oº mostly. In the sunlight the leaves tend to grow towards the light, which is upwards, so they are all placed at 40º or over. "]).
answer(number(13),part(b),subpart(ii),[69,0	,"because the plants get more oxygen if they arent facing the light. When they face the light they don't get so much oxygen they get more light."]).
answer(number(13),part(b),subpart(ii),[70,0	,"As plants need light to photosynthesyse they have to turn around to get any light and to be able to transpire whereas leaves in the light just need to stay the way that they are facing."]).
answer(number(13),part(b),subpart(ii),[71,noanswer]).
answer(number(13),part(b),subpart(ii),[72,0	,"More shade more room more places to sit or chill in the sun you. Leaf are tottly different from the rest."]).
answer(number(13),part(b),subpart(ii),[73,0	,"When a plant is in constant sunlight it will die because it not pigging up the right amount of water which they need when attracting this much sunlight, where as chart 2 show this chart 1 shows plants in the shade where they can collect all of the water and nurishment needed because of there being enough moisture for them in the ground so they don't need to hide away and be trapped by the sun. "]).
answer(number(13),part(b),subpart(ii),[74,2	,"Leafs need light to grow and make food if the leaves are facing the light than are chloraphyll in the plants can trap the light and will photosynthese. They will grow more there will be a higher percentage of leaves growing.The leaves out of the sun wont grow so much because they have got a lot of sun to make them photosynthese."]).
answer(number(13),part(b),subpart(ii),[75,2	,"For the plants to photosynthesize they need sunlight to make there food. So the leaves in the shade will try harder to get the sunlight to do so. but the leaves in the sunlight have direct contact so they can photosynthesize as much as they need. So the leaves posistions are different because they need to try harder or not try to get the sunlight "]).
answer(number(13),part(b),subpart(ii),[76,0	,"Because if they are all angled facing the sun they will all die at the same time and it will all photosyise again also all the seeds will get transported the same way which means that the seed will plant litterally next to each other which will causes problems when photo-synthesis takes place again"]).
answer(number(13),part(b),subpart(ii),[77, 2	,"Chart 1- tried to face the sun as much as it could to get the most amount of sunlight for photosynthesis. Chart 2- wanted the sunlight but not too much so that the leaves burnt just enough to photosynthesis"]).
answer(number(13),part(b),subpart(ii),[78, 0	,"the leaves in the sun had sufficiant light to photosythisise so could yurn away. The leaves in the shade did not have enough so keept facing the sun as long as posible."]).
answer(number(13),part(b),subpart(ii),[79, 0	,"The leaf positions are different because the transpiration have made it positions."]).
answer(number(13),part(b),subpart(ii),[80, 0	,"the leaf positions were different in the two areas because the sun was moving in the sky so the angle changes on the leaf"]).
answer(number(13),part(b),subpart(ii),[81,noanswer]).
answer(number(13),part(b),subpart(ii),[82,	0	,"leaves need the sun to photosynthesis so wherever the sun is the leaves will face this direction the leaves already have a large surface area for taking in sunlight so if they turn the whole leaf faced towards the sun they can photosynthesis quick"]).
answer(number(13),part(b),subpart(ii),[83,noanswer]).
answer(number(13),part(b),subpart(ii),[84,0	,"More photosynthesis will occur if there is more sunlight, which will increase their amount of food produced, this is why each leaf trys to get as much sunlight from the sun's rays as possible, because it will increase their amount of 'livelihood'."]).
answer(number(13),part(b),subpart(ii),[85,0	,"the leaf in the shaded area was not getting enough sunlight than the leave in the open area one this meant that the leaf in the open area was using photosynthesis to say alive more than the leaf in the shaded area, so more sunlight getting to the open area leaf meant more oxygen getting to it than the shaded leaf."]).
answer(number(13),part(b),subpart(ii),[86,0	,"you know you can get all sorts of leaves so you've got to leafs and done the experiment and done it on the - chart - bar charts and it just came out like edge to the sun in chart 1 it is the graph is on the left and in chart 2 is on the right so that shows the results of the leafs which are two areas for"]).
answer(number(13),part(b),subpart(ii),[87, 2	,"Because transpiration works best in sunny, dry windy areas and without the plant facing the sun, it wont really happen, also for photosynthesis to work it needs light also so if the plant isn't directly by the sun the angle will then change so that it is. As in the equation for photosynthesis is has in it energy (sunlight) carbon dioxide + water > > sunlight glucose + oxygen."]).
answer(number(13),part(b),subpart(ii),[88,	4	,"In the shade area the plants turned to face the sun this was so they could get more sunlight to continual the photosynthesis process. Whereas the plants in one open area had their edge to the sun because the heat would evaporate too much water from the plant, interupting and disturbing the cycle of the transpiration stream."]).
answer(number(13),part(b),subpart(ii),[89,0	,"Transpiration is when water passes out of the leaf through stomata so that it can take in more from the roots - cooler & with more nutrients. When it is hotter & brighter this is easier for it to take place: it was easier for the leaves in the open area for this to happen to. Photosynthesis occurs easily when there is the suns light & chlorophyll (in plant) so leaf would turn to face the chlorophyll in view of the light, then with Co2, photosynthesis can take place.  
"]).
answer(number(13),part(b),subpart(ii),[90,2	,"leafs need to be facing the sun to be able to photosynthisise so if they where in a shaded area the leafs would automatically point towards the sun. If they where in an open area then the leafs wouldn't move very much because they where all ready in the sun.  
"]).
answer(number(13),part(b),subpart(ii),[91,noanswer]).
answer(number(13),part(b),subpart(ii),[92,0	,"In chart 1 the shaded area needed as much light as possible to make photosynthesis happen. In the open area however the leaves needed as much water from the soil as possible being as vertical as possible"]).
answer(number(13),part(b),subpart(ii),[93,0	,"The leaves in the shade have not got as much sun as the leaves in the open so they have lost cloride which would make them alot weaker."]).
answer(number(13),part(b),subpart(ii),[94,1	,"plants need sunlight for photosynthesis but chlorophyll in all green leaves is also needed so for plants to make there own food (glucose) from carbon dioxide they need sunlight which is why when they need to photosynthesise they face the sun and when they don't they are to the edge of the sun. Leaves face towards the sun in the shaded area - need sunlight. The leaves are exposed to it shown in chart 2 so they move away."]).
answer(number(13),part(b),subpart(ii),[95,0	,"Photosynthesis is a process which needs light energy and it helps the plants to grow quicker Transpiration is a process by which the plants absorb the oxygen and food energy to help the plants to breath.  
"]).
answer(number(13),part(b),subpart(ii),[96,1	," Because even though they are facing the sun the leaves in the shade dont get as much light as the one's in the open area "]).
answer(number(13),part(b),subpart(ii),[97,3	,"In the shaded area the leaves would not be photosynthesising as much because they would not be receiving as much light so they would want to face the sun to receive more light. The leaves inthe open area would not want as much light because they'd be losing alot of water by transpiration so the move to the edge of the sun so the transpire less. "]).
answer(number(13),part(b),subpart(ii),[98,2	,"Photosynthesis requires water and light. So in the shaded area, the plant shows the whole leaf facing the sun, hoping to absorb more sunlight using chlorphyll, it shows the whole leaf to increase the surface area so it can get maximum light. In the open area it already does get lots of light, and so it doesn't get too hot and denature enzymes it turns to the side slightly so it still attracts light, but not an extreme amount. Also Transpiration, is the rate at which water moves in the plant. So in a flat leaf - it is going to be quick because it hasn't got far to travel. However in a edge leaf, there is a further distance to travel.  
"]).
answer(number(13),part(b),subpart(ii),[99,0	,"The shaded area had leav edges turning towards the sun to try and catch the sunlight. In the open area the leaves edges were getting enough sunlight and leaning towards the sun so that transpiration could happen."]).
answer(number(13),part(b),subpart(ii),[100,4	," for photosynthesis to happen the pallisade cells need sunlight, oxygen & water. In the shade most leaves will be trying to get as much sun as possible. The leaves in the open area will want to try & keep water in the leaves but also catch the sun so they will not want as much sun so the water doesn't transpire. "]).
answer(number(13),part(b),subpart(ii),[101,0	,"transpiration taken place when the plant is cool and dry so thats why the leaves were trying to get at the best angle for this to happen. (eg like washing dry, needs to be cool & dry)"]).
answer(number(13),part(b),subpart(ii),[102,noanswer]).
answer(number(13),part(b),subpart(ii),[103,0	,"I think why the leaf go resort facing the sun was because it get a bit of sun shinning on it and a b "]).
answer(number(13),part(b),subpart(ii),[104,noanswer]).
answer(number(13),part(b),subpart(ii),[105,0	,"Because the plants need sun light and water and food but if the plant don't get this they is ill eventually one the two leaves were different on facing the sun and the other one was on the edge "]).
answer(number(13),part(b),subpart(ii),[106,0	,"In chart 2 the had they wanted the edge to face the sun because at the top sunlight is need for photosynthesis and at the bottom the sunlight is need for transpiration and to evaporate the water. In chart 1 they need most of what sunlight was there for photosynthesis."]).
answer(number(13),part(b),subpart(ii),[107, 0	," In the shaded area, the plants were not getting enough sunlight to perform photosynthesis, and so they had to turn to face the sun to be able to get enough. In the open area, the plants had as much sunlight as they needed so they didn't have to turn as much to get sunlight to perform photosynthesis"]).
answer(number(13),part(b),subpart(ii),[108,2	," Because for photosynthesis to take place you need sun so the leaves that are in the shade have the leaves facing the sun to try and get more sunlight, but the leaves that are in the sun to try and get a bit more sun to help with the photosynthesis."]).
answer(number(13),part(b),subpart(ii),[109,1	," The leafs positions in the different areas were like it because. In chart 1 the shaded area the leaves needed to get as much sun as possible so they are more or less flat to collect more sunlight."]).
answer(number(13),part(b),subpart(ii),[110,0	," Because plants need the sun to groth its is called photosynthesis with out that they wouldnt grow"]).
answer(number(13),part(b),subpart(ii),[111,0	," because the plants in the sun have got enough sun so they trie not to have their leaves on them all the time were is the plants in the shade the need most of the sunlight amed towards them"]).
answer(number(13),part(b),subpart(ii),[112,noanswer]).
answer(number(13),part(b),subpart(ii),[113,0	,"because in photosynthesis and transpiration you need both sun and shade in order for it to take place. So that is what the plants do."]).
answer(number(13),part(b),subpart(ii),[114,noanswer]).
answer(number(13),part(b),subpart(ii),[115,0	,"Because they had to make it a fair test and do the same things if the leaf was not facing the sun at all they wouldn't of got the results they got."]).
answer(number(13),part(b),subpart(ii),[116,0	,"If a leaf has got more sun it will grow faster what its on"]).
answer(number(13),part(b),subpart(ii),[117,0	,"In light plants photosynthisize producing oxygen, energy and absorbing Co2 but in the dark the proces reverses and so the plant gets away from the light so it was work optimal rate, producing Co2 absorbing oxygen to produce its energy. "]).
answer(number(13),part(b),subpart(ii),[118,0	," the ones in the shaded area where all trying to reach the sunlight where as the leaves in the sunlight are all evenly spaced & recieve sunlight."]).
answer(number(13),part(b),subpart(ii),[119,0	,"Plants all move so they can be facing the sun the is so that all plants can photosynthesis."]).
answer(number(13),part(b),subpart(ii),[120,1	,"The leaves in the shaded area had a greater number facing the sun. I think that this was because they could have a bigger surface area recieveing more light. The leaves in the open area had a variety of angles (most being edge to sun or in between) because the had a lot of light all around them."]).
answer(number(13),part(b),subpart(ii),[121,2	,"for photosynthesis to happen you need sunlight and in a shaded area there is little sunlight so leaves need to face the sun to live. In the open area the leaves get plenty of sunlight so much so, that transpiration might take place which is loss of water from leaves and then they might die. So they edge to the sun to get sun they only require."]).
answer(number(13),part(b),subpart(ii),[122,1	," The plants that are in the shade are leaning towards the sun so they can use it for photosynthesis. They are leaning towards the sun because they have a large surface area and they want to use it for photosynthesis, because they are not getting enough light because they are in the shade. The plant that are in the sun are getting to much sun so turn to the side"]).
answer(number(13),part(b),subpart(ii),[123,0	,"The leaf changed its angle in the shaded area because it needed to absorbe some sunlight so that the leaf could still survive. The leaf changed it's angle in open space so that it could absorbe more energy through the edge of the leaf than face on to the sun (smaller surface area) "]).
answer(number(13),part(b),subpart(ii),[124,0	,"They were different so they could test where photosynthesis takes place best in open area or under shade whether the sun light can still reach the leaves strong enough to make photosynthesis take place and at what angle it's best at. "]).
answer(number(13),part(b),subpart(ii),[125,noanswer]).
answer(number(13),part(b),subpart(ii),[126, 0	," plants need sunlight to grow so there going to be different if there not in sunlight.  
"]).
answer(number(13),part(b),subpart(ii),[127,1	,"In chart 1 it is already in a shaded area so the darker it gets the more it struggles to photosynthesise. In chart two its in an open space so it already has powerful sun meaning it easy to photosynthesise so it needs a little shade to help it grow more efficiently or the plants will be exposed to too much & wilt"]).
answer(number(13),part(b),subpart(ii),[128, 2	," When a plant is in a shaded area it trys to face the sun as much as possible in order to recieve sunlight for photosynthesis. However a plant in an open area will try to get as close as possible to the sun for light as the suns rays are spread out and a plant needs to get close to the sun to get this light."]).
answer(number(13),part(b),subpart(ii),[129, 1	,"the ones in the shaded are get less sunlight so they turn. the one's in the open area get a lot of sun so they don't need to turn. They turn to photosythesize so they could grow"]).
answer(number(13),part(b),subpart(ii),[130,2 ,"	The positions of the leafs in the two areas were totaly different because in the shaded areas the leafs wear facing the sunlight but out in the open the had their edge to the sun because in the open it will have been to hot and in the shade it will have been to cold."]).
answer(number(13),part(b),subpart(ii),[131,0	,"In chart 1 there were alot of leaves because so little of them were facing the sun, and the chart 2 had alot near the edge to the sun because it had an open area."]).
answer(number(13),part(b),subpart(ii),[132,noanswer]).
answer(number(13),part(b),subpart(ii),[133,noanswer]).
answer(number(13),part(b),subpart(ii),[134,0	,"In chart 1 the leaves could not get enough light because it was in a shaded area the light could not get to the leaf that much because it was tilted. In chart 2 the leaves were in open transpiration occured when they were at 45 thats when they photosynthesiced."]).
answer(number(13),part(b),subpart(ii),[135,0	,"when the plant grow the plant have to face the sun if there is not sun they try to head they selve to the sun so it can shine on they plants and the plant can grow bigger and very very stronger and they can grow faster cause they have got energy to grow big."]).
answer(number(13),part(b),subpart(ii),[136,0	,"because the leaves get more sunlight to the sun so they face the sun. They also get more water."]).
answer(number(13),part(b),subpart(ii),[137, 0	,"I think because its in a pertical positions in the two area because it can get the sun they way they get it best so they point that way."]).
answer(number(13),part(b),subpart(ii),[138,0	,"because some of the leafs didn't get that much sunlight (photosynthesis) probably because they weren't facing the sun or weren't growing enough to reach the sunlight."]).
answer(number(13),part(b),subpart(ii),[139, 0	,"When photosynthesis takes place it doesn't all ways stay the same and also produce the same way. There two areas were are different because 1 set had an open area were the sun could get and the other area had shade, so not alot of sun could get there."]).
answer(number(13),part(b),subpart(ii),[140,noanswer]).
answer(number(13),part(b),subpart(ii),[141,1	,"In the open area most of the leaves will be in the sun anyway so don't need to move far. But in the shade the leaves must face the sun because it is needed for photosynthesis to get energy. Also in the open air leaves grow towards the light and away from gravitational pull anyway."]).
answer(number(13),part(b),subpart(ii),[142,noanswer]).
answer(number(13),part(b),subpart(ii),[143,0	,"the leafs need sinlight to respirate oxygen so they can turn carbon dioxide water air, into fresh air to respiration."]).
answer(number(13),part(b),subpart(ii),[144,0	,"The leaf can't produce food for themselves if there not facing the sun. The leafs need sunlight for photosynthesis to work. Photosynthesis is the process in which it produces its own food and minerals. And the sunlight is very important that's why the leafs will always face the sun. It's a automatic natural reaction."]).
answer(number(13),part(b),subpart(ii),[145,noanswer]).
answer(number(13),part(b),subpart(ii),[146,noanswer]).
answer(number(13),part(b),subpart(ii),[147,0	,"The leaves which were in the open area got more light than the ones in the shaded area because the ones in the open area just blew away the ones in the shaded area stay in the same place"]).
answer(number(13),part(b),subpart(ii),[148,0	," That is where the sun shines on the leaf two places."]).
answer(number(13),part(b),subpart(ii),[149,noanswer]).
answer(number(13),part(b),subpart(ii),[150,noanswer]).
answer(number(13),part(b),subpart(ii),[151,1	," In the open area they have the sunlight on them all the time but in the shade the is hardly any sunlight at all."]).
answer(number(13),part(b),subpart(ii),[152,0	," The leaf positions were different in the two areas because in the shaded area it is difficult for sunlight to get to the leaf and for photosynthesis to take place and the open area it is easier for sunlight to get to the leaf and so much easier for photosynthesis to take place."]).
answer(number(13),part(b),subpart(ii),[153,0	," If light can get to them they will grow it depends on where they are in A shaded place or an open Areas.  
"]).
answer(number(13),part(b),subpart(ii),[154,2	," The leaf posistion will be different depending upon the plant, the majority of the leaves would be facing towards the sun, to produce photosynthesis but the plants also need transpiration to feed so that they live."]).
answer(number(13),part(b),subpart(ii),[155,1	," The shaded area hasnt much light so the leaf has to try to get some somehow - leaning towards the sun. Maybe little rain goes there so it tries getting that as well. In the open area, the leaf doesn't need to worry bout getting oxygen water or sunlight because it can get it easily."]).
answer(number(13),part(b),subpart(ii),[156,noanswer]).
answer(number(13),part(b),subpart(ii),[157,0	," The leaf positions were different because the leaves outside would get more sunlight. Where as the ones in the shaded area wouldn't get any sunlight."]).
answer(number(13),part(b),subpart(ii),[158,noanswer]).
answer(number(13),part(b),subpart(ii),[159,1	," Because in the open area there was nothing blocking the light so they got enough. But in the shaded area they didn't get enough so they keep trying to get more by actually facing the sun not just edging it"]).
answer(number(13),part(b),subpart(ii),[160,noanswer]).
answer(number(13),part(b),subpart(ii),[161, 0	," plants need the sun to photosynthesis if a plant is in a shaded area the plant trys its best to get sun rays so the plant can photosyntisis this is how in chart 1 the plants facing the sun is higher than chart 2  
"]).
answer(number(13),part(b),subpart(ii),[162, 2	,"When the leaves are in a shaded area they need to get the whole of their leaf surface in the sun so that photosynthesis can take place and they can grow when the leafs are in an open area they will get sun on them anyway so they put their eage out so that they can moved easier by the wind and transpiration."]).
answer(number(13),part(b),subpart(ii),[163,noanswer]).
answer(number(13),part(b),subpart(ii),[164,noanswer]).
answer(number(13),part(b),subpart(ii),[165, 0	,"All plants need sunlight, warth oxygen in order to photosynthes. That is why that in the shaded area leaves have changes there direction in order to face the sun. In open area the leaves are at the edge to the sun for the same purpose. The plants depend on the sun to live and reproduce."]).
answer(number(13),part(b),subpart(ii),[166,0	,"As the leaf on chart 1 was facing the sun it turned less because there wasn't much sun getting to it because it's in the shade. On chart 2 it is in the open area so the sun is on it and turns to face the sune more"]).
answer(number(13),part(b),subpart(ii),[167,2 ,"	In a shaded areas leaves need as much sun as they can get to photosynthesis this is why over half faced directly to the sun. In the open area light is easier to take in for photosynthesis this is why most leaves are at an angle to the sun so as their cells are not damaged."]).
answer(number(13),part(b),subpart(ii),[168,noanswer]).
answer(number(13),part(b),subpart(ii),[169, 0	,"plants always have their leaves towards light so that food can be produced, for photosynthesis, when photosynthesis is working its clear that transpiration works at a faster rate because chloroplyll needs water and minerals to work properly and at a faster rate when photosynthesis is working more water gets obsorbed in the roots and it travels up the xylene tubes and through the leaves guard cell."]).
answer(number(13),part(b),subpart(ii),[170, 0	,"the leafs could have been facing the sun but the sun has moved and the plants have stayed in the shade."]).
answer(number(13),part(b),subpart(ii),[171,0	,"If the sun hits the flower then they will grow."]).
answer(number(13),part(b),subpart(ii),[172,0	,"not all the plants need the sun for photosynthesis they can also photosynthesis in the shade but other plants need the sun so if the we put the plants in chorl to an open area but facing the sun + the chart 2 in a shaded the facing the sun the results could be the same."]).
answer(number(13),part(b),subpart(ii),[173,noanswer]).
answer(number(13),part(b),subpart(ii),[174,noanswer]).
answer(number(13),part(b),subpart(ii),[175,noanswer]).
answer(number(13),part(b),subpart(ii),[176, 0	,"The shaded area were growing slowly but well because they were in the shaded and cool area where as the open are leaves were growing but together they were not spreaded out and were not getting enough drink. (water)"]).
answer(number(13),part(b),subpart(ii),[177, 0	,"Because chart 1 is higher than chart 2"]).
answer(number(13),part(b),subpart(ii),[178,noanswer]).
answer(number(13),part(b),subpart(ii),[179, 3	,"The plants in the shade wanted to get as much sulight as possable so they face the sun directly. The plants in a open area, are at a risk of burning and loosing too much water so they face the edge of the sun."]).
answer(number(13),part(b),subpart(ii),[180, 0	,"Because for photosynthesis you need carbon dioxide + water + chlorphyll and light. But when you get to much of one, in this case light, too much water can be lost by transpiration so the leaves turns to aviod the water being lost due to transpiration, preventing growth "]).
answer(number(13),part(b),subpart(ii),[181, 1	,"photosynthesis is the process of plants turning sunlight into energy. Most of the leaves in the shade faced the sun to get as much sunlight as possible"]).
answer(number(13),part(b),subpart(ii),[182, 0	,"Plants need the sun to preform photosynthisis and they need that to survive. So in the shaded area the leaves turned to face the sun. But in the open area the leaves had their edge to the sun"]).
answer(number(13),part(b),subpart(ii),[183,noanswer]).
answer(number(13),part(b),subpart(ii),[184,noanswer]).
answer(number(13),part(b),subpart(ii),[185,noanswer]).
answer(number(13),part(b),subpart(ii),[186, 0	,"  
Because in the shaded area the leaves could trap as much sunlight energy so it was harder for the plant to photosynthesis it made it harder as the plant did not grow and have enough energy where as the plant in the open had allot of sun so it made it easier for photosynthesis to take place so the plant could grow easily so the plant ony needed to tilt its leaves to the sun.  
"]).
answer(number(13),part(b),subpart(ii),[187,noanswer]).
answer(number(13),part(b),subpart(ii),[188, 0	," Because in the shaded area, the leaves needed the sun to photosynthesis, but in chart 2 the leaves her getting sun & air (co2) so they didn't need to be so close to the sun "]).
answer(number(13),part(b),subpart(ii),[189, 	0 ,"	Because to photonise you need alot of sun so the leaves facing the sun grew alot more and there was more of them, plus they are used to sun. But in the shaded part there was no leaves facing the sun and not as many leaves were growing. "]).
answer(number(13),part(b),subpart(ii),[190,	1	," altough plants need sun to photosythesis to much sun will just stop them from getting enouth nurisment from the ground so they angle them selfes with edge to the sun to limit the amount they take in.   
"]).
answer(number(13),part(b),subpart(ii),[191,	3 ,"	Plants and leaves tend usually to grow and face towards the sunlight this is so that the chloroplasts can absorb the light of the sun more easily for photosynthesis in order to produce starch for food. Transpiration is the amount of water loss from the leaves. So the leaves will want to grow so that least water loss is achieved. Therefore depending on what area they are in depends on how they grow as they have to adapt to the surroundings   
"]).
answer(number(13),part(b),subpart(ii),[192, 0 ,"	They were both different due to the fact that the amount of sunlight that they were recieving was different. Plants need sunlight to callgout photosynthesis and transpiration so the leaves where moving to where ever they could recieve the most sun light and moisture.   
"]).
answer(number(13),part(b),subpart(ii),[193, 0 ,"	Plants need a certain amount of sun to be able to photosynthesize, but they need an equal amount of the factors do so leaves lose more water through the underside of the leaf as the upperside has a waxy protective layer. When the edge is to the sun it gets the right amount of sun but also loses an equal amount of water "]).
answer(number(13),part(b),subpart(ii),[194,noanswer]).
answer(number(13),part(b),subpart(ii),[195,noanswer]).
answer(number(13),part(b),subpart(ii),[196,noanswer]).
answer(number(13),part(b),subpart(ii),[197, 0 ,"	the photosynthesis goes towards light transpiration is see through skin. "]).
answer(number(13),part(b),subpart(ii),[198, 0 ,"	The plants in the shaded area were mostly facing the sun as they were trying to get as much light as possible for photosynthesis. The plants in the sun did not need to do this but they had their edges towards the sun so that they could transpire and get new nutrients from the soil through the roots "]).
answer(number(13),part(b),subpart(ii),[199,	0	," because when you have get the sun on something and when you haven't it is a different sorry. "]).
answer(number(13),part(b),subpart(ii),[200, 0 	," Because leaves sway and grow in different phases. Different roots and life. "]).
answer(number(13),part(b),subpart(ii),[201, 0 ,"   
because in the shaded areas photosynthesis didn't occur properly as there was not enough water and sunlight being absorbed therefore some plants in the shaded areas were transpiring and transporting water from the top of their leaves down to the roots they were also probably uptaking water by transpiration to different parts of the leaves  
 "]).
answer(number(13),part(b),subpart(ii),[202, 0 ,"   
The leaves are trying to obtain the most light they can get. When the leaves angle themselves they are trying to get the most light possible so they can use it in photosynthesis. (make glucose) so they can then transport more energy: making more glucose.   
 "]).
