:- multifile answer/4.

answer(number(6),part(a),subpart(0),[1,	2	,"When the body falls below normal the blood vessels 'vasoconstrict' where the blood supply to the skin is cut off, increasing the metabolism of the body.  This prevents heat loss through the skin, and causes the body to shake to increase metabolism. 	"]).
answer(number(6),part(a),subpart(0),[2,	0	,"the blood vessels supply warm blood and take away cold blood to warm up inside the body.	"]).
answer(number(6),part(a),subpart(0),[3,	1	,"They cut off the blood supply to the skin, therefore reducing the amount of heat loss by vasoconstriction. The hairs are also stood up to keep warmth in and the sweat glands do not secrete any sweat to keep the body as warm as necessary. (Homeostasis - maintenance of a constant internal environment)	"]).
answer(number(6),part(a),subpart(0),[4,	0,"The blood vessel would stop the blood going to the sweat glands, hair root and capillary loop so that it can flow to more needed areas. It would also build up the fat layer to keep in heat. 	"]).
answer(number(6),part(a),subpart(0),[5,	1	,"The blood vessels ie. capillaries constrict and move away from the skin surface, more blood is kept deep in the body, away from the cool skin surface	"]).
answer(number(6),part(a),subpart(0),[6,	1	,"Blood vessels reduce heat loss by vasconstriction. this is where the blood vessels stop blood flow to cappillary loop. This stop heat loss because is blood was passing through the cappillary loop is would look heat as it is close to the surface	"]).
answer(number(6),part(a),subpart(0),[7,	0	,"The blood vessels will contract and close up using the heat to stay in and the cold to stay out	"]).
answer(number(6),part(a),subpart(0),[8,	1	,"The process which stops the body temperature falling is called vasoconstriction. The hairs stand up to trap warm air. The blood supply to the skin is cut off to conserve heat and the sweat pore don't produce any sweat.	"]).
answer(number(6),part(a),subpart(0),[9,	0	,"they can close sweat pores so heat isn't lost through them and relax the hair muscles to reduce the loss and can pump the blood around slower to avoid losing too much energy	"]).
answer(number(6),part(a),subpart(0),[10,	1	,"If this occurs the body carries out a process called Vasoconstriction.  This causes the hair muscle to contract and the hairs stand on end sweat pores close and blood flows lower down away from the surface to prevent any heat loss. 	"]).
answer(number(6),part(a),subpart(0),[11,noanswer]).
answer(number(6),part(a),subpart(0),[12,noanswer]).
answer(number(6),part(a),subpart(0),[13,	1	,"the blood vessels pump the blood further away from the skin surface so that heat from the blood is not lost through heating up the skin and going into the air	"]).
answer(number(6),part(a),subpart(0),[14,	0	,"The blood vessels expand or contract depending on the temperature.  When it is hot they contract so less blood flows through.  When it is cold they expand so more blood flows through	"]).
answer(number(6),part(a),subpart(0),[15,	0	,"Letting some liquid (sweat) out through the sweat glands	"]).
answer(number(6),part(a),subpart(0),[16,	2	,"Vasoconstriction. The lumens of the vessels are made smaller, so they do not run as close to the skin, this reduces the amount of energy needed and heat produces. Less blood is pumped through the vessel at any one time.	"]).
answer(number(6),part(a),subpart(0),[17,	1	,"When the body gets cold the temperature receptors send a message to the nerves which send an impulse to the blood vessels near the surface of the skin to tell them to close off, they do this so the heat is not lost from the blood when going near to surface and the heat from the blood is kept for the inner tissues or the body.	"]).
answer(number(6),part(a),subpart(0),[18,	1	,"Vaso Constriction takes place to reduce heat loss.  The blood Suplie is reduced to Save energy and that is why we go pale	"]).
answer(number(6),part(a),subpart(0),[19,	2	,"The ducts shut, stopping blood circulating near the surface of the skin where it would lose heat faster. This is called vasoconstriction, and means that the blood retains it heat because it doesn't escape by circulating near the surface, therefore reducing heat loss	"]).
answer(number(6),part(a),subpart(0),[20,	0	,"First of all the sweat pores will close up so not liquid can get out of them. Their blood will be pumped more to areas near the skin so that they warm up. This is an effort to counter the cold environment out side the skin.	"]).
answer(number(6),part(a),subpart(0),[21,	0	,"The blood vessels open up and the blood flows into the capilaries just under the surface of the blood.	"]).
answer(number(6),part(a),subpart(0),[22,	1	,"They move further away from the skin and the walls constrict to make less room for the blood to flow through.	"]).
answer(number(6),part(a),subpart(0),[23,	0	,"Our sweat glands close so that no heat can be lost	"]).
answer(number(6),part(a),subpart(0),[24,	2	,"If the body temperature falls below normal then the blood will not flow so near to the surface of the skin so the heat in the blood is kept in the body and not allowed to escape into the air.	"]).
answer(number(6),part(a),subpart(0),[25,	0	,"when the body is cold the blood vessels get smaller so our bodies can keep an average core temperature around the heart.	"]).
answer(number(6),part(a),subpart(0),[26,	0	,"They move further away from the surface of the skin, and become narrower (capillaries).	"]).
answer(number(6),part(a),subpart(0),[27,	2	,"To reduce heat loss the blood vessels close up, stopping blood reaching the skin and losing heat out from sweat pores. The body then has goosebumps which don't allow heat out of the body.	"]).
answer(number(6),part(a),subpart(0),[28,	0	,"The blood vessel moves further into the body to warm the blood more, in the fatty layers so it can radiate its heat into the body and skin.	"]).
answer(number(6),part(a),subpart(0),[29,noanswer]).
answer(number(6),part(a),subpart(0),[30,	1	,"blood vessels reduce heat loss by reducing the amount of blood flowing towards the skin. This reduces the amount of heat lost by not allowing so much heat to the skin	"]).
answer(number(6),part(a),subpart(0),[31,	0	,"	The hair will stand up trapping air underneath it and the blood vessels will go deeper into the skin to stop the heat escaping so easily, and the fat layer will act as a insulator.	"]).
answer(number(6),part(a),subpart(0),[32,	0	,"	When body temperature fall below normal, the brain sends messages telling the blood vessels to expand so more 'warm' blood can reach the colder parts of the body	"]).
answer(number(6),part(a),subpart(0),[33,	0	,"	The blood will be pumped around at a slower rate, then the heat loss will be reduced as it will not give out so much heat and not at as much of a fast rate.	"]).
answer(number(6),part(a),subpart(0),[34,	0	,"	The blood vessels come colser into the skin to reduce the amount of heat lost.  If the body was too warm, the blood vessels go right up to the surface of the skin to help cool the body down.  That's why we go red when we get hot.	"]).
answer(number(6),part(a),subpart(0),[35,	3	,"	The blood vessels cut off the blood capillary loop so that the blood stays inside the body and not near the skin where heat can be lost from the blood.	"]).
answer(number(6),part(a),subpart(0),[36,	0	,"	When the body temp falls below normal the hair muscles are sent signals, making the hairs on the body stand on end. This makes air particles trapped between the hairs keeping the body warm. The blood vessels and blood capillary loop gets smaller. This is how the body reduces heat loss.	"]).
answer(number(6),part(a),subpart(0),[37,	3	,"	The blood vessels will constrict so that there is less blood flowing through them at the surface Less blood flow at the surface of the skin means that more body heat can be retained. Heat is less likely to be lost by conduction, radiation and evaporation.	"]).
answer(number(6),part(a),subpart(0),[38,	3	,"Vasoconstriction occurs, and this is where blood moving through the blood capillary loop is cut off.  Because blood is now not flowing near to the skin surface less heat is lost from the blood.	"]).
answer(number(6),part(a),subpart(0),[39,	1	,"If the body temperature falls below normal then the blood vessels contract therefore making it harder for the blood to pass through them. This makes your heart pump faster therefore warming you up.	"]).
answer(number(6),part(a),subpart(0),[40,	2	,"In cold body temp blood is made to flow further from the skin. The vessels constrict and this allows less heat to be lost from the body. Also, hormones come through these vessels to instruct the shivering 'process to begin (the hypothalamus detects temperature.)	"]).
answer(number(6),part(a),subpart(0),[41,	0	,"They pump more blood around so, that it is heating the body up more, because it gets heat from the heart and lungs, so that it goes through there more often.	"]).
answer(number(6),part(a),subpart(0),[42,	0	,"When the body is colder than normal The blood vessels don't flow near the skin to keep all heat from the blood internal. They close the sweat gland. The blood capillary loop stops and the only flow of blood is through the blood vessels and other major vessels, veins etc	"]).
answer(number(6),part(a),subpart(0),[43,	2	,"The blood vessels cut off the blood supply to the skin (to the blood capillary loop) by a process called vas-constriction. Normally, the blood going to the surface is cooled up in the blood capillary loop, but by no blood getting there, it doesn't get cooled. Also, the sweat gland is inactive, as it has no blood to excrete water from.	"]).
answer(number(6),part(a),subpart(0),[44,	1	,"if a low temperature is detected then the blood vessels supply less blood to the skin capileries and so the blood maintains it's temperature by not being exposed to the cold 	"]).
answer(number(6),part(a),subpart(0),[45,	0	,"The blood vessels stay close to the fat layer in order to absorb heat and have it transported around the body in the blood.	"]).
answer(number(6),part(a),subpart(0),[46,	2	,"The blood vessels restrict the blood flow from reaching the surface (near) of the skin. The capillary network is cut off and minimal heat from the blood is lost. i.e the blood vessels closes circulation to sweat gland + capillary loop is cut off from supply.	"]).
answer(number(6),part(a),subpart(0),[47,	0	,"The hypothlamus sends a signal to your body saying body is to cool. The blood capilliaries retract from surface and become thinner which reduces heat loss from the surface. Hairs also stick in the air to trap any heat, lets blood near surface	"]).
answer(number(6),part(a),subpart(0),[48,	0	,"they make the sweat glands stop and pump warm blood under the surface of the skin	"]).
answer(number(6),part(a),subpart(0),[49,	2	,"The capillary loops near the skin constrict and don't allow much blood to pass when cold is detected, so the warm blood is kept in the blood vessels further in as to not lose heat energy through the skin."]).
answer(number(6),part(a),subpart(0),[50,	0	,"More blood goes through the blood vessels. As blood is warm it warms up the body by running next to the skin"]).
answer(number(6),part(a),subpart(0),[51,	0	,"Blood vessels contract and prevent heat loss by moving closer together this helps reduce any heat loss.  Your body will try + keep its temperature around 37 ºC.  This is the bodies optimum working temp.  It will slow blood down as well.  	"]).
answer(number(6),part(a),subpart(0),[52,	0	,"They expand and thicken so heat energy can't pass through them	"]).
answer(number(6),part(a),subpart(0),[53,	0	,"the sweat pore and sweat gland are attached to the blood vessels and these help the body temperature to try and remain constant. The sweat replaces the heat.	"]).
answer(number(6),part(a),subpart(0),[54,	0	,"More blood vessels are sent to the affected area thus making the layer thicker. the more blood vessels mean that heat is not lost at such a rapid rate as the layer beneath the skin is thicker.	"]).
answer(number(6),part(a),subpart(0),[55,	0	,"everything inside your body becomes tight and closes up all your pores, hair muscles also stiffen up causing hair to stand on end. Sweat pores also close up so less cold is absorbed	"]).
answer(number(6),part(a),subpart(0),[56,	0	,"they constrict allowing less blood to flow to less important places.  Instead pumping around places where it is needed.	"]).
answer(number(6),part(a),subpart(0),[57,	0	,"They grow hair (Armpit hair) to take in heat and the less heat you have to more hair will grow.  Also the more sweat will make the arm hair grow.  If you wash you should not have as much arm hair?	"]).
answer(number(6),part(a),subpart(0),[58,	0	,"If there is heat loss the blood vessel causes the hair muscles to straighten the hair so it is rigid and therefore air is trapped in between the hairs and is heated by the body and as a result heats the body.	"]).
answer(number(6),part(a),subpart(0),[59,	0	,"The blood vessels will close the connection to the sweat gland so no water is allowed through the sweat pores to cool the body down. They also rise to the surface of the skin to create heat as the blood flows along and creates kinetic energy.	"]).
answer(number(6),part(a),subpart(0),[60,	3	,"If the body temperature falls below normal then the blood vessels near the surface of the skin contract and reduce the blood flowing through them.  This means that less blood flows near the surface and loses its heat so it stays nearer the vital organs keeping warm and warming the body as it flows round the vital parts	"]).
answer(number(6),part(a),subpart(0),[61,	0	,"The blood vessels reduce heat loss, if the body temperature falls below normal then the hairs help to warm the body up to get it back to its normal temperature.	"]).
answer(number(6),part(a),subpart(0),[62,	0	,"The blood flows through the capilaries heating the surface. Sweat gland is stoped hairs lay down to insulate the body.	"]).
answer(number(6),part(a),subpart(0),[63,	0	,"blood vessels reduce heat loss by widening & letting more blood through, the vessels therefore going up through the blood capillarys in the skin & hearing the muscles and skin around.	"]).
answer(number(6),part(a),subpart(0),[64,	2	,"if the body temperature falls below normal, the blood vessels prevent blood from reaching the skin.  This is to prevent heat loss and is known as vasoconstriction."]).
answer(number(6),part(a),subpart(0),[65,	0	,"If the body temperature falls below normal, the blood vessels lower themselves in order for them to keep as much heat as possible to regain normal body temperature. The blood travelled round the body with more heat helping for the body to regain normal body temperature.	"]).
answer(number(6),part(a),subpart(0),[66,	2	,"If the body temperature falls before normal the blood vessels shut of access of blood to the capillary loop near the surface of the skin so as heat can not be lost easily by conduction or radiation.	"]).
answer(number(6),part(a),subpart(0),[67,	1	,"If the body temperature falls below normal, vasoconstriction takes place. Hairs stand on end, sweat pores are blocked and the capillaries do not supply blood close to the surface of the skin as alot of heat is lost this way.	"]).
answer(number(6),part(a),subpart(0),[68,	1	,"The blood vessels reduce heat loss if the body temperature falls below normal, by shutting the blood off so that the body doesn't lose heat from the blood capillary loop.  Therefore, normal body temperature is contained and the temperature gradually gets back up to the normal temp	"]).
answer(number(6),part(a),subpart(0),[69,	1	,"They vasoconstrict.  This causes the blood vessels to become smaller and lye lower under the skin.  This makes the surface area smaller and its better insulated. 	"]).
answer(number(6),part(a),subpart(0),[70,	2	,"the blood vessels reduce heat loss by passing less blood round the blood capillary loop they do this because the capillary loop is near the surface of the body and heat is easer to loose near the surface of the body.	"]).
answer(number(6),part(a),subpart(0),[71,	1	,"If the body temperature falls below normal then the blood vessels cut / limit the supply of blood to the cappillaries. This keeps the internal body system warm so they can continue their jobs.	"]).
answer(number(6),part(a),subpart(0),[72,	2	,"vasoconstriction occurs. The blood vessels get thinner. less blood flows near the cold surface of the skin. This way less heat is lost.	"]).
answer(number(6),part(a),subpart(0),[73,	1	,"If you become over heated your vessels raise to the surface, (cool blood down) but in order to raise body temperature your vessels reduce to deep underneath your skin to minimise heat loss from your blood"]).
answer(number(6),part(a),subpart(0),[74,	1	,"The hairs on our body tend to stand up, and no sweat is produced and the blood supply of the skin closes off. And this is called vasconstriction	"]).
answer(number(6),part(a),subpart(0),[75,	0	,"The blood vessels help by the blood flowing up to the blood capilary loop, and keeping the circulation going so the body doesn't loose any more heat and therefore keeps temperature back to normal.	"]).
answer(number(6),part(a),subpart(0),[76,	0	,"all the blood move faster and dose not go near the top of your skin they stay close to the moses	"]).
answer(number(6),part(a),subpart(0),[77,	0	,"If the body temperature falls below normal then the blood vessles will expand so that more oxygen can pass through forming more movement which creates more heat.	"]).
answer(number(6),part(a),subpart(0),[78,	0	,"They vascodilate which means they let more blood through them so this gives everything a good blood supply so for example the hairs can stand on end or your muscles can shiver.	"]).
answer(number(6),part(a),subpart(0),[79,	1	,"The blood vessels contract to prevent blood from moving near to the skin.  Through the method of 'vasoconstriction' the blood is kept near the core without long heat to the outside.	"]).
answer(number(6),part(a),subpart(0),[80,	0	,"blood vessels reduce heat loss as blood is warm and when traveling around the body it can often have a fatty layer or fat layer above in acting as an insulator which means the blood is warm warming up part around the blood vessels. 	"]).
answer(number(6),part(a),subpart(0),[81,	1	,"If the body temperature falls below normal the blood vessels stop the blood circulating in the blood capillary loop so the blood is pumping closer to the body.  It also makes a muscle contract so that the hair will stand up on end	"]).
answer(number(6),part(a),subpart(0),[82,	1	,"If it really cold then our blood vessels vasoconstrict. This means that they stay thin. This occurs because if the blood vessels vasodilates then the surface area for heat loss through the blood is greater. So if the blood vesseles are thinner or constricted then they don't lose heat as readily. 	"]).
answer(number(6),part(a),subpart(0),[83,	2	,"To reduce the heat loss the blood capillary loop falls below the fat layer (vase constriction) so that the heat from the blood is insulated by the fat. In this way not too much heat is lost through the skin. This action is determined by the hypothalamus in the brain	"]).
answer(number(6),part(a),subpart(0),[84,	0	,"The blood vessels will pump more water up through the blood capillaries, sending oxygen to all parts of the skin. It will pump it more quickly as heat is being lost at a faster rate. The sweat pores will close to minimise heat loss."]).
answer(number(6),part(a),subpart(0),[85,noanswer]).
answer(number(6),part(a),subpart(0),[86,	0	,"The blood vessels expand so that more blood can pass through they also move away from the surface of the skin	"]).
answer(number(6),part(a),subpart(0),[87,	1	,"The circulation around the skin ( the blood capillary loop) is cut off by the blood vessel. This along with other factors to control the body temperature when it is low is caused vasoconstriction."]).
answer(number(6),part(a),subpart(0),[88,	0	,"The blood is pumped round that part of the body faster, with the sphincters in there relaxing, so therefore the more warm blood there is, the more heat there is for it to give off.	"]).
answer(number(6),part(a),subpart(0),[89,	0	,"The blood vessels move away from the skin so that less heat is lost. The pores also close up.	"]).
answer(number(6),part(a),subpart(0),[90,	0	,"If the body temperature falls low, the blood vessels will get smaller, therefore less blood is flowing through them and less heat will be lost through the skin."]).
answer(number(6),part(a),subpart(0),[91,	1	,"the blood capillary loop is shut off from the capillary so the blood is not close to the skin surface. The hair muscle allows the hair to stand errect from the skin acting as insulation. The sweat pore closes + the sweat gland stops releasing sweat so as not much energy is lost	"]).
answer(number(6),part(a),subpart(0),[92,	1	,"In the blood capillary loop, the upper blood vessels will contract so that less blood can pass through it, therefore retaining body heat, but still supplying oxygen to the skin.	"]).
answer(number(6),part(a),subpart(0),[93,	2	,"When the body detects a temperature below normal a signal is sent and the body thermoregulates. The blood vessels therefore vasoconstrict which reduces heat loss from the blood."]).
answer(number(6),part(a),subpart(0),[94,	0	,"the blood vessels move further away from the skin to try and warm up	"]).
answer(number(6),part(a),subpart(0),[95,	2	,"Vasoconstriction, blood flow is prevented from flowing through the blood vessels in the skin, this heat is not lost from the skin to cooler areas once heat is conserved"]).
answer(number(6),part(a),subpart(0),[96,	0	,"The hair muscle becomes erectile and the hairs are then standing up on end trapping air, therefore reducing heat loss.  The blood capillary loop contracts to become warmer.  The fat layer will insulate, also."]).
answer(number(6),part(a),subpart(0),[97,	0	,"The blood vessels pump more blood to the capillaries beneath the skin. The pressure here increases and the temperature also increases. This then heats up the body to reduce heat loss."]).
answer(number(6),part(a),subpart(0),[98,	1	,"The blood vessels vasoconstrict (they get narrower) near the skin surface so that there is less blood smaller surface area exposed to the air and cold surface of the body so that the warm blood can keep the inner-body warm, i.e. the organs"]).
answer(number(6),part(a),subpart(0),[99,	2	,"If baby temperature falls the blood vessels stop supplying blood to the capillaries; this is called vasoconstriction. This keeps all the blood and warmth nearer the centre of your body because that is where all the organs are. This keeps the organs warm and stops heat being lost through the surface of your skin because the blood isn't flowing to the surface of your skin.	"]).
answer(number(6),part(a),subpart(0),[100,	2	,"If body temperature falls below normal, the blood vessels will prevent blood from flowing up the blood capillary loop therefore reducing heat loss because the warmth of the blood will not be near the surface of the skin.  This is called vasoconstriction. "]).
answer(number(6),part(a),subpart(0),[101,	1	,"They stop blood going into the blood capillary where it is close to the skin surface and would lose heat energy quickly there (vasilaconstriction). This means the body will be warmer as the blood will be warmer."]).
answer(number(6),part(a),subpart(0),[102,	1	,"By cutting off the supply to the skin. So that less heat is lost from the blood.  therefore no blood circulates near the skin."]).
answer(number(6),part(a),subpart(0),[103,	0	,"The blood is passed through the blood capillary loop, causing the tissue around it to warm up."]).
answer(number(6),part(a),subpart(0),[104,	2	,"the blood vessels, through a process called vasoconstriction reduce their size and surface area, therefore allowing less heat to be lost from the skin."]).
answer(number(6),part(a),subpart(0),[105,	2	,"The blood vessels constrict the blood going near the surface and they close up so that, heat is not lost when body temperature is low. This is called vasoconstriction."]).
answer(number(6),part(a),subpart(0),[106,	0	,"To help reduce heat loss blood vessels move away from the surface.  When this happens the vessels are not so obvious on the skin surface.  This prevents heat or helps to prevent heat from being lost so easily through the skin. 	"]).
answer(number(6),part(a),subpart(0),[107,	0	,"they flow further away from the skin to prevent heat loss"]).
answer(number(6),part(a),subpart(0),[108,	2	,"They cause the blood capillarites to constrict (vasoconstriction) so they do not let blood flow so near the surface, and heat cannot be lost this way.  They also pull the hair upright in an attempt to trap a layer of air over the skin, preventing so much heat from escaping."]).
answer(number(6),part(a),subpart(0),[109,	1	,"the blood vessels close off the capillaries beneath the skin allowing heat to be kept away from the sweat glands reducing and increasing the bodies temperature.	"]).
answer(number(6),part(a),subpart(0),[110,	0	,"The supply of blood to the skin will be cut off so heat cannot escape.  Blood cells in the blood vessel will decrease in size to minimise heat loss.  They close off sweat gland to decrease evaporation to the surface."]).
answer(number(6),part(a),subpart(0),[111,	0	,"they pump less blood round the body to get us using less oxygen and cool down	"]).
answer(number(6),part(a),subpart(0),[112,	0	,"	The blood vessel contracts to trap heat in blood which has to move at high pressure to get through. This also creates kinetic heat energy.	"]).
answer(number(6),part(a),subpart(0),[113,	0	,"The blood vessels expand, sending blood particles to the surface of our skin.  This is because we have warm blood and it therefore will warm us up - which is why when we get hot, we go red	"]).
answer(number(6),part(a),subpart(0),[114,	3	,"The blood vessels reduce in width allowing less blood through.  This stops alot of blood from reaching the surface of the skin and being cooled by the air.	"]).
answer(number(6),part(a),subpart(0),[115,	0	,"	Blood vessels contain blood and "]).
answer(number(6),part(a),subpart(0),[116,	3	,"If it is cold vasoconstriction occurs. This is when the blood vessels near the skin constrict and so force the blood to flow through blood vessels further in the body. This cuts down on the amount of heat lost from the blood through the skin - meaning the body keeps the needed energy.	"]).
answer(number(6),part(a),subpart(0),[117,	0	,"You start to shiver therefore the muscles contract as though you were exercising the body therefore producing more heat, then you start sweating when shivering for a long period of time"]).
answer(number(6),part(a),subpart(0),[118,	2	,"They body detects that the body temperature is below normal and decreases the amount of blood that is sent to the blood vessels near the surface of the skin. This reduces heat loss as the heat in the blood would normaly radiate from the surface of the skin into the world around you.	"]).
answer(number(6),part(a),subpart(0),[119,	3	,"If the body is too cold the blood supply to the capilliery loop is cut off. This reduces the amount of blood flowing near the surface of the skin and the amount of heat lost by radiation is reduced."]).
answer(number(6),part(a),subpart(0),[120,	0	,"The blood vessels will increase the amount of blood going through the vessels to increase the temperature by (illegible) also it makes the hairs on Your arms stand up so the hairs cause a gap of air between you skin and the top of the hair.  This trapped air then insulated the body - keeping the body temperature normal."]).
answer(number(6),part(a),subpart(0),[121,	1	,"The blood vessels close up due to vascontriction. Muscles contract causing heating to occur, which passes along the blood vessels around the body. No blood is passed through the cappillaries, this reduces heat loss"]).
answer(number(6),part(a),subpart(0),[122,	2	,"If the body temperature falls below normal the blood vessels send less blood to the capillaries near the skins surface so less heat is lost. It also causes the hair to stand up and to trap more heat in between them. The vessels also serve the capillaries near the skin to move away, preventing heat loss."]).
answer(number(6),part(a),subpart(0),[123,	1	,"They get smaller, therefore decreasing the surface area of the blood cells with a smaller surface area there is less way the heat can get out."]).
answer(number(6),part(a),subpart(0),[124,	1	,"The blood vessels sink below the surface and cut off most the blood to the capilleries that are near the surface. this keeps more heat under the fat insulating layer and keeps the body warmer."]).
answer(number(6),part(a),subpart(0),[125,	3	,"The blood vessels contract (vascoconstrict) reducing heat loss from the surface of the skin by radiation.  By contracting they reduce the blood flow to the surface therefore prevent heat or energy loss from the surface."]).
answer(number(6),part(a),subpart(0),[126,	0	,"They speed up heart rate and the blood circulates around the blood capillary loop."]).
answer(number(6),part(a),subpart(0),[127,	0	,"The blood vessels reduce heat loss by moving deeper in to the arm so they are further from skin therefore less heat is losted. The blood vessels also carry glucose to the muscles so that they can warm the body by shivering."]).
answer(number(6),part(a),subpart(0),[128,	0	,"When the body temperature falls below normal the blood vessels move further away from the surface of the skin to stop the loss of heat through the skin."]).
answer(number(6),part(a),subpart(0),[129,	0	,"The blood vessels swell up to form a thicker wall and their is less blood flowing this is why cold people go blue."]).
answer(number(6),part(a),subpart(0),[130,	0	,"The blood vessels contract heating the blood and the excess blood is sent to the vital organs to keep them warm.  The blood vessels retract away from the skin and come in to be heated up.	"]).
answer(number(6),part(a),subpart(0),[131,	0	,"The blood vessels would seng a message to the sweat glands forcing them to close the pores.  The blood vessels then force the hair muscle to contract making the hairs stand up on end."]).
answer(number(6),part(a),subpart(0),[132,	2	,"If this happens, hairs on the arm surface stand up, which helps heat get between them. The sweat glands stop producing sweat, which would normally help cool us. Blood capillaries would 'close down' in order to decrease their surface areas so to not lose much heat from blood. This is called vascondilation.	"]).
answer(number(6),part(a),subpart(0),[133,	2	,"The blood vessels and capillaries in the skin get smaller or constrict blood flow so as to prevent heat from escaping from the blood this is called vasoconstriction."]).
answer(number(6),part(a),subpart(0),[134,	2	,"The capillaries vasoconstrict and divert blood lower in the skin often under the fat cells when one is cold. This reduces the amount of heat lost by radiation from the blood and helps in conserving heat energy."]).
answer(number(6),part(a),subpart(0),[135,	0	,"If your body temperature falls below normal. The blood vessels reduce heat loss by trapping all the heat within your body and using the fat layer to keep you warm. Therefore the blood vessels help to maintain normal body temperature."]).
answer(number(6),part(a),subpart(0),[136,	2	,"If the temperature falls below normal, the blood vessels will cut off blood supply to the skin therefore reducing the loss of heat. They also stop the sweat glands secreting sweat to keep the heat."]).
answer(number(6),part(a),subpart(0),[137,	1	,"If the temperature falls, the blood vessels don't let the blood up near the surface of the skin because the blood needs to keep warm while it is flowing, to keep all of our organs warm. The blood vessel gets smaller to create more friction as the blood passes through	"]).
answer(number(6),part(a),subpart(0),[138,	1	,"During cold weather blood travels deep under the skin so that it won't loose any heat. If it stays far away from the surface of the skin then it will stay warm, travel around your body, and generally keep your organs + whole body warm. It does thinks due to the blood capillary loop which allows it do decide how far away from the skin the blood flows.	"]).
answer(number(6),part(a),subpart(0),[139,	0	,"The sweat pores close so no heat can escape. The blood vessels make the hair stay on end so that the hairs can trap air. Therefore insulating the body.	"]).
answer(number(6),part(a),subpart(0),[140,	1	,"When body temperature falls, the sweat pore closes.  So no heat is lost, blood is stopped by the blood vessels from coming near the skin so no more heat is lost through the skin.	"]).
answer(number(6),part(a),subpart(0),[141,	3	,"Vascondriction - the diameter of the blood vessels becomes narrower - less surface area from which to lose heat. less blood flowing through to loose heat from.	"]).
answer(number(6),part(a),subpart(0),[142,	0	,"It doesn't allow much water to the sweat gland and makes the hair muscle contract making the hair stand on end	"]).
answer(number(6),part(a),subpart(0),[143,	1	,"Blood vessels have two different paths to follow. (in the skin). If the body is cold, blood will travel further down in the skin to reduce heat loss. There will also be a decrease in blood flow as the blood vessels constrict."]).
answer(number(6),part(a),subpart(0),[144,	0	,"When cold the blood vessel will supply more oxygen and energy to the hair erector muscle causing the hairs to stand on end. These hairs trap air close to the surface of the skin effectively insulating it."]).
answer(number(6),part(a),subpart(0),[145,	1	,"If the body temperature drops the blood vessels dilate so that they are further away from the skin and therefore minimises heat loss through the skin"]).
answer(number(6),part(a),subpart(0),[146,	0	,"It pumps the blood quicker and from the sweat gland it make sure no sweat is lost, this is because the sweat release heat.  The blood vessel go small so it is hard for the blood to travel this reduce heat lose. "]).
answer(number(6),part(a),subpart(0),[147,	0	,"The blood vessels sink away from the skin when you are cold so that more heat is kept. When you are hot you blood vessels rise to near the surface of your skin so you cool down."]).
answer(number(6),part(a),subpart(0),[148,	0	,"The blood vessels rise to the surface of the skin (making it red ) to increase the amount of heat at the surface and prevent anymore heat being lost through the skin."]).
answer(number(6),part(a),subpart(0),[149,	1	,"If the temperature falls below normal the blood vessels contact. This is called vasoconstriction. This helps to stop blood moving too fast around the body so that cells can absorb more oxygen from the blood to respirate more. This increased rate of respiration obviously increases energy output."]).
answer(number(6),part(a),subpart(0),[150,	0	,"Blood loop capilaries move down away from the skin this mean heat can't pass out as easily - through convection"]).
answer(number(6),part(a),subpart(0),[151,	0	,"If the temperature falls below normal, the blood will get warmer. Then, this warm blood is sent throughout the body to warm it up."]).
answer(number(6),part(a),subpart(0),[152,	0	,"They enlarge slightly	"]).
answer(number(6),part(a),subpart(0),[153,	0	,"As they pass through the brain it checks the temperature a message would then be sent to tell the fat layer to stop the blood vessels going to the surface of the skin to let heat escape."]).
answer(number(6),part(a),subpart(0),[154,	1	,"When the temperature falls below normal, the cappilleries constrict (vasoconstriction).  This reduces the heat loss, as the blood cappilleries are not so close to the surface of the skin.  This also increases the pressure at which the blood flows.	"]).
answer(number(6),part(a),subpart(0),[155,	0	,"Because they are only one cell thick and therefore heat transfer can occur more easily.  There are also parts of the blood vessel going all through the skin and so can therefore allow heat transfer all around the skin.	"]).
answer(number(6),part(a),subpart(0),[156,	0	,"The blood vessels expand to keep the body temperature high and keep you warm 	"]).
answer(number(6),part(a),subpart(0),[157,	3	,"They constrict allowing less blood to flow through the arteries  near the surface of the skin and so less heat is lost by radiation, this is called vasoconstriction. Also the hairs are made to stand up by the contraction of the erector muscles so heat is trapped between the hairs.	"]).
answer(number(6),part(a),subpart(0),[158,	1	,"Through the process of vasoconstriction they close the glands in the skin so that heat cannot escape through them	"]).
answer(number(6),part(a),subpart(0),[159,	1	,"The blood vessel constrict and go deep into the skin. less blood passes less energy or heat is evaporated body temperature remains constant	"]).
answer(number(6),part(a),subpart(0),[160,	0	,"the blood tries to cool down by going to the surface-.  Red skin. by letting the oxygen from the blood the blood will cool down causing us to cool down inturn.	"]).
answer(number(6),part(a),subpart(0),[161,	0	,"Because the temperature has decreased and the sweat pore is below normal.	"]).
answer(number(6),part(a),subpart(0),[162,	0	,"The body doesn't sweat, the hair stands on end and closes sweat and the blood vessels pump the blood faster and the fat layer swells up and increases to keep the warmth in.  It also reduces the surface area.	"]).
answer(number(6),part(a),subpart(0),[163,	0	,"If the body temperature falls, blood vessels cut of the blood supply to the blood capillary loops, so that the blood does not cool down, which in turn would cool the rest of the body.	"]).
answer(number(6),part(a),subpart(0),[164,	1	,"The blood vessels don't flow around the blood capillary loop. This way the blood doesn't go near the surface and become colder. The sweat gland doesn't produce sweat because of this and the hair becomes erect to trap air, which acts as an insulator and prevents heat loss.	"]).
answer(number(6),part(a),subpart(0),[165,	0	,"The blood vessels prevent flow of the blood to the capillary loops (which cools blood) and keeps it below the layer of fat which does not allow heat to be lost to the outside air. The fat layer prevents heat loss due to radiation.	"]).
answer(number(6),part(a),subpart(0),[166,	0	,"The blood vessels dilate When the body needs to prevent heat loss.  It dilates to prevent heat being lost through the skin as radiation and keeps the heart in the centre of the body.  If you are too hot the vessels expand losing heat through the skin this process is known as homeostasis	"]).
answer(number(6),part(a),subpart(0),[167,	1	,"The blood vessel stops a large ammount of blood going to the blood capillary and sweat gland.  This prents the presonne from sweating and loosing heat. 	"]).
answer(number(6),part(a),subpart(0),[168,	0	,"The blood starts to circulate more quicker in the blood vessels which then goes up the blood capillars as it circulates faster the blood starts to warm up as more energy is transfered out of the blood cells, which our skin sensors pick up in result we feel warmer	"]).
answer(number(6),part(a),subpart(0),[169,	0	,"The blood vessels have a good blood supply which they increase and absorb more oxygen from the cells to carry around to keep the heat energy in and pass more oxygen to the fat layer to make it a better insulater instruct the sweat pores to keep the energy in and make the hair stand on end to prevent water loss.	"]).
answer(number(6),part(a),subpart(0),[170,	1	,"To reduce heat loss the blood vessels constrict i.e. vasoconstriction.  This closes the sweat pore so that excess heat is not lost through respiration and the hair stands on end activated by hair muscle so that a layer of air is trapped between the skin and hair to prevent excess heat loss and to warm up the body.  	"]).
answer(number(6),part(a),subpart(0),[171,	2	,"The blood vessels contract reducing their surface area so that heat will therefore not be able to escape. This also prevents the blood vessels from being near the surface of the skin which would lead to heat loss. The opposite happens if the body temp rises above normal. The fatty layer also helps protect the blood vessels as they contract	"]).
answer(number(6),part(a),subpart(0),[172,	2	,"When we are cold, the blood vessels shut off meaning that the amount of heat loss is reduced. This is called vasoconstriction. By doing so, are body keeps in necessary heat which acts as an insulator.	"]).
answer(number(6),part(a),subpart(0),[173,	2	,"If the body temperature falls below normal, blood vessels do not flow up to the surface of the skin - this is known as VASOCONSTRICTION, this means that body heat is not lost by convection."]).
answer(number(6),part(a),subpart(0),[174,	1	,"The blood vessels below the fatty layer close off to reduce heat being transferred to the air to reduce heat loss.  It also does not let out sweat and makes the hairs stand on end to trap heat."]).
answer(number(6),part(a),subpart(0),[175,	1	,"If the body temperature calls to below normal then blood supply to the blood capillary loop is constricted (vasoconstriction).  This also stops the sweat gland from functioning and prevents the hair from lying flat which stops heat loss and maintains a suitable level of water (no sweat)"]).
answer(number(6),part(a),subpart(0),[176,	0	,"by radiating heat the blood vessels can reduce heat loss. They fall to the further away from the skin when is is cold to reduce heat loss.  Resulting in the pale Colour a human's skin goes in the cold.	"]).
answer(number(6),part(a),subpart(0),[177,	1	,"If the body temperature falls below normal, the blood vessels close off the blood capillary loop. This helps to retain heat, as the further warm blood is from the skin, the less heat will conduct out and be lost from the body.	"]).
answer(number(6),part(a),subpart(0),[178,noanswer]).
answer(number(6),part(a),subpart(0),[179,	0	,"If the nerves at the skin detect that it has got cold the blood vessels try to reduce heat loss by not flowing up by the edge of the skin because then the inner body temperature stays warm.	"]).
answer(number(6),part(a),subpart(0),[180,	2	,"When the bodys temp drops below normal the change is detected (by the hypothalamus). Blood is prevented from flowing near to the surface of the skin in vasoconstriction. This prevents any excess heat being lost. The blood supply to the skin is shut off.  	"]).
answer(number(6),part(a),subpart(0),[181,noanswer]).
answer(number(6),part(a),subpart(0),[182,	0	,"If the body temperature falls below normal the blood vessels take in more oxygen and glucose from the blood so that it could be distributed evenly in the skin. They also stop the sweat glands producing sweat and they also make hair can trap air and reduce heat loss	"]).
answer(number(6),part(a),subpart(0),[183,noanswer]).
answer(number(6),part(a),subpart(0),[184,	1	,"The blood vessels reduce heat loss by shutting of the blood supply to the skin if the body temp falls below normal.	"]).
answer(number(6),part(a),subpart(0),[185,	0	,"It will send a pulse through the blood capillary which goes to the sweat gland which produces sweat which goes through the sweat pore to mantain a steady temperature.	"]).
answer(number(6),part(a),subpart(0),[186,	1	,"It reduces the flow of your blood around back to its original speed which calms you down and relaxes you. Once you are released your body temperature drops back down to its normal rate	"]).
answer(number(6),part(a),subpart(0),[187,	0	,"It will make the hair stand up from shoot to warm you up. High blood pressure along blood vessel. No sweat, you will shiver if you are cold.	"]).
answer(number(6),part(a),subpart(0),[188,	1	,"They get smaller so that less blood goes to the surface where blood heat is lost.  The heat is kept nearer organs to keep them warm and working at the optimum temperature 37 ºC.	"]).
answer(number(6),part(a),subpart(0),[189,	2	,"If body temperature falls below normal the brain detects that the blood is cooler than normal it then sends a message to the skin to make the blood capillaries contract, so less heat is lost from the blood through the skin surface. The hair muscles contract so the hairs stand up to trap a layer of still air. Sweat glands stop producing sweat.	"]).
answer(number(6),part(a),subpart(0),[190,	0	,"More blood is sent to the blood vessels which move toward the skin as they expand and the warmth of the blood keeps the area warm and temperature up.	"]).
answer(number(6),part(a),subpart(0),[191,	3	,"Vasoconstruction takes place ie the arteries contract, hence the lumen becomes narrower allowing less blood to flow through. Therefore less neoutis lost from the body through radiation. On the surface over skin is therefore pale in cold temperatures.	"]).
answer(number(6),part(a),subpart(0),[192,	0	,"The blood vessels helps reduce heat loss by retaining the heat inside the body and not letting it escape. The blood vessels, helps to cool the body and prevent sweat being produced.	"]).
answer(number(6),part(a),subpart(0),[193,	0	,"The blood vessels act as an insulator.  They reduce heat loss by not releasing fluid into the sweat gland, which if was done so, would travel through the sweat duct and evaporate causing body temperatures to cool.  They would also reduce heat loss by causing the hairs to relax and lay on the arm, also acting as an insulator. 	"]).
answer(number(6),part(a),subpart(0),[194,	0	,"The blood vessels shut off the blood capillary loop, this reduces the amount of heat loss as the heat can no longer diffuse into the air.	"]).
answer(number(6),part(a),subpart(0),[195,	0	,"the blood vessels sends a chemical to the sweat gland and produces sweat.  This sweat cools the body down and evaporates from the body.	"]).
answer(number(6),part(a),subpart(0),[196,	0	,"the blood vessels expand causing the hair muscle to contract and the blood capillary loop to carry blood to the skin at a faster rate.  The skin rises and the hairs trap air. 	"]).
answer(number(6),part(a),subpart(0),[197,	2	,"Less blood is transported to the skin so it isn't lost through the skin.  It keeps the heat in for the rest of the body. 	"]).
answer(number(6),part(a),subpart(0),[198,	0	,"It sends blood to the surface of the skin so it will cool down much quick	"]).
answer(number(6),part(a),subpart(0),[199,	0	,"The blood vessels send blood to the blood capillary loop which stands all the hairs up straight. This means then that the hairs can trap any heat.	"]).
answer(number(6),part(a),subpart(0),[200,	3	,"If the body temperature falls below normal the blood vessels narrow and carry less blood to the surface of the skin. This means less heat is lost from the blood through the skin.	"]).
answer(number(6),part(a),subpart(0),[201,	0	,"blood will move through the capillary loop. Because the blood	"]).
answer(number(6),part(a),subpart(0),[202,	1	,"When body temperature falls below normal, the flow of blood steps to the particular area, to stop the sweat pore producing any sweat.  The blood vessels carry oxygen to where its needed, eg hair muscle.  The blood vessels carry nervous signals to the hair and sweat gland. 	"]).
answer(number(6),part(a),subpart(0),[203,	0	,"The blood vessels carry oxygenated blood which is passed on to the fat layer which is a heat insulator.	"]).
