:- multifile answer/4.

answer(number(6),part(c),subpart(0),[1,	1	,"His body realises this temperature change by receptors in the skin.  It realises its too hot and so vasodilation takes place, hairs lie flat and the body sweats.  This means blood flow to the skin is increased, to lose heat through the skin, the sweat evaporates, taking heat energy with it and so cooling it down and the hours are meant to reduce air pockets of warmth lowering your metabolism"]).
answer(number(6),part(c),subpart(0),[2,	1	,"senses around his body detect what the temperature is a hyrosthalumos (I think that's the right word) triggers a reaction because the body needs to keep at the same conditions (homeostasus) so his body triggers him to sweat, which evaporates off his skin cooling it down."]).
answer(number(6),part(c),subpart(0),[3,	2	,"Thermeostasis allows David to feel in his brain that he is too hot and sends chemical messenges via the nervous system to make sure that is changed so a maintenence of a constant internal environment is withheld. (Homeostasis ! ) Using this the temperature is lowered. e.g the hairs on the skin lie flat, sweat is produced and the blood supply is released to the skin all allowing heat to escape.(vasodilation !)"]).
answer(number(6),part(c),subpart(0),[4,	0	,"David would be breathing heavily and sweating alot more, the blood would also be pumping alot harder around his body. His body would detect it by the excess sweat he is producing, the body attempts to keep up with David by pumping more blood around the body and getting rid of more fat."]).
answer(number(6),part(c),subpart(0),[5,	1	,"The temperature change is noted by his brain via the nervous system. His body tries to return back to normal temperature by sweating which helps take heat away from his skin by convection blood capillaries become full and move close to the surface and hairs move so that they lie flat on the surface on the skin."]).
answer(number(6),part(c),subpart(0),[6,	1	,"Davids body detects temperature change several way. One is as he sweats he looks wate so ADH is produced to absorb more water from area.  Davids Body then starts to sweat & his hairs get as flat to his body his cappilleries vasodilte & blood flow close to his skin. As his sweat evaporates heat energy from surrounding area in (illegible) too."]).
answer(number(6),part(c),subpart(0),[7,	1	,"A lot of sweat is created and there is alot of water in our sweat. Davids body is oozing alot of fluid and water which helps cool him down. The control mechanism produce fluid and make his body rest creating more fluid in the body"]).
answer(number(6),part(c),subpart(0),[8,	1	,"His body begins to vasodilate. David would begin to sweat cooling his skin. Blood supply to the skin would also help call him down. The hairs on Davids body would lie flat. His cheeks would redden as the blood supply increases in the skin in his face trying to release heat."]).
answer(number(6),part(c),subpart(0),[9,	0	,"He sweats which releases excess water and trys to slow down his heart beat which both helps cool him down. Slowing down his breathing rate helps to control the heating in his body as it slows down the hearts beating."]).
answer(number(6),part(c),subpart(0),[10,	1	,"The skin can detect a change in body temperature.  When it rises above normal it causes the process, vasodilation.  This relaxes the hair muscles which cause the hairs to lay flat, the sweat pores open to let sweat evaporate out and away from the body and the blood flows nearer to the surface of the skin to allow maximum heat loss to enable him to cool down."]).
answer(number(6),part(c),subpart(0),[11,noanswer]).
answer(number(6),part(c),subpart(0),[12,noanswer]).
answer(number(6),part(c),subpart(0),[13,	3	,"David's blood temperature would rise and his brain would notice this, then he would try to return to his normal temperature by sweating, the sweat then evaporates from his skin. It needs heat to do this and it uses up the excess body heat leaving him cooler."]).
answer(number(6),part(c),subpart(0),[14,	2	,"The part of your brain which detects temperature changes is called the hypothalamus.  When he gets hot, the sensory nurons in the skin send a message to the brain.  To return his temperature back to normal, the hair muscles cause hairs on arms and legs to flatten, so they are not trapping air.  The sweat gland also produces sweat which is secreted through the pores on your body.  The sweat then evaporates from the skin making you cool down.	"]).
answer(number(6),part(c),subpart(0),[15,	0	,"The let some of the heat out by letting him sweat"]).
answer(number(6),part(c),subpart(0),[16,	2	,"A detection in body temperature is made by the brain. Vasodialation occurs, and sweat is lost through the sweat pore in the skin. This causes evaporation of the sweat from the skin to happen, which in effect cools the body down. Blood flows quicker throughout the body."]).
answer(number(6),part(c),subpart(0),[17,	1	,"When david gets hot his temperature receptors feel the change in temperature they has send a message to the brain via the nerves the brain then send a message back telling the blood vessels to open up, the sweat glands to release water and his hair mussels to relax.  Opening the blood vessels helps to take the temperature from the skin and even it out through the body the sweats lose water to the surface of the skin - this water then takes the warmth from the skin to evaporate off.  When the hair mussels relax this makes his hair lie flat preventing air from being trapped, so it is not heating up the body."]).
answer(number(6),part(c),subpart(0),[18,	1	,"The body is Constantly using feedback to Control homeostasis.  When the Sense organs (here skin) detect something wrong an electrical impulse is sent down the Sensory neurone.  This Crosses the Synapx (break between neurones) using a Chemical message.  This reaches the Central nervous System (brain & spine).  Then the message is Sent back down the motor neurone  - electrical impulse.  The motor neurone then sparkes a reaction in the muscles or blood suplie.  Then the blood will come to the surface (vasodialation) and he will turn red, losing heat.  The Sweat gland will release sweat, the evaporation will cool him down "]).
answer(number(6),part(c),subpart(0),[19,	1	,"Sensory receptor cell in the skin sense the increase in temperature. The impulse travels along the sensory neurones to the central nerve system, where the brain puts control mechanisms into action. David sweats, to lose heat energy by evaporation. Vaso-dilation occurs, increasing his blood is cooled by the circulating near the skin. The hair erector muscle relaxes, so that the hair doesn't stand on end trapping insulating air which would warm David up."]).
answer(number(6),part(c),subpart(0),[20,	2	,"As blood gets pumped to the back, it not only supplies it with energy but it is checked to make sure it is at the right temperature by the brain. If the blood is above it's normal temperature it means the body is over it's normal temperature, therefore the brain tells the body to sweat. This is the bodies way of trying to cool down.	"]).
answer(number(6),part(c),subpart(0),[21,	0	,"His skin detects a change in temperature and in this case its risen. This causes his hairs to lie flat and his sweat gland to produce sweat to try and cool him down. Also the blood doesn't flow in the capilaries just under the skins surface. These things all try to cool him down and this is called vasoconstriction."]).
answer(number(6),part(c),subpart(0),[22,	2	,"In the brain, the Hypothalamus detects that the body is warmer so it sends messages down the nerves to make the hair muscles pull the hairs on end. It also makes the sweat glands secrete sweat to try and rid of excess heat by evaporation."]).
answer(number(6),part(c),subpart(0),[23,	0	,"Our skin controls our body temperature so to cool us down our hairs lie flat on our skin our bodies produces sweat to cool us down"]).
answer(number(6),part(c),subpart(0),[24,	1	,"Nerves in Davids body will tell his brain that he is getting too hot. His body will then try to get his temperature back to normal. His blood vessels will flow nearer to the syringe to release heat. His hairs will go flat to his arm so they dont trap warm air. He will begin to sweat and as the sweat evaporates on his skin this will cool his skin down."]).
answer(number(6),part(c),subpart(0),[25,	0	,"david detects the heat increase as his hair lie flat against the skin and he feels sweaty. His body sweats so that he can get rid of any hot liquids and the blood vessels become larger to try and stop the heart over heating itself"]).
answer(number(6),part(c),subpart(0),[26,	0	,"His body detects this temperature change through sensory nerves.  His body tries to return his temperature to normal by causing him to sweat, to cool his skin down, and moving blood vessels closer to the skin surface to lose heat more."]).
answer(number(6),part(c),subpart(0),[27,	1	,"The body detects temperature change when blood vessels open allowing blood goe to the skin. This is why you appear red when hot and giving of heat. An attempt to return his temperature back to normal water is released through the sweat pores allowing the body to cool itself down through evaporation. The body detects temperature change by the body temperature rising."]).
answer(number(6),part(c),subpart(0),[28,	0	,"Davids body detects his temperature change through his nervous system. His body tries to return him to his normal temperature, by bringing the blood vessel to the surface of his skin to cool him down by moving the hair on his body to upright, so no hot air is stuck underneath it."]).
answer(number(6),part(c),subpart(0),[29,	0	,"His body detects this change, and then he is able to loose some of this - sweating"]).
answer(number(6),part(c),subpart(0),[30,	1	,"His body's control mechanisms attempt to return the temperature back to normal by producing more sweat to lose heat, makes the hairs on the body lie flat to the skin and less blood is pumped to this area. His body detects this temperature change by the nervous system detecting the increase and sending a message to the brain to make the changes above."]).
answer(number(6),part(c),subpart(0),[31,	0	,"His blood vessels will rise to the surface of his skin and his hairs will go flat to his skin stopping air from being trapped. And he will also produce sweat to cool his body temperature."]).
answer(number(6),part(c),subpart(0),[32,	2	,"The body detects temperature change as blood passes by the brain. The brain then decides to either make you warmer or in David's case cooler. The brain will send messages along nerves telling certain parts of the body to sweat in an attempt to cool us down"]).
answer(number(6),part(c),subpart(0),[33,	0	,"Davids body detects that he is too hot by his nervous system.  The message is transmitted to the brain and the body recognises that it has to do something to regulate the temperature. One way David's body may cool him down is by releasing sweat.  The sweat is released through his sweat pores via sweat glands.  Sweating causes a very fast form of heat release as the heat is released as the sweat."]).
answer(number(6),part(c),subpart(0),[34,	1	,"The body detects the change in temperature through a nerve.  A message is sent to the brain saying the body needs to be cooled down.  This then sends a message to the sweat gland and tells it to let sweat out of the pores to help cool the body.  Also blood vessles then run nearer to the skins surface to help cool his body."]).
answer(number(6),part(c),subpart(0),[35,	1	,"Nerves detect the change in temperature change and send a message to the brain. The brain will then send a message telling the body to sweat so heat energy is lost through evaporation, to relax all hair muscles and to keep the blood capillary loop flowing so as much heat can be lost to retain to normal body temperature"]).
answer(number(6),part(c),subpart(0),[36,	0	,"Davids body senses that there is a temperature change using sensitive nerves and signals. The body attempts to return his temp by producing sweat through the sweat glands and out of the sweat pores."]).
answer(number(6),part(c),subpart(0),[37,	3	,"The hypothalamus in the brain detects the temperature change and sends chemical messages to the skin.  The capillaries near the surface of the skin dilate, more heat can be lost by conduction and radiation.  The sweat glands will secrete sweat. The sweat will evaporate transferring heat energy away from the skin."]).
answer(number(6),part(c),subpart(0),[38,	2	,"The brain detects the change in temperature of the body through sensory nodes which are stimulated by change in temperature.  A signal is sent via the sensory neurones to the brain (spinal chord aswell) where another signal is sent via motor neurons to effectors (muscles) where a response is triggered.  This includes (if the body is too hot), vasodilation, sweating and skin hair lying flat against the skin."]).
answer(number(6),part(c),subpart(0),[39,	0	,"Davids body detects the temperature change as the blood vessels expand therefore letting more blood to the heart making it beat faster and also because the sweat glands are producing sweat. sweating imparticular this cools David down by letting off excess water and cooling the skin, which in turn cools the blood vessels which stops the heart beating so fast and returns his temperature back to normal"]).
answer(number(6),part(c),subpart(0),[40,	2	,"As his body rises, the hypothalamus detects the temperature change. It sends messages for the following in the blood.  the extra heat can be lost through sweating as water on the skin evaporates, this carries heat energy away.  The blood vessels near the skin allow blood to flow through losing heat energy that way.  all hairs lay flat if they were previously erect). These all ensure a constant enviroment remains (homeostasis)"]).
answer(number(6),part(c),subpart(0),[41,	0	,"The Hair nerves detect an increase in temperature, which sends a chemical to the brain.  The control mechanisms, will create water which will take the heat and absorb it."]).
answer(number(6),part(c),subpart(0),[42,	1	,"Davids body detects the heat due to his hairs which start vibrating alerting his sensory neurones which transmit the reaction to his brain via his spinal chord. To return his temperature the blood vessels pump blood through the blood capillary loop which evaporarates the sweat in his gland which leak out of his sweat pore. The capillary loop loses heat also by pumping so close to the skin"]).
answer(number(6),part(c),subpart(0),[43,	2	,"David's hypothalamus detects the rise in his body temperature in the blood. The hypothalamus then reacts in a number of ways. Firstly, it sends a message to the brain to make the muscles shiver. It also tells the brain to make the hair muscles in the skin contract, to trap heat under the erect hairs. It also sends a message to the blood vessels to open up the blood supply to the skin, to cool the blood down. In opening the blood supply to the skin, the sweat glands also become active, and produce sweat to cool the body down.	"]).
answer(number(6),part(c),subpart(0),[44,	3	,"The hypothalymus detects that the blood has higher temperature than normal, David sweats to increase evaporation which cools him and also increases the blood supply to the skin in an attempt to loose heat from it"]).
answer(number(6),part(c),subpart(0),[45,	0	,"A message is sent to his brain via the nerous system informing it that the body temperature has changed.  The brain then sends a message to his body's control mechanisms which then attempts to return his temperature back to normal by making him sweat and allowing the capillaries to expand letting out heat.  The hairs then lye flat trapping less air."]).
answer(number(6),part(c),subpart(0),[46,	0	,"Hairs lie flat on arm - to prevent insulation.  Blood flows close to surface of skin to ensure heat loss.  Sweat poors open to allow water to carry excess heat away.  The body increases breathing to allow water vapour to transport excess heat out of body."]).
answer(number(6),part(c),subpart(0),[47,	0	,"A stimulus is sent to the thermoregulator which detects the temperature is too low it therefore acts by sending impulses to varies parts to begin the cooling down. The sweat glands are activated , hairs relax and the cappilaries erect to make maxiumum heat loss and to cool the body back down by blood at surface."]).
answer(number(6),part(c),subpart(0),[48,	0	,"the bodys temperature gland detects the temperature change. The sweat glands then start to produce sweat and then the sweat goes on to the skin out of the sweat pore and makes the surface of the skin wet then when David is turning around and wind passes his skin the sweat cools him down and makes the skin also cool down which in time brings his body temperature down to normal again."]).
answer(number(6),part(c),subpart(0),[49,	2	,"The temperature change is detected by the hypothalamus, and this causes a number of reactions to take place:.  His blood capillaries near the surface of his skin dilate, allowing more blood through to lose heat, his hairs lie flat against his skin  so they don't trap air (an insulator) and his sweat glands secrete sweat which evaporates, drawing away heat energy	"]).
answer(number(6),part(c),subpart(0),[50,	1	,"He detects the temperature change because he will become hotter than normal, and may go red in the face.  His body attempts to return his temperature back to normal by making him sweat (when this evaporates it takes hot away from the skin) and making his hairs lie flat against the skin."]).
answer(number(6),part(c),subpart(0),[51,	0	,"Messages are sent by your nerves to your brain to tell you of a rise in temperature.  Your body will attempt to slow your blood down and will make you sweat to also reduce heat.  Your blood vessels will move further apart to allow heat loss."]).
answer(number(6),part(c),subpart(0),[52,	1	,"The change in temperature is detected by a process called homeostasis. An impulse is then sent from the brain to the sweat glands and sweat production increases, to cool the person. The hair muscle contracts so that the hair stays closer to the skin."]).
answer(number(6),part(c),subpart(0),[53,	0	,"David is using up energy so his heart starts to beat faster increasing the rate at which the blood is being pumped around the body, he starts to sweat and the sweat is detected by the temperature of his body. He stops playing football and his heart rate pumps slower."]).
answer(number(6),part(c),subpart(0),[54,	1	,"As David's temperature rises, the body's muscles heat, this change is detected by the brain sweat glands produce sweat which is released by the body through the skin, this action is caused by a message sent to the brain. The release of these fluids instantly causes the body's temperature to drop."]).
answer(number(6),part(c),subpart(0),[55,	0	,"the skin starts to get off, so the blood pumps more causing all the muscles to get tired and start to sweat through the sweat pores all over the body."]).
answer(number(6),part(c),subpart(0),[56,	0	,"His body temperature returns back to normal by the process of sweating.  This releases water through the pores of the skin."]).
answer(number(6),part(c),subpart(0),[57,	0	,"Davids body detects the change and sends impulses around his body telling his body that he is cold so they send hormones around his body which make him sweat and heat up.  He will then cool down and be back to normal."]).
answer(number(6),part(c),subpart(0),[58,	1	,"His body detects the change in temperature by seeing that the enzymes in his body are working at a faster rate so in David's blood vessel to cool him down it sends water to the sweat glands which send the water to the sweat pore where it is evaporated from the skin which cools him down."]).
answer(number(6),part(c),subpart(0),[59,	0	,"The body detects a temperature change as the breathing becomes irregular and the heart beat is speeded up, the body will then allow water out of the sweat pores and the hairs on the body will smooth down in order to allow any heat out of the body."]).
answer(number(6),part(c),subpart(0),[60,	2	,"The hypothalamus detects a change in the body's temperature.  This then sends a message to the skin which will adjust it.  It does this by excreting sweat from the sweat glands, as the sweat evaporates the body is cooled.  The erector muscles also relax allowing the hair to lie flat, they are no longer trappin a layer of warm air close to the skin and so the body is cooled by this absence of insulation. "]).
answer(number(6),part(c),subpart(0),[61,	0	,"David's body would begin to sweat to cool the body back down.  The sweat gland produce water out of the sweat pores which then cool down the surface of the skin."]).
answer(number(6),part(c),subpart(0),[62,	0	,"The body detects the temperature change through the relay neurone motor neurone etc to the effector which is the control mechanism to make sweat so he can cool down.	"]).
answer(number(6),part(c),subpart(0),[63,	1	,"David detects this temperature change because he can feel his skin becoming hot & also he sweats which is a sign of hotness he uses his senses in both of these.  his bodys control mechanisms attempt to return his temperature back to normal by sweating the sweat lying on the skin evaporates in the air & takes the heat with it."]).
answer(number(6),part(c),subpart(0),[64,	2	,"The hypothalamus detects the change in the temperature so sends a nervous impulse to the skin.  The hairs on the skin then lie flat to increase the amount of heat lost.  The skin also starts to produce sweat in order to cool the body down.  Blood supply to the skin is increased to lose heat and this is called vasodilation."]).
answer(number(6),part(c),subpart(0),[65,	0	,"The sweat gland releases water through the sweat pore the body to cool down.  The blood vessels contract themselves higher helping to cool the body.  Hairs place themselves against the skin reducing heat being collected.  And the blood capillary loop sends itself higher up the skin giving oxygen and food to the skin tissue thus reducing heat"]).
answer(number(6),part(c),subpart(0),[66,	3	,"Thermoreceptors in the brain detect the raised temperature of the blood messages are sent via nerve impulses to the effector region which is the skin the messages are received by the sweat gland to release sweat to cool off the body.	"]).
answer(number(6),part(c),subpart(0),[67,	1	,"Davids body detects the temperature change by the nerves which are close to the skin. The nerves then send electrical impulses to the brain to tell it, it needs to cool down. The sweat glands then produce sweat (to cool down the body), hairs lie flat and blood travels through the capillaries close to the surface for maximum heat loss. (The sweat is gotten rid of through the sweat pore).  This is called Vasodilation."]).
answer(number(6),part(c),subpart(0),[68,	0	,"When he's hot the hairs lie flat sweat is produced and the blood supply is turned on again to get rid of as much heat as possible through the skin all this is called vascodilation > does this to make body temperature return to normal.  When he's too cold the hairs errect no sweat is produced the blood supply is turned off so that as much heat as possible is kept in the body as possible process called vasoconstriction. "]).
answer(number(6),part(c),subpart(0),[69,	2	,"This happens from your muscles are used and heat up.  Your brain detects this and you sweat which gets rid of some of the heart.  Your blood vessels also vasodilate.  This makes the bigger and closer to the surface.  It increases the surface are (means more heat loss).	"]).
answer(number(6),part(c),subpart(0),[70,	0	,"Davids body will try and return its temperature back to normal by sweating."]).
answer(number(6),part(c),subpart(0),[71,	1	,"David is using more oxygen than normal as he is playing football. This makes the blood pump around the body much quicker. The body detects this and attempts to return his temperature to normal by releasing more liquid through the sweat gland to the pores. Also David's hairs will lie straight to give as little covering as possible.	"]).
answer(number(6),part(c),subpart(0),[72,	2	,"The change in temperature is detected by the brain after heat is produced from aerobic respiration. This causes sweat to be produced by sweat glands in the skin when this liquid evaporates it takes heat away from the body, cooling the body. Blood vessels will dilate (widen) to lose as much heat from the blood as possible"]).
answer(number(6),part(c),subpart(0),[73,	0	,"His brain recieves messages, as a reaction chemicals are released with instructions, these go to your sweat glands - sweats released and this cools your skin down. Hairs lie dormaint to release heat from your skin. Blood vessels dialate to the skins surface in order to lose warmth in your blood."]).
answer(number(6),part(c),subpart(0),[74,	1	,"Hairs lie flat: sweat is produced to cool you down.  The blood supply off the skin opens. This is called vasodilation."]).
answer(number(6),part(c),subpart(0),[75,	0	,"David will start to breathe heavier and therefore take in more oxygen and carbon dioxide, which will then hopefully make David go back up to his normal breathing rate, then his temperature of his body will go back to normal, slowly."]).
answer(number(6),part(c),subpart(0),[76,	0	,"This body detects this by when the hart beats faster and the eynalin is puping faster his body control this by sweeting."]).
answer(number(6),part(c),subpart(0),[77,	2	,"The body detects this temperature change through the skins nerves which then sends messages back to the brain.  His body controls the heat through the sweat glands making sweat that goes out of the sweat pore.  Also the blood vessels dialate."]).
answer(number(6),part(c),subpart(0),[78,	3	,"the temperature of the blood is monitored so when, it gets above normal the brain tells the body to react. It does so by sweating which is the evaporation of water on the skin which takes away the heat. It lays hair flat on the skin to reduce the 'fur' on our bodies and the blood vessels vascoconstrict."]).
answer(number(6),part(c),subpart(0),[79,	1	,"The brain notify that the heart is beating quicker and the lungs are working faster. It sends a message to the target area and then (illegible) things are done. Hairs on the skin are flat. The sweat glands produce sweat to cool the surface of her skin. Also the blood vessels (illegible) and allow the blood's heat to be lost at the surface"]).
answer(number(6),part(c),subpart(0),[80,	0	,"It detects the temperature change through the nerves, which sense the skin temperature increasing causeing messages to be send to the brain and the brain reads by sending signals to for example a sweat pore to produce sweat which is a liquid and when in contact with the air will cool which will cool down the body also."]).
answer(number(6),part(c),subpart(0),[81,	2	,"The hypothalamus detects that David is hot by knowing this it works to reduce water loss so it adds more ADH so David loses less water.  In his arms the sweat gland is active making David release sweat.  Also the hairs on his arms lay flat and blood is pumped through the blood capillary loop so that the extra heat is lost through the skin."]).
answer(number(6),part(c),subpart(0),[82,	3	,"There is a region in the brain called the hypothalamus that detects a change in temperature. For our bodies to keep working it needs to be at a contant temperature. This is called homeostasis. This is when a factor like temperature is changed so the brain tells the body to start sweating. Sweat gets evaporated away from our body and that is how we lose heat. Our body keeps doing this until the body temperature returns to it's normal level.  stimulus > receptor > neurou > effector > responce	"]).
answer(number(6),part(c),subpart(0),[83,	2	,"The change in the temperature is sensed by the hypothalamus in the brain. The body lowers the hairs on the skin to stop the insulation and by vasodilation the blood level rises above the fat layer thus less insulation. The body also sweats; heat is conducted to the sweat which evaporates - taking the heat with it."]).
answer(number(6),part(c),subpart(0),[84,	0	,"Oxygen is being used up much more quickly from the cells when he is exercising and must be replaced. The heart pumps blood more quickly round the body to his muscles which need the oxygen. Once the oxygen has been replaced the body temperature will return to normal. The body has also lost water through the sweat glands and this must also be replaced by the blood.	"]).
answer(number(6),part(c),subpart(0),[85,noanswer]).
answer(number(6),part(c),subpart(0),[86,	2	,"A brain signal is required telling the brain the body is too hot, the brain then sends a signal to the different parts of the body to react to lower temperatures. The sweet glands produse more sweet this sweet when reaches the skin evaporates the blood vessels come to the surface of the skin so they cool down"]).
answer(number(6),part(c),subpart(0),[87,	2	,"He produces more sweat which will evaporate and therefore help him cool down. The hairs on his arms will lie flat and the blood supply will flow next to his skin. The heat change has been detected by his hypothalamus which sends messages to the pituitary gland which then sends the message to the necessary area. The process of David trying to cool down is known as vasodilation."]).
answer(number(6),part(c),subpart(0),[88,	0	,"David sweats out to produce a cool layer on the skin, and extract the heat from within, to the sweat which is then evaporated out. Davids body detects this by the nerves in his skin sending a message in the skin which then send a message back to the sweat gland to give off sweat."]).
answer(number(6),part(c),subpart(0),[89,	0	,"The body detects the changes by the receptors in the skin. The sweat pores open and release sweat and the blood vessels flow towards the skin so that heat is lost from the blood."]).
answer(number(6),part(c),subpart(0),[90,	0	,"When David overheats his brain sends messages telling the sweat glands to produce sweat, the hairs on his skin to lie flat and for the blood vessels near his skin to get larger so more heat is lost through the skin."]).
answer(number(6),part(c),subpart(0),[91,	1	,"David's blood would be going faster through his veins and his breathing would be quicker, this causes his temperature to rise. To cool his body down again he begins to sweat. The energy needed for the swet to evaporate comes from David, this cools him down. The blood capillary loop opens so blood gets to the skin surface. The hairs lay flat so no air is trapped to insulate him. This is all called thermoregulation"]).
answer(number(6),part(c),subpart(0),[92,	3	,"Blood travels all around the body.  When the blood heats up even slightly, this is detected in the brain.  The brain can then deal with the task of lowering the body temperature.  Chemical messages are sent back down with the blood for the hair muscle to make the hair flat so no air is trapped and also for the sweat gland to start secreating sweat which evaporates and cools the body down.  The top blood vessels in the blood capillary loop will open up so as much blood can pass through as possible."]).
answer(number(6),part(c),subpart(0),[93,	2	,"The hypothalamus detects this change and therefore sends a signal for his body to thermoregulate. This enables his blood vessels to vasodilate which enables heat to be lost and also the sweat glands become active which produce sweat and as the sweat evaporates the body can cool down. Hair lies flat to enable more heat to be lost.	"]).
answer(number(6),part(c),subpart(0),[94,	0	,"his blood vessels move closer to the surface so they can cool down, he will also sweat to lose some heat."]).
answer(number(6),part(c),subpart(0),[95,	1	,"The (illegible) centre detects this rise as a result of negative feedback of blood passing through the brain.  Hormones are released to the target organs to bring the body temp back to 37 ºC.  The blood capillaries vasoconstrict, his body hairs lie flat and sweat is released to the skin to cause heat loss through evaporation."]).
answer(number(6),part(c),subpart(0),[96,	1	,"Hypothalamus detects it.  Sweats to cool down vessels dilate  so they can cool off near the skin."]).
answer(number(6),part(c),subpart(0),[97,	0	,"The hair moves down which is controlled by a muscle. This then sends a message to the brain which tells the body to cool down. To do this the body releases heat through water, in the form of sweat and it and blood pressure is decreased."]).
answer(number(6),part(c),subpart(0),[98,	0	,"The hypothalamus located in davids head receives signals from nerves reporting the change in temperature, it then sends signals to the skin which then makes the hairs on the surface lie flat and the glands to start sweating.  The sweat then evaporates which means the sweat molecules absorb energy from the skins surface and leave taking the energy with them, thus cooling the body down."]).
answer(number(6),part(c),subpart(0),[99,	1	,"The hypothalamus detects the increase in body temperature and sends messages to the brain to cool his body down. The brain sends messages to the skin to make his sweat glands start producing sweat to allow some of the heat to evaporate off his body. The hairs on his skin remain flat to not trap an insulating layer of air. His blood vessels allow blood to flow to the capillaries called; vasodilation so that the heat can be brought to the surface of the skin and lost through the skin."]).
answer(number(6),part(c),subpart(0),[100,	1	,"David's body detects a temperature change because of nerves in his skin.  These nerves send sensory neurones up to David's brain.  His body's control mechanisms return his temperature back to normal by opening the blood capillary loop so that blood flows near surface of his skin - temperature decreases.  The hair on his skin lie flat.  This is called vasodilation."]).
answer(number(6),part(c),subpart(0),[101,	0	,"Davids body detects this temperature change through his nerve cells which send chemical messages to his brain or central nervous system. His body attemps to return his temp to normal in several ways. His hairs stand on end to trap air and therefore insulate the body. The body (vasiloconstricts) stops blood getting into blood capillaries near the skin surface to help retain heat."]).
answer(number(6),part(c),subpart(0),[102,	0	,"This happens by hormones detecting the rise in temp which causes the sweat glands to open and the blood supply in the skin to open as well.  The hairs on the body lay flat and sweat comes out from sweat pores over the body.  i.e. under arm pits.	"]).
answer(number(6),part(c),subpart(0),[103,	0	,"The body will do a number of things. It will produce sweat to cool down the bodys temperature. It use tiny sensors in the body to detect the change. The body is ment to be 37ºC if it rises it will attempt to counteract it."]).
answer(number(6),part(c),subpart(0),[104,	1	,"sensors in the body relay information about his temperature to the pituitary gland. This in turn activates the body's control mechanisms, so he begins to sweat to lose heat energy through evaporation and the blood vessels in his skin dilate to increase their surface area and lose heat that way."]).
answer(number(6),part(c),subpart(0),[105,	0	,"The body detects temperature change as the blood vessels are wide and near the surface. Also because Adrenaline is going around the body and more energy is needed. His body attempts to get his temperature back to normal by letting the hairs lie flat, and the sweat gland produces sweat which comes at the sweat pore and cools the body surface. The blood vessels are also very wide and near the surface so there is more heat loss."]).
answer(number(6),part(c),subpart(0),[106,	0	,"Haemostacious is the process which trys to keep a constant internal environment.  This detects that Davids body temperature is becoming to warm.  In reaction to this blood vessels become more present on the skins surface, in attempt to loose heat through the skin, sweat gland begin to produce sweat through the sweat pour, and hairs do not protude so much from the body."]).
answer(number(6),part(c),subpart(0),[107,	1	,"Davids heart pumps faster because he needs more energy and to cool him down his blood runs close to the surface to let of heat	"]).
answer(number(6),part(c),subpart(0),[108,	2	,"David's body has a thermoregulatory centre in the brain, which detects heat and other changes to the body.  The sweat glands beneath his skin release sweat which then evaporates on the skin's surface, cooling it down.  The capillaries allow the blood to flow nearer to the surface of the skin by vasodilation, giving off more heat.  The temperature then drops back to normal."]).
answer(number(6),part(c),subpart(0),[109,	0	,"homeostasis detects that his inner body temperature is too high so, his capillaries under the skin open and allow blood to heat up the sweat gland causing it to use the bodies energy to evaporate, cooling the body down, also the hairs lie flat.	"]).
answer(number(6),part(c),subpart(0),[110,	0	,"Sensory neurone at the skin detect the change and send an impulse to the Central nervous system and his brain will send a message back through a motor neurone to the skin to increase body supply or increase metabolism.  He will also sweat to keep cool and his hear will pump more blood through per minute."]).
answer(number(6),part(c),subpart(0),[111,	0	,"Nerves detects a change in temperature. David will breath more heaverly taking in oxygen to return to a normal temp"]).
answer(number(6),part(c),subpart(0),[112,	2	,"The temperature is detected in blood capillories where heat is concerned they contract sending impulses to the brain via nerves. In response the sweat gland release water to increase evaporation - releasing heat in the process hairs also stand on end to prevent convection- heat trapping against skin"]).
answer(number(6),part(c),subpart(0),[113,	0	,"His body detects this by his feedback control system (linked with homeostasis).  Homeostasis keeps the environment inside the body the same, and so after our hairs lie flat, and we sweat, our feedback control system senses the temperature has changed, and it cools him down by sweating."]).
answer(number(6),part(c),subpart(0),[114,	0	,"The temperature dectors in his body detect a rise in body temperature.  The neurones send an electrical message to the brain to inform it of this change.  Then the brain sends out either a chemical or electrical message to certain places to cool the body down eg. hair on the skin bends over to allow cool air to conduct with the blood easier."]).
answer(number(6),part(c),subpart(0),[115,noanswer]).
answer(number(6),part(c),subpart(0),[116,	2	,"The CNS detects the level of heat in the blood. Homeostasis is the system which tries to keep all the conditions in the body constant & thermalregulation is part of this. To try and return this temp back to normal the blood vessels are stimulated and vasodilation occurs. The hair muscles are also stimulated to ensure that the hair on the skin is pulled flat onto the skin."]).
answer(number(6),part(c),subpart(0),[117,	0	,"The body detects the temperature change because the body is dehydrated and needs water. His body temperature goes back to normal when he starts sweating and by doing that it cools him down"]).
answer(number(6),part(c),subpart(0),[118,	2	,"His body detects this temperature change as his heart is beating blood round the body faster, and the muscles are working hard. His body's control mechanisms attempt to return his temperature back to normal, by his sweat pores opening to release unwanted body heat, as the sweat is evaporated from the skins surface. Also more blood surface to sent to the blood vessels near the skins surface to let heat radiate out of the body into the world around him."]).
answer(number(6),part(c),subpart(0),[119,	3	,"The temperature of his blood is detected by the hyperthalamus, a part of the brain. This then sends messages to parts of his body to correct the levels. Such as vasodilation, where blood flows close to the skin radiating heat. His sweat pores produces sweat which evaporates leaving the surface cooler. Hair lies flat against the skin alowing air to move freely past."]).
answer(number(6),part(c),subpart(0),[120,	1	,"The skin (receptor) on David detects the temperature rise (stimulus) then this message travels through the rely neuron to the brain which then makes the sweat glands begin to produce sweat.  Sweat covers the skin and to cool the body cool air that passes over the sweat will make it evaporate which cools the body down."]).
answer(number(6),part(c),subpart(0),[121,	2	,"When exercise is done, more energy is produced which results in an increase in temperature. The brain detects this and send an electrical impulse which tells the blood vessels to vasodiolate. Sweat glands in the dermis extract water which comes to the surface, and is evaporated of the skin. This causes cooling which helps maintane the correct temperature of the body."]).
answer(number(6),part(c),subpart(0),[122,	1	,"David's brain senses that the body is becoming too hot. It sends signals along the nerves to stimulate sweating. The sweat gland produces sweat on the skin surface encourages heat loss. The hair muscle also relaxes so that the hair lies flat on the skin so that air is not trapped by it. The blood capillary also moves nearer the surface of the skin to help heat escape."]).
answer(number(6),part(c),subpart(0),[123,	1	,"Nerve endings send messages to the brain which then encourages sweating, expanding of blood vessels etc"]).
answer(number(6),part(c),subpart(0),[124,	2	,"His brain detects the rise in blood temperature and signals the blood vessels to rise towards the surface and to open up the surface blood capillaries."]).
answer(number(6),part(c),subpart(0),[125,	1	,"Receptors in the skin detect the increase in temperature, they pass on energy to the sensory neurone which generates electrical impulses. These messages are sent to the co-ordinator (in this case the brain) and the brain controls the response to be given.  The electrical pulse is sent back along the motor neuron to the effector which causes a response. In this case the response would be sweating and vascochilating of blood vessels."]).
answer(number(6),part(c),subpart(0),[126,	0	,"The sweat glands excrete sweat."]).
answer(number(6),part(c),subpart(0),[127,	0	,"The receptors in his body detect a temperature change and send a message via the spine to the brain. The body control mechanism tries to restore his body to it's normal temperature by producing sweat which gets caught under the bodies hairs cooling the body."]).
answer(number(6),part(c),subpart(0),[128,	0	,"His body detects this because David is needing more oxygen. His sweat glands produce sweat to get rid of extra fluids in his body and to release heat. The hairs on his arms stay lying flat."]).
answer(number(6),part(c),subpart(0),[129,	1	,"The sweat glands produce sweat which cools the body and the vessels become slightly larger and more blood goes through that is why hot people go red as the oxygen in the blood is carried quicker."]).
answer(number(6),part(c),subpart(0),[130,	0	,"His body detects the change through heat sensors which sends a message to the brain.  The reactors then send a message back telling his pores to open and his sweat glands to start producing sweat.  The blood vessels also rush towards the skin to cool the blood which is why when you exercise you look red."]).
answer(number(6),part(c),subpart(0),[131,	1	,"David's body detects the change through homeostasis.  His body's control mechanisms then produce more sweat, forcing the heat out of his body through water vapour.  The blood vessels then force the hairs on his body to lay flat so that more heat can escape freely"]).
answer(number(6),part(c),subpart(0),[132,	1	,"His skin and muscles detect his body temperature is above normal and so they 'instruct' the sweat glands to produce sweat as this will cool down the body when it evaporates. Hair muscles on his arm relax, which forces the hairs to lie flat and therefore they do not trap heat. His blood capilbries near the surface of his skin widen so that  more heat is lost from the blood due to a larger surface area. This is called vasodilatation."]).
answer(number(6),part(c),subpart(0),[133,	1	,"The sense organs will detect the increase in temperature. These will go from the skin to the brain which will go to the sweat gland which will make him sweat. Also. the hairs on his body will lie flat so as to stop his body from trapping heat and his blood vessels will dilate to let him lose more heat from the blood."]).
answer(number(6),part(c),subpart(0),[134,	2	,"The hypothalamus in the brain measures temperature of David's body and when David is playing football it notices an increase in the body temperature. It then sends messages in the form of electrical impulses via the central nervous system to the skin espe"]).
answer(number(6),part(c),subpart(0),[135,	0	,"David plays football and realises he's sweating which means he is loosing energy out of his body making him hot, and this is how he detects this temperature change. Even though David is very hot and sweaty his body tries to get back to normal temperature, and by doing this"]).
answer(number(6),part(c),subpart(0),[136,	0	,"As he is running his blood cells are converting more Co2 and therefore producing more heat as well. the blood vessels detect this. Therefore, the open up the blood supply to the skin in an effect to release heat. The sweat glands begin to secrete sweat in an effect to cool the body and the hairs lay flat so it is easier for heat to escape as the extra layer is not insulating any heat."]).
answer(number(6),part(c),subpart(0),[137,	0	,"The temperature change is detcted by the sweat leaving his body and the blood vessels getting larger, to let more blood through. To return him to his normal temperature he starts sweating to cool his skin down and the blood vessels get bigger."]).
answer(number(6),part(c),subpart(0),[138,	1	,"Heat sensors detect the change in temp, and send a message through a sensory neurone to the spine where the message is passed on to a relay neurone which passes the message on to the brain, and the effectors the motor neurone sends the message for his hairs to lay down flat, minimising the air space between hair + skin and he is also told to sweat which will cool him down through evaporation. Also his blood will flow close to the surface, to loose heat."]).
answer(number(6),part(c),subpart(0),[139,	0	,"His temperature rises above normal, his hair on his arms lay flat so that no air can be trapped therefore it doesn't insulate his body his sweat pores open, the heat condenses to form sweat which cool his body"]).
answer(number(6),part(c),subpart(0),[140,	0	,"The body temperature is detected through the rise of the bloods temperature.  The body reacts to this by the sweat gland producing sweat, and leting it out of the sweat pore.  This then cools the skin temperature down."]).
answer(number(6),part(c),subpart(0),[141,	2	,"The brain in particular the hypothalumus detects the temperature change. It sends signals / nervous impulses) to sweat glands to produce sweat, which will evaporate, having a cooling effect. Also the blood vessels near the surface of the skin will vascodilate - increasing area - increasing area for heat to be lost."]).
answer(number(6),part(c),subpart(0),[142,	0	,"As his body temperature rises the blood capillary loop near the surface of the skin gets warmer.  As the blood passes to the sweat gland it detects the rise in temperature.  As it does this it takes some water from the blood and leaks it out through the sweat pore, which cools the skin down and lowers the body temperature."]).
answer(number(6),part(c),subpart(0),[143,	2	,"The change in temperature is detected by the hypothalemos (constantly monitored) If his body temperature rises too high, his body tries to re-stable his temperature by doing the following things: hair muscles relax so all his hairs lie flat so that no air is trapped; The blood supply opens up so that blood travels closer to the surface of his skin to let out heat; He will begin to sweat so that the evaporation of the sweat on his skin will cool him down."]).
answer(number(6),part(c),subpart(0),[144,	2	,"His body recognises the temperature change as his whole body is working harder, his heart is pumping faster and his lungs are breathing more rapidly. His body tries to cool him down by the hairs on his shin lying flat to avoid trapping air and sweating so that when the sweat evaporates it will use his bodies heat to do so and cool him down."]).
answer(number(6),part(c),subpart(0),[145,	3	,"David's body detects the change in the hypothalamus when the blood flows to the brain. This then sends messages to the rest of the body to cool it down. The sweat glands produce sweat which is evaporated off the skin using the heat energy to do so, the blood vessels contract, so that heat loss is increased"]).
answer(number(6),part(c),subpart(0),[146,	0	,"His body is detect change because he is losing water.  The body trys not to lose alot of water, so he will not dehighder	"]).
answer(number(6),part(c),subpart(0),[147,	1	,"Davids body detects the temperature rise by sending signals to his brain. His brain then tells his body to sweat, sweating carries heat away from his body so attempts to bring his body temperature back to normal.	"]).
answer(number(6),part(c),subpart(0),[148,	1	,"Messages are sent to Davids brain which tell his body to cool him down. He therefore sweats more to cool him, his hairs lie flat to allow heat out and his blood vessels descend down away from the surface of his skin."]).
answer(number(6),part(c),subpart(0),[149,	1	,"Davids brain senses that body temperature has fallen below normal. It's gland sends a hormone in the blood. Firstly, this hormone tells the hair cells to stand on end. This creates a layer of air trapped in the hairs around the body. This will warm the body up. Secondly the body stops producing as much water to keep the water levels in the blood constant.	"]).
answer(number(6),part(c),subpart(0),[150,	1	,"The brain detects the temperature change, it can do this as blood passes through the brain & it can detect temperature. Blood capillory loops rise to try and expel some of the heat. Heat is also transmitted, from the blood into sweat through convection the sweat is then released from the sweat gland removing the heat"]).
answer(number(6),part(c),subpart(0),[151,	0	,"First, the temperature changes (increased) because he is coming around and his heart and lungs are working faster. This means that he is using up more energy than normal one way of returning the temperature back to normal is that the body lets out sweat so the body becomes cooler or, David should rest for a while so the body becomes cooler	"]).
answer(number(6),part(c),subpart(0),[152,	2	,"David's brain detects his body's temperature change. His body's control mechanisms attempts to return his temperature back to normal by sweating. When you sweat, the sweat evaporates and 'removes' heat with it."]).
answer(number(6),part(c),subpart(0),[153,	3	,"As the blood passes through the brain it checks the temperature, when it senses it is above normal the brain sends a message round the body to do something about it. The body will then begin to sweat more because the sweat gland releases more water. Also the blood vessels rise to the surface of the skin to release some of the heat onto the skin so it evaporates the hairs will lay flat so the water can evaporate off them taking the heat with it."]).
answer(number(6),part(c),subpart(0),[154,	1	,"The nerve endings on the surface of the skin, detect the rise in temperature.  The hairs lie flat against the skin and the blood cappileries dilate (vasodilation).  He will also produce sweat, through the sweat pores, a quick way of losing heat."]).
answer(number(6),part(c),subpart(0),[155,	1	,"The brain senses heat increase through the nerves causing the sweat glands to make David sweat.  When this is produced the air around evaporates this making David feel cooler."]).
answer(number(6),part(c),subpart(0),[156,	0	,"The hairs on his body rise to let out some of the heat maintained in his body and his sweat glands produce sweat to try to keep him cool. David will sweat for a while and produce bodily odurs which will keep his body temperature down. His heart will pump faster to try and produce more blood flowing through his body.	"]).
answer(number(6),part(c),subpart(0),[157,	3	,"David's body detects this temperature change because the homeostasis is the maintenance of a constant internal environment, and one of the things that need to be kept constant in the body temperature. The hypothalomus detects the temperature change so a message is sent down to the tissue fluid and they attempt to turn his temperature back to normal by making the arteries expand near the surface of the skin allowing more blood to flow near the surface, so more heat is lost by radiation, the hairs on the arms lie flat and the sweat glands produce sweat, which cools the skin and the blood flowing through it. 	"]).
answer(number(6),part(c),subpart(0),[158,	2	,"The hypothalamus monitors body temperature - it detects the temperature rise and sends a message to the skin which starts sweating to attempt to get rid of excess body heat, as well as carring out the process of vasodilication"]).
answer(number(6),part(c),subpart(0),[159,	1	,"Temperature receptor cells in skin detect change which sends impulses upto hypothalamus in brain.  His temperature falls as he starts to sweat, sweat spreads on skin, and is evaporated taking energy 	emperature falls.  Also blood vessels come near to the skin and dialate lots of blood flows more energy/heat evaporated leaving less heat 	emperature falls."]).
answer(number(6),part(c),subpart(0),[160,	0	,"David detects the temp change because he comes hot and, sweat occurs where the sweat pores are releasing water from the blood his hairs lay flat tempting to not store air there."]).
answer(number(6),part(c),subpart(0),[161,	0	,"They detect it by the increase of the blood flow and the amount of the sweat pore coming out of David.  The mechanisms are trying to return by decreasing the blood flow and pumping more oxygen to the Davids systems.  And all his mechanisms."]).
answer(number(6),part(c),subpart(0),[162,	0	,"Davids body detects temperature change by how hot he is getting and his hair will lie flat detected by the hair muscle and he will start to sweat and open the sweat pore, which is controlled by the sweat gland.  It increases the surface are the fat layer doesn't swell reducing heat. the blood is pumped slower."]).
answer(number(6),part(c),subpart(0),[163,	1	,"This is due to thermoregulation and homostasis, which is the body detecting change in the body temperature and attempting to control it. It does this by producing sweat, which is evaporated from the skin, cooling it and by making hairs on the body lie flat."]).
answer(number(6),part(c),subpart(0),[164,	1	,"The rise in temperature is detected and sent to the brain. The blood vessels flow around the blood capillary loop and the sweat gland starts producing sweat. The hair stays relaxed. The water in the sweat helps to cool David. The sweat evaporates away as well."]).
answer(number(6),part(c),subpart(0),[165,	3	,"David's brain has special receptors which monitor blood temperature. The exercise causes that temperature to rise and David's brain tells the body to loose heat. It does this 3 ways. Firstly the blood flows into the blood capillary loops which allow heat to radiate from the blood. Secondly the sweat glands open which allows heated water to evaporate into the air. Thirdly the hairs on his body lay flat which means no air is trapped close to his body preventing heat from escaping."]).
answer(number(6),part(c),subpart(0),[166,	0	,"Stimuli in the Skin may detect his skin is too hot, the blood vessels will expand to the skin in order for heat to be lost through radiation, Sweat will be produced onto the skin and that will evaporate, lowering body temperature.  The gland in the brain the hypothalamus is responsible for maintaining body temperature."]).
answer(number(6),part(c),subpart(0),[167,	0	,"David's body temperature is detected by the nervous system which tells his brain he needs to cool down.  His body cools down by producing sweat and by making his blood go towards his skin this will make david go red in the face."]).
answer(number(6),part(c),subpart(0),[168,	0	,"The sensory neurones on david skin detect the temperature change and the message is sent through the nerves system to the brain. This sends message back, and triggers of the sweat gland, which released water from the blood vessel through the sweat gland out the sweat pore and onto the skin to cool it down. The liquid is known as sweat."]).
answer(number(6),part(c),subpart(0),[169,	0	,"They will detect it because he would be sweating a lot therefore loosing more water than normal. His heomostatis has the job of detecting this and sends chemical messages to release more ADH from the pulitary gland which realeases more water too cool him down as well as still sweating to cool him down and his skin pores will open up to realease as much heat energy as possible."]).
answer(number(6),part(c),subpart(0),[170,	2	,"The hypothalamus detects the body temperature change which alerts the brain.  To attempt to return his temperature back to normal he produces sweat which cools the body, and the blood vessels get bigger (vasodilation) which activates the sweat pore, opening it.  The hairs lie flat against the skin, thus not trapping any air."]).
answer(number(6),part(c),subpart(0),[171,	1	,"when David's body starts working hard, his nervous system picks this up and sends messages to the brain so that his body control mechanisms start to make his body sweat. The sweat will help release the heat energy that is built up due to aerobic respiration and also help to evaporate heat, keeping the skin cool. To do this, the sweat pores on your skin open, letting heat all the way from the sweat glands which are joined to your blood vessels to escape, which helps the temperature to regulate. The regulation of the body temperature can be due to homeostosis."]).
answer(number(6),part(c),subpart(0),[172,	2	,"The Hypothdmus in your head senses that the body is overheated and sends a nervous impulse to the skin. Hairs lie flat to cool you down, sweat is produced by sweat glands to reduce body temperature. Blood vessels open, this is to increase the amount of heat loss throught your body. All of this is called vasodilatation the above are in order to return your body temperature back to normal."]).
answer(number(6),part(c),subpart(0),[173,	1	,"Davids body detects the changes by impulses to the brain and releases a hormone or activates his body to do react in a certain way - eg open sweat pores in order to lets heat evaporate of the skin by sweating."]).
answer(number(6),part(c),subpart(0),[174,	3	,"A gland in the brain detects the body temperature is too high.  It sends messages in blood vessels to: sweat as water evaporates off skin it cools it, for hairs to lie flat and to open blood supply to area so heat can be lost in the air.	"]).
answer(number(6),part(c),subpart(0),[175,	1	,"David's body detects the temperature change because his skin is sensitive to change in temperature, it sends electrical impulses to the brain (along the sensory + relay neurones) which then send impulses around the body (motor neurone) which causes his body to try and reduce heat.  Blood supply to the skin is increased (vasodilation) which in turn causes the sweat gland to function and the hair to lie flat (hair muscle).  Both, retaining water loss and decreasing the temperature."]).
answer(number(6),part(c),subpart(0),[176,	0	,"the change in temperature is known as the stimulas which goes along a receptor cell to the sensory neurone to the relay neurone so the motor neurone then to the effector which results in a response.  In this case the body's response is to sweat."]).
answer(number(6),part(c),subpart(0),[177,	1	,"* The receptor in the skin detects temperature change. This sends an electrical message down the sensory neurone to the synapse, where the message is changed from electrical to chemical. This is in the CNS (central nervous system). The message will then be changed back to electrical and sent down the motor neurone, which will cause the effectors (control mechanisms) to operate - for instance opening blood capillary loops and sweating, to allow his temperature to return to normal."]).
answer(number(6),part(c),subpart(0),[178,noanswer]).
answer(number(6),part(c),subpart(0),[179,	1	,"When his body temperature rises his nerve receptors feel that his body is using up a lot of energy which is warming up the body.  This is when the body makes his blood vessels flow as near as possible to the skin to release heat and he starts to sweat so his movement in the air can evaporate it off and cool his body down."]).
answer(number(6),part(c),subpart(0),[180,	1	,"The hypothalamus (just below the brain) detects changes in body temperature through signals + electrical impulses passed through the nerves. The hypothalamus then sends signals back to the control mechanisms to tell them that his body is too hot. They the carry out their jobs to attempt to get the body temp back to normal."]).
answer(number(6),part(c),subpart(0),[181,noanswer]).
answer(number(6),part(c),subpart(0),[182,	0	,"The nerves in his skin send electrical pulses to the brain to tell it that the body temperature is too high. Then the brain sends signals back to the skin to make the hair on the skin come back down  by the hair muscle and to the sweat glands to start producing sweat."]).
answer(number(6),part(c),subpart(0),[183,noanswer]).
answer(number(6),part(c),subpart(0),[184,	0	,"When his body realises he is to hot blood goes to the surface (which makes you look red) and you start to sweat."]).
answer(number(6),part(c),subpart(0),[185,	0	,"David's body detects his temperature change because his heart rate goes up and he starts to breath faster.  his body control mechanisms tries to return his body temperature back to normal by his sweat glands producing sweat to come out his sweat pores."]).
answer(number(6),part(c),subpart(0),[186,	0	,"When David plays football his temperature rises so he starts losing breath quicker so his heart pumps more blood to get him breathing more but this also increases his body temperature so he begins perspiring which then cools his body down."]).
answer(number(6),part(c),subpart(0),[187,	0	,"He will sweat to cool him down, this is produced by sweat glands, his hairs will lay flat. Sweat will be released from the sweat pore."]).
answer(number(6),part(c),subpart(0),[188,	1	,"The brain detects he is too hot so sends messages to the sweat glands so they produce sweat as his evaporates it will cool him down.  His hair muscles will relax so the hair lies flat.  The blood vessles dilate-get wider so blood goes to the surface so heat is lost.  This is homeostasis."]).
answer(number(6),part(c),subpart(0),[189,	4	,"The brain senses that the blood around it is above normal temperature it sends messages to the skin to cause the blood capillaries in it to dilate, so more heat can be lost from the blood to the surroundings. The sweat glands start producing sweat which takes the heat away from the skin surface as it evaporates. The hair muscles relax, so the hairs lie flat, so do not trap a layer of insulating, still air"]).
answer(number(6),part(c),subpart(0),[190,	0	,"The pituitary gland detects that the urine concentration is to strong so it sends a signal to start producing ADH and this is sent to the kidneys which absorb more water from the blood to sweat with and cool the body down."]).
answer(number(6),part(c),subpart(0),[191,	2	,"The temperature control centre in the brain detects the rise in David's body  above the adverage temperature , 35ºC. This is an example of negative feed back it sends a message to mechanisms in David's body which then work to produce energy e.g muscles shiver or hairs become erect to trap air which acts as an insulator. Sweating also begins so that latent heat is lost in the form of water vapour."]).
answer(number(6),part(c),subpart(0),[192,noanswer]).
answer(number(6),part(c),subpart(0),[193,	1	,"David's body would now begin to sweat as it has become overheated, this would allow the sweat to evaporate, helping to cool the body.  His heart would also begin to pump quicker, so that oxygen is able to travel to the working muscles.  The airs on Davids body would stand upright allowing more air to travel to his body to cool it down.  He will become more red as his blood has travelled to the surface of the skin, as it is overheated."]).
answer(number(6),part(c),subpart(0),[194,	0	,"The increase body temperature is detected in the blood by hormones.  This causes further hormones to be released which control lead to sweating and blood capillary loops opening both of which cool down the body."]).
answer(number(6),part(c),subpart(0),[195,	0	,"Through homeostasis Messages are sent to the sweat glands in the body to tell the glands that your body is above normal temperature and therefore the sweat produced cools you down.	"]).
answer(number(6),part(c),subpart(0),[196,	0	,"blood detects the rise in temperature and nerve impulses send messages to the brain to try and regain normal temperature.  The body then reduces fluids through his skin (i.e. sweat) which is then evaporated and cools the skin down, therefore reducing body temperature."]).
answer(number(6),part(c),subpart(0),[197,	1	,"His skin has sensory nerves that send impulses to the brain to tell the body its to hot.  He sweats a lot to cool down his body and less blood is travelling to the skin."]).
answer(number(6),part(c),subpart(0),[198,	2	,"the body detects the blood temperature when it is being passed through the brain this will send messages to produce sweat, to cause the warm blood to go to the surface."]).
answer(number(6),part(c),subpart(0),[199,noanswer]).
answer(number(6),part(c),subpart(0),[200,	3	,"The brain moniters the temperature of fluids like blood as they pass through. Nerves - stimuli in the skin also send messages to the brain telling it of the temperature change. His body control mechanisms attempt to return it to normal by, sweating through the sweat pores to lose heat by evaporation, widening the blood vessels to increase heat lose, and lieing the skins hairs flat."]).
answer(number(6),part(c),subpart(0),[201,	1	,"His sweat glands start to produce sweat which evaporates from the skins surface. The moisture retains the heat therefore cooling the skin down."]).
answer(number(6),part(c),subpart(0),[202,	1	,"Davids hypothalmus detects a change in body temperature, which then sends a nervous signal to the skin via blood vessels.  His body tries to get back to normal by producing sweat to cool him down, and by making his hairs lie flat."]).
answer(number(6),part(c),subpart(0),[203,	0	,"David's skin vasoconstricts in an attempt to increase its temperature. His body attempts to return his temperature back to normal by pointing the sweat glands to secrete sweat which cools hims down."]).
